### ISSUE TITLE
Cli Crashes when trying to login. (Windows 10) - Error: Cannot find module '<CurrentDirectory>\index-login'

### ISSUE THREAD

**Issue by fusspawn** [githubsaturn/captainduckduck#1]
when attempting to login using the cli on windows 10 the client crashes with the following error: 

Error: Cannot find module 'C:\Users\paul\index-login'

have posted the output to a gist here: https://gist.github.com/fusspawn/76ce58616050c1956315b026e7c03ab6

**Comment by githubsaturn** [comment]
Thanks for reporting. Fixed in 1.0.5 of CLI. Please update using `npm install -g captainduckduck` and let me know if you still have the issue.
https://github.com/githubsaturn/captainduckduck/commit/7b84ce6379fa2fbe7718b7510b7b96303b2475b9

**Comment by fusspawn** [comment]
Confirmed. This is now fixed. Login works correctly.
