### ISSUE TITLE
Can u make Wordpress example app?

### ISSUE THREAD

**Issue by Brun0AFK** [githubsaturn/captainduckduck#10]
Can u make wordpress example app, just bc in that case u need to integrate mysql db, and wp-cli? I just wonder how will that will work ( I still didnt try much to play with your app but good work dude)

**Comment by githubsaturn** [comment]
It is possible, but it won't be much fun as Captain is made for the application layer of the web-app, not database, persistent storage in general. The database part (MySQL for WP) would have to be created through docker command line which makes the process not intutive for beginers. Since Captain's main premise is to keep things as simple as possible, I'll create that tutorial when it becomes a simple one-click process, like the rest of stuff in Captain :)

My plan is to add support for persistent, MySQL, MariaDB, MongoDB or any other db,  by the end of Dec - maybe even sooner. Anyways, if this is something that interests you, stay tuned until it gets published.

**Comment by githubsaturn** [comment]
**For anyone reading this thread:**
As of version `v0.2.1`, Databases and more importantly One-Click Apps are added. I'll make a tutorial soon. But it's really simple. Just click on "Select From One-Click App" and select WordPress. Captain automatically spins out a WordPress container and a MySQL container, and connects them. If WordPress is your thing, I suggest you try it out soon. In addition to `WordPress`, there are other one-click apps as well: `MongoDB`, `MySQL`, `Postgresql`, `Parse Server`, `PhpMyAdmin `and many more. I'll grow this list to include more app. Let me know if there is a database/app that you want to see as a one-click app 😄

**Comment by MartinKavik** [comment]
@githubsaturn  Nice!
> Let me know if there is a database/app that you want to see as a one-click app
[Minio](https://www.minio.io/) would be awesome as a 1-click app :) Maybe it would be useful to create a Trello board with already existing apps and a column for voting new ones :)
I'll try it with Elm and Elixir+Postgre+Minio, thanks :)

**Comment by shinokada** [comment]
Thanks for your work. I will try it soon.

> Let me know if there is a database/app that you want to see as a one-click app

Laravel will be awesome.

Q1. Laravel and other app require `public` folder to be root folder. How can I set it in captainduckduck?
Q2. Can we use .env file for php app as well? 

😁😁😁😁

**Comment by Ar1sC** [comment]
Also maybe Gitea & NextCloud... I'm trying to do that alone but I am new on the docker area and confused.. :/ Also it would be great if you create a Discord Server for CaptainDuckDuck

**Comment by FistMeNaruto** [comment]
I was wondering if it is possible to have a setup somewhat similar to this:

- Local environment with access to apps (wordpress or anything else) through project.localhost for development (offline), MySQL database
- Staging environment, set up to track `staging` branch in git, deploys both the app and database to a server using `captainduckduck deploy`, access through staging.project.com
- Production environment, set up to track `master` branch,  also deploys like staging, access through project.com

This, or similar, workflow would be great, though I'm not sure if captainduckduck is the right tool for this.

**Comment by githubsaturn** [comment]
> Local environment with access to apps (wordpress or anything else) through project.localhost for development (offline), MySQL database

Yes. You need to have Docker installed. And a local DNS server (On ubuntu 16.04, this is built-in, no need to install). Details: https://github.com/githubsaturn/captainduckduck/wiki/Run-Locally

--------


> Staging environment, set up to track staging branch in git, deploys both the app and database to a server using captainduckduck deploy, access through staging.project.com
> Production environment, set up to track master branch, also deploys like staging, access through project.com

Yes. It's possible to have multiple servers. When you run `captainduckduck deploy` it asks you which server you want to deploy to. However, automatic git tracking is not supported yet. To deploy, you'll have to run `captainduckduck deploy`.
Automatic deployments triggered by push events is being developed , see https://github.com/githubsaturn/captainduckduck/issues/25

**Comment by Brun0AFK** [comment]
Maybe i didnt get it but is it possible to use load balancer with wordpress installed?

**Comment by githubsaturn** [comment]
@Brun0AFK 
WordPress and any other apps is already behind the load balancer (nginx) https://raw.githubusercontent.com/githubsaturn/captainduckduck/master/graphics/captain-architecture.png
