### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by iamrommel** [githubsaturn/captainduckduck#101]
It works fine on my local machine, but every time i deploy it on the server i always got this ngix badgate way error.

Is there are way to see some debugging information so i can determine what is the issue.

**Comment by githubsaturn** [comment]
Make sure your docker version matches thw requirements on wiki.

If your docker version is good,  the please run `docker service ps captain-captain --no-trunc` and copy the output here.

**Comment by githubsaturn** [comment]
Make sure your docker version matches thw requirements on wiki.

If your docker version is good,  the please run `docker service ps captain-captain --no-trunc` and copy the output here. 

Also, what server provider you use?

**Comment by iamrommel** [comment]
I was using digital ocean with thier one-click-apps default setup of docker.

Using the node sample you have does work, but my own simple nodejs does
not, that is why i want to debug it

**Comment by githubsaturn** [comment]
I see. On your server, run:

```
docker service update srv-captain--your-app-name --detach --force  ## this restarts your app
docker service logs srv-captain--your-app-name --since 10m --follow ## this shows last 10 minutes of logs
```

**Comment by iamrommel** [comment]
`root@captainduckduck:~# docker service update srv-captain--app02 --detach --force
srv-captain--app02
root@captainduckduck:~# docker service logs srv-captain--app02 --since 10m --follow
srv-captain--app02.1.raepdkaklz0y@captainduckduck    | npm info it worked if it ends with ok
srv-captain--app02.1.shtuo0jrku6l@captainduckduck    | npm info lifecycle payme@0.1.7~poststart: payme@0.1.7
srv-captain--app02.1.shtuo0jrku6l@captainduckduck    | npm info ok
srv-captain--app02.1.raepdkaklz0y@captainduckduck    | npm info using npm@5.4.2
srv-captain--app02.1.raepdkaklz0y@captainduckduck    | npm info using node@v8.7.0
srv-captain--app02.1.raepdkaklz0y@captainduckduck    | npm info lifecycle payme@0.1.7~prestart: payme@0.1.7
srv-captain--app02.1.raepdkaklz0y@captainduckduck    | npm info lifecycle payme@0.1.7~start: payme@0.1.7
srv-captain--app02.1.raepdkaklz0y@captainduckduck    |
srv-captain--app02.1.raepdkaklz0y@captainduckduck    | > payme@0.1.7 start /usr/src/app
srv-captain--app02.1.raepdkaklz0y@captainduckduck    | > cd server && node ./bin/server.js
srv-captain--app02.1.raepdkaklz0y@captainduckduck    |
srv-captain--app02.1.raepdkaklz0y@captainduckduck    | Listening on port 3000
`


I know from my code that i setup the port to listen to 3000 if i did not specify it. Is there any guides regarding using ports and ip on CDD (captainduckduck). I got a hunch that this port thing is the issue. What do you think.

By the way I really appreciate your project, i hope this get lot success and good luck.

**Comment by githubsaturn** [comment]
If you're using a plain ExpressJS app, Captain automatically sets an environmental variable for your app `PORT=80`. If it doesn't do that, it's a bug in CaptainDuckDuck. Please provide a sample app that exhibits the issue and I'll look into it.

However, if you manually hardcode it to 3000, you can either:
- Replace 3000 with `Number(process.env.PORT || '3000')`
- Modify default nginx config for your app. To do so, go to web dashboard, go to your app, click on EDIT NGINX config. and fine this line: `set $upstream http://<%-s.localDomain%>;` and change it to `set $upstream http://<%-s.localDomain%>:3000;`

**Comment by iamrommel** [comment]
![image](https://user-images.githubusercontent.com/177265/34592188-45551a90-f1fd-11e7-86de-f02b8c32180b.png)

![image](https://user-images.githubusercontent.com/177265/34592217-6d0fea6a-f1fd-11e7-8e4f-701f6c3712c6.png)

![image](https://user-images.githubusercontent.com/177265/34592298-fb43be24-f1fd-11e7-9b30-6a88ce45f7a1.png)


I was using that environment variable but i guess it was still getting from port 3000

**Comment by githubsaturn** [comment]
This is really bizarre. Are you sure you saved your config on the dashboard? Can you please print all environmental variables to see what's in there?
Just add this line: `console.log(JSON.stringify(process.env, null, 2));` right below `normalizePort(...`

**Comment by iamrommel** [comment]
I only got this from the env
![image](https://user-images.githubusercontent.com/177265/34592915-63749f0a-f202-11e7-8106-517a77a60f5c.png)

By the way that variable was setup from the webpack plugin
![image](https://user-images.githubusercontent.com/177265/34592924-7870d59a-f202-11e7-8bef-963aad238c71.png)

**Comment by iamrommel** [comment]
so i guess this webpack definePlugin overrides the the process.env,

and I confirmed it, changing the port to other than 3000 makes it work. I hardcoded the port 80 value from the code, deploy it again it now works fine. Thanks for the info and support.

I wish we have a feature to view the logs inside the captainduckduck web app, there are common feature that i see from galaxy or heroku.

More power and luck for this project, this can compete enough with galaxy or heroku.

**Comment by iamrommel** [comment]
![image](https://user-images.githubusercontent.com/177265/34593280-e29d0ec8-f204-11e7-852a-0177d1fe3793.png)

Here are my postmortem for this case so if anyone with the same issue i got, they can refer to this

1. Check the logs by running 
`docker service update srv-captain--your-app-name --detach --force                ## restarts your app
docker service logs srv-captain--your-app-name --since 10m --follow              ## shows last 10 minutes of logs`

2. DO NOT OVERRIDE THE process.env, there are several settings there that CDD is using.


Thanks for the help @githubsaturn

**Comment by githubsaturn** [comment]
Glad that you figured it out :+1: 

Accessing app logs on the web app is on the roadmap. But before that, build logs are coming to the web app. Stay tuned!
