### ISSUE TITLE
Can't deploy app by `captainduckduck deploy`

### ISSUE THREAD

**Issue by lohazo** [githubsaturn/captainduckduck#102]
I try to deploy sample app but i always got this error
And NetData in server not work as well when i click "Start NetData Engine" it say "NetData is successfully updated." and nothing happen
```
Something bad happened. Cannot deploy "test-php"

{
  "statusCode": 500,
  "body": "Internal Server Error",
  "headers": {
    "server": "nginx/1.13.8",
    "date": "Fri, 05 Jan 2018 03:49:28 GMT",
    "content-type": "text/plain; charset=utf-8",
    "content-length": "21",
    "connection": "close",
    "x-powered-by": "Express",
    "etag": "W/\"15-/6VXivhc2MKdLfIkLcUE47K6aH0\""
  },
  "request": {
    "uri": {
      "protocol": "https:",
      "slashes": true,
      "auth": null,
      "host": "captain.cloud9.iamfail.net",
      "port": 443,
      "hostname": "captain.cloud9.iamfail.net",
      "hash": null,
      "search": null,
      "query": null,
      "pathname": "/api/v1/user/appData/test-php",
      "path": "/api/v1/user/appData/test-php",
      "href": "https://captain.cloud9.iamfail.net/api/v1/user/appData/test-php"
    },
    "method": "POST",
    "headers": {
      "x-namespace": "captain",
      "x-captain-auth": "",
      "content-type": "multipart/form-data; boundary=--------------------------024477817017647375853323",
      "content-length": 10626
    }
  }
}
```

**Comment by githubsaturn** [comment]
You need to "Create" the app before deploying it.

Go to web dashboard > apps and create a new app name `test-php`, then your app becomes available at `http://test-php.cloud9.iamfail.net/`

**Comment by githubsaturn** [comment]
Also, for NetData, do you see this OPEN NETDATA button after you start the engine? Just click on that button and it opens NetData.
![image](https://user-images.githubusercontent.com/10582082/34595960-e3f37e70-f190-11e7-9e47-160cf5c4b162.png)

**Comment by sidharthv96** [comment]
Netdata bug is still there sometimes for me too.
This page wont load, it stays in the start netdata page itself.

**Comment by githubsaturn** [comment]
> This page wont load, it stays in the start netdata page itself.

@sidharthv96 Can you please clarify what you mean by it?

- What happens when you click on Open NetData button? Nothing? Any error? Basic NetData (grey background) page with no content?
- Does it fix itself after a few seconds? few minutes? never?
- Does it fix itself by clicking on Turn NetData Off button and waiting a couple of seconds and Turning NetData on again?

**Comment by lohazo** [comment]
@githubsaturn I do not have that button
Only button Start NetData Engine
After i click it, it say "NetData is successfully updated." But still only one button.

**Comment by githubsaturn** [comment]
Thanks for the info. I have retrofitted the startup script for NetData. Please stay tuned for V0.5
https://github.com/githubsaturn/captainduckduck/commit/1a634bc96857617c8016eddc7418143dcb0aefef
