### ISSUE TITLE
cannot install captainduckduck

### ISSUE THREAD

**Issue by rokal** [githubsaturn/captainduckduck#103]
Hello,

I tried to install captainduckduck using npm and I got this result:

```
$ sudo npm install -g captainduckduck
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: timed-out@^4.0.0 (node_modules/captainduckduck/node_modules/got/node_modules/timed-out):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: No valid versions available for timed-out

npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for duplexer3

```

npm version : 5.5.1
node version : v9.3.0

Is this an issue or a problem by just my side?

I don't have the same problem when installing other librairies.

Help please!

Thanks

**Comment by githubsaturn** [comment]
Thanks for the report. This is a critical issue!
Seems like npm package `update-notifier` is now broken! It's a dependency used by CaptainDuckDuck
try 
```
 npm i --save update-notifier
```
and you'll see the same error. I'll raise the issue with them.

**Comment by githubsaturn** [comment]
npm is down: https://status.npmjs.org/

![image](https://user-images.githubusercontent.com/10582082/34643424-e5e06aba-f2d8-11e7-81bc-efdc30c04244.png)


I'll close this issue as it's not actionable from our end. Once npm is back online, this issue will get resolved automatically.
