### ISSUE TITLE
Deploying a node app

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#107]
Couple of questions/observations:

According to the wiki on the [captain definition file](https://github.com/githubsaturn/captainduckduck/wiki/Captain-Definition-File), we have to have this file alongside the package.json.

In the definition file, the only information for a node app is e.g.:

    {
     "schemaVersion": 1,
     "templateId": "node/8.9.3"
    }

Of these two bits of information, `schemaVersion` is always 1.

Of the other two bits of information, the node version is already specified in the package.json:

    "engines": {
      "node": "8.9.3"
    }

So isn't the captain definition file kinda redundant in this case?  It doesn't specify anything that is actually needed (or not available from somewhere else)?  I'm also generally wary about code or configurations that contain repeated information, because there is the danger of updating one but not the other... what happens if I specify a different node version in the definition file vs the package.json?

Finally, for every new release of node, would we need to wait for captain to catch up and support it... what does "supporting" mean in this respect?  Isn't it just a case of installing whatever node container is specified in the definition/package.json?

**Comment by gnuns** [comment]
Yeah, when engine variable is set on `package.js` the captain definition file is redundant.
But about the node version support, it's based on the [official node.js docker image](https://hub.docker.com/_/node/) versions, which is constantly updated.

**Comment by drmrbrewer** [comment]
> when engine variable is set on package.js the captain definition file is redundant

but we still have to include it?

> the node version support, it's based on the official node.js docker image versions

so we can use any node version supported in docker, regardless of what the captain readme says?  That's kinda what I assumed should be the case, but why is the supported version list in the readme there at all... better just to link to the docker list... otherwise the readme will invariably be out of date a lot of the time.

**Comment by githubsaturn** [comment]
Thanks @gnuns !

> but we still have to include it?
Yes, as it's the standard way to tell Captain what is runtime environment for your application. Not all languages have package.json. Theoretically, we can deduce the node version from package.json/engine. But engine is not a required field. That's the first issue. Second issue is that Captain needs to have language specific code - which is a nightmare to maintain! Anyways, the version you define in your `captain-definition` file is the version your app will use. Similar to your dev machine where you can have node 6 installed on your laptop and your `package.json > engine` might say `4`.

> so we can use any node version supported in docker, regardless of what the captain readme says? That's kinda what I assumed should be the case, but why is the supported version list in the readme there at all... better just to link to the docker list... otherwise the readme will invariably be out of date a lot of the time.

I've included in readme so it's easier for people to read. But it's a good idea to also link it to Docker Hub. Will do that. Thanks!
