### ISSUE TITLE
Redis 1 click app suggestion

### ISSUE THREAD

**Issue by dottodot** [githubsaturn/captainduckduck#108]
I'm sure the list is probably endless for 1 click app but think redis could be a good option to have.

**Comment by RobinsonKameron** [comment]
How can we deploy a docker file without the one click app solution? @dottodot have you deployed a redis container?

I setup a captain-definition that looks like this
```
{
  "schemaVersion": 1,
  "dockerfileLines": [
    "FROM dockerfile/ubuntu",
    "RUN \\",
    "cd /tmp && \\",
    "wget http://download.redis.io/redis-stable.tar.gz && \\",
    "tar xvzf redis-stable.tar.gz && \\",
    "cd redis-stable && \\",
    "make && \\",
    "make install && \\",
    "cp -f src/redis-sentinel /usr/local/bin && \\",
    "mkdir -p /etc/redis && \\",
    "cp -f *.conf /etc/redis && \\",
    "rm -rf /tmp/redis-stable* && \\",
    "sed -i 's/^\\(bind .*\\)$/# \\1/' /etc/redis/redis.conf && \\",
    "sed -i 's/^\\(daemonize .*\\)$/# \\1/' /etc/redis/redis.conf && \\",
    "sed -i 's/^\\(dir .*\\)$/# \\1\\ndir \\/data/' /etc/redis/redis.conf && \\",
    "sed -i 's/^\\(logfile .*\\)$/# \\1/' /etc/redis/redis.conf",
    "VOLUME [\"/data\"]",
    "WORKDIR /data",
    "CMD [\"redis-server\", \"/etc/redis/redis.conf\"]",
    "EXPOSE 6379"
  ]
}
```

and when I run captianduckduck deploy I get this output

```
This might take several minutes. PLEASE BE PATIENT...

Something bad happened. Cannot deploy " youmeblog-redis"


Error code: 1000

Error message:

 App not found:  my-app-redis! Make sure your app is created before deploy!
```

**Comment by githubsaturn** [comment]
FIRST:
Why do I see two app names `youmeblog-redis` and `my-app-redis`? Which one is the correct app name? and what is the other one?

SECOND:
Your dockerfile is wrong. `FROM dockerfile/ubuntu` should be `FROM ubuntu`.

THIRD:
Why don't you simply use the office redis docker. In that case, your captain-definition will be:
```
{
  "schemaVersion": 1,
  "dockerfileLines": [
    "FROM redis"
  ]
}
```
See https://hub.docker.com/_/redis/

**Comment by RobinsonKameron** [comment]
FIRST: That was a typo on my part

SECOND: I used the conversion tool and a common docker file to help out + I took that docker file from a gist

THIRD: I'll try that one out! I'm new to using Docker! Thank you for your help.

**Comment by githubsaturn** [comment]
Added in https://github.com/githubsaturn/captainduckduck/pull/160

Will be released in the next version
