### ISSUE TITLE
Deploying Create-react-app

### ISSUE THREAD

**Issue by danielivert** [githubsaturn/captainduckduck#112]
I tested deploying a react app and it worked great. 

I was wondering if it's possible to trigger the build command after is it deployed to captainduckduck and then load that instead of the development version. Is there a way to do that?

Thanks for the help and congratulations for the amazing work you are doing!

**Comment by githubsaturn** [comment]
Thanks for your comment.

Can you please clarify a bit on what you are suggesting?
Are you referring to the auto-deploy via Github/Bitbucket webhooks? What do you mean by "build command"?

**Comment by aberba** [comment]
I think he means running `npm start` runs it as a node app. But create-react-app requires doing `npm run build` command to generate a static website (in a folder called `build`). He want support for running static websites.

**Comment by danielivert** [comment]
Hi!

Sorry for not being very clear with my question. Basically I was looking to have something like pre-deploy/post-deploy after sending my react app to captainduckduck. I found out that I could use the captain-definition file to convert my Dockerfile and run the commands I needed there.

This is how I solve it, if anyone is wondering how to deploy a react app, the captain-definition I used:

{
  "schemaVersion": 1,
  "dockerfileLines": [
    "FROM node:8.7.0-alpine",
    "RUN mkdir -p /src/app",
    "WORKDIR /src/app",
    "COPY ./src/package.json /src/app/",
    "RUN npm install && npm install -g pushstate-server",
    "COPY ./src /src/app",
    "RUN npm run build",
    "EXPOSE 80",
    "CMD [ \"npm\", \"run\", \"start:prod\" ]"
  ]
}

**Comment by lucasdu4rte** [comment]
captain-definition attempt

```
{
    "schemaVersion": 1,
    "dockerfileLines": [
        "FROM node:8.7.0-alpine",
        "RUN mkdir -p /src/app",
        "WORKDIR /src/app",
        "COPY ./src/package.json /src/app/",
        "RUN npm install && npm install -g pushstate-server",
        "COPY ./src /src/app",
        "RUN npm run build",
        "EXPOSE 80",
        "CMD [ \"npm\", \"run\", \"start:prod\" ]"
    ]
}
```

> Something while retrieving app build logs.. "Error: Error: connect ECONNREFUSED ip:443"

**Comment by danielivert** [comment]
Can you share your package.json file?

My assumption is that there a module regarding SSL that is breaking the npm install. 
Do you have a module with something to force https?

**Comment by lucasdu4rte** [comment]
is a crude version of the react
```
{
  "name": "react-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-scripts": "1.1.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```
this here might help?

> new WebpackDevServer(webpack(WebpackDevConfig), {
>     https: true,
> ....

**Comment by RenanZX** [comment]
Build your app in a local machine, and deploy the build:

https://caprover.com/docs/recipe-deploy-create-react-app.html
