### ISSUE TITLE
Bad gateway for node app (solved... but related question)

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#115]
After deploying my node app and browsing to the web address, I was finding I was getting "bad gateway / nginx" errors in the browser.

With some hints from https://github.com/githubsaturn/captainduckduck/issues/101 I have sorted this, but I have a related question.

In my node code, the express server initialisation was originally based on some boilerplate code that seemed to work at the time, and has done ever since, when testing on cloud9 and deploying to heroku.

What it does is something along the lines of:

    var app = express();
    var port = process.env.PORT || 8080;
    var ipaddress = process.env.IP || '127.0.0.1';
    app.listen(port, ipaddress);

And, you guessed it, since `process.env.IP` was indeed undefined when deploying via captain, it was using `127.0.0.1` instead... leading to the gateway error.  When deploying to heroku, no problems... I assume because `process.env.IP` is defined.

Just listening based on the port fixed this for captain deployments:

    app.listen(port);

However, since `process.env.IP` seems to be a relatively standard/common env var, is it possible for captain to define that env var automatically on deploy, so that code like mine (and others in future) that check `process.env.IP` don't fall over when it is not defined?  It's easy for me to fix, simply by adding the following line to `dockerfileLines` in my `captain-definition` file, but I wonder whether this should be standard for node deployments?

    "ENV IP 0.0.0.0",

**Comment by githubsaturn** [comment]
`process.env.IP` is not being used by all NodeJS applications, it's not standard per se. The built-in `templateId` in `captain-definition` is for super standard nodejs applications. Remember, if you have anything specific about your application, you will have to set a custom Dockerfile anyways. That would make it impossible for Captain to intervene your dockerfile. So you'll have to manually insert `ENV IP 0.0.0.0` to your dockerfile lines.
