### ISSUE TITLE
Very minor typo

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#116]
In the opening part of the deploy process, the following statement appears:

> Note that uncommited files and files in gitignore (if any) will not be pushed to server

`uncommited` should be `uncommitted`

Very minor... hope you don't mind it being pointed out ;-)

**Comment by githubsaturn** [comment]
Typo pull requests are always welcomed 😄 

You can even edit the file on GitHub directly:
https://github.com/githubsaturn/captainduckduck/blob/master/app-cli/captainduckduck-deploy.js

Just edit any files that you want, and it creates a pull request and I can merge it.

**Comment by drmrbrewer** [comment]
done... my very first one, ever...!  was it OK?

**Comment by githubsaturn** [comment]
Perfect 👍 

Feel free to edit any other files if you see any other typo
