### ISSUE TITLE
How to stop and remove captain?

### ISSUE THREAD

**Issue by tymons** [githubsaturn/captainduckduck#12]
Hello,

first of all I am really impressed by this project and found it really helpful. I have tested some cases and  after a while, I want to remove captainduckduck from my local machine. How can it be obtained? I am really noobish with docker.

I tried:

```
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
```

But captainduckduck keeps restarting and I got ngix and captain entries at `docker ps`

**Comment by githubsaturn** [comment]
Captain uses docker swarm to support clustering and restarting containers if they stop. That's why it's keeps re-appearing. Try this:
`docker service rm $(docker service ls -q)`
then
`docker swarm leave --force`

**Comment by ravikiranp123** [comment]
You may also want to delete /captain directory. Doing so will remove the configuration files as well and lets you perform a fresh install.
