### ISSUE TITLE
Captain rollback?

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#121]
Is there an equivalent of `heroku rollback` (to roll back to the previous deploy) and `heroku rollback v123` (to roll back to a specific deploy)?  It seems that previous app images are retained with captain (you can see them with `docker images`), so it should in principle be possible to have a `captainduckduck rollback v123` equivalent?

**Comment by githubsaturn** [comment]
It will be added to Captain dashboard in the future. It's currently supported by Docker. Assuming your app name is `my-app` and your current version is `12` and you want to rollback to version `10`. It's a little confusing at first, but you essentially retag your old version as the new version and update the app:

```
docker service ls --filter name=srv-captain--my-app # copy image name which is something like registry.yourrootdomain.com:996/captain/img-captain--my-app:12

docker tag registry.yourrootdomain.com:996/captain/img-captain--my-app:12 registry.yourrootdomain.com:996/captain/img-captain--my-app:12-backup

docker tag registry.yourrootdomain.com:996/captain/img-captain--my-app:10 registry.yourrootdomain.com:996/captain/img-captain--my-app:12

docker service update srv-captain--my-app --image registry.yourrootdomain.com:996/captain/img-captain--my-app:12 --force

```
