### ISSUE TITLE
Remote access to postgresql database

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#123]
For a postgresql database set up via the captain one-click app method, I can open a shell into the postgres container as follows:

    $ docker exec -it 05b3a3471f6f bash

where the above is the ID of the postgres container.  Then within the shell I can use psql to manipulate the db as normal.  I assume that this is the best way of using psql on the db... please say otherwise!

I'd really like to know, however, if I can perform operations on the captain-created db from a remote host (e.g. my online IDE), via the -h switch, for example to dump a db backup file from the remote (captain) db:

    $ pg_dump -C -O -h host.of.my.captain.db -U myusername -d mydb > dbbackup.sql

**Comment by githubsaturn** [comment]
From https://github.com/githubsaturn/captainduckduck/wiki/App-Configuration#port-mapping 

> The most common use case is when you want to connect to a database container from your local machine. 

So, replace `-h host.of.my.captain.db` with `-h captain.your.domain.com` and add `-p 1234` where `1234` is the host port you mapped to port `5432` of your postgres container
