### ISSUE TITLE
Feedback when a webhook is received on captainduck

### ISSUE THREAD

**Issue by danielivert** [githubsaturn/captainduckduck#124]
It would be nice to get some kind of feedback on the admin dashboard when there has been a webhook from github, gitlab, etc. Otherwise it's hard to know if something is happening in captainduck or not. #25

**Comment by githubsaturn** [comment]
![image](https://user-images.githubusercontent.com/10582082/34918519-8d8c1824-f908-11e7-8801-ad1485dd62bf.png)

Captain shows you the building state. The only caveat is that Captain doesn't use websockets and therefore it doesn't automatically show you the building state if you are already on the app screen. All you need to do is to go to another screen, e.g., Settings, and come back to app to see the building state.
