### ISSUE TITLE
postgres container not showing

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#125]
I set up a new postgres one-click app, and it claimed that it was set up OK, but then I ssh onto my server, and do `docker ps`, there is no postgres container showing.  I have tried deleting the pg app in Captain and adding it again, but still can't see it as a container.  Any troubleshooting I can do?  

My setup is: two servers (nodes), app with four instances, and netdata enabled, and I added the postgres app *after* connecting the two nodes together.  I had previously been testing the postgres app/db with captain, and it all worked as expected, but it was only on a single server setup... does it make a difference?

**Comment by githubsaturn** [comment]
Chances are the db instance is on the second node. SSH to your second node and see if it's there. You can move it to the first (main) node by editing node id in your app's details page. Note that this will delete your current db. However since this is a brand new db, it should not be a concern for you.

**Comment by githubsaturn** [comment]
Where your container will end up is totally in hand of Docker Swarm, not CaptainDuckDuck. This decision is usually pretty smart and it takes multiple factors into consideration. More details:  https://docs.docker.com/engine/swarm/services/#control-service-placement

In defense of Docker Swarm:
And the placement of your DB on the second node is not a bug at all! Imagine you have 1 main node and 100 worker nodes, and you're trying to deploy 500 apps. Do you really expect all your apps end up on your main node? Surely not.

Again, note that, if you really need to move your DB to the main node forcefully, you can still do that. CaptainDuckDuck using Docker Swarm allows you to optionally specify a node where you want your service to run by editing Node ID.

**Comment by drmrbrewer** [comment]
> where your container will end up is totally in hand of Docker Swarm

Not *totally*... it seems like you have some degree of control e.g. via [placement constraints](https://docs.docker.com/engine/swarm/services/#placement-constraints).

> Do you really expect all your apps end up on your main node?

If I have an app that needs to be replicated 500 times, then yes I would expect these instances to be spread across the 100 nodes.  I have the flexibility to change the instance count in captain depending on need, and if demand drops right down I can even take the instance count back to 1, in which case everything can be handled by one server and I can destroy all but one server and pay only one server cost.

But the postgres app is a bit different, not least because it has persistent storage.  Therefore, if node 1 has core things like captain, nginx, certbot etc, and if postgres ends up on node 2, then when demand on my main app drops and I reduce the instance count for the main app down to 1, I am still stuck with two servers.

So I would have expected the core apps to be on the main node, with worker nodes being for replicated apps.  Yes that means that the main node is more overloaded with apps than others, but I can just have a slightly larger main node to accommodate this?

So isn't it possible to force the pg app onto the main node via a placement constraint?  I'm happy to hear any opinion to the contrary, i.e. that it's better to have the pg app on the second node for some reason.

BTW it also seems to me that the pricing structure of digitalocean and vultr tends to suggest that it can be better to deploy e.g. N nodes of size S than one node of size NxS.  E.g. for $5 on vultr you get 1CPU and 1GB RAM while for $10 you get 1CPU and 2GB.  So it's better to have 2 at $5 than 1 at $10 because you get an extra CPU.  And better to have 4 at $5 than 1 at $20.  Is there any downside to this approach?  I know that each server comes with an overhead (basic things like docker and other libraries), so you're not getting as much useable RAM, but the extra CPUs are surely invaluable?

**Comment by githubsaturn** [comment]
> Not totally... it seems like you have some degree of control e.g. via placement constraints.
> 
> So isn't it possible to force the pg app onto the main node via a placement constraint? I'm happy to hear any opinion to the contrary, i.e. that it's better to have the pg app on the second node for some reason.
> So I would have expected the core apps to be on the main node, with worker nodes being for replicated apps. Yes that means that the main node is more overloaded with apps than others, but I can just have a slightly larger main node to accommodate this?

Look at the last paragraph from my previous comment:

> Again, note that, if you really need to move your DB to the main node forcefully, you can still do that. CaptainDuckDuck using Docker Swarm allows you to optionally specify a node where you want your service to run by editing Node ID.

-------

> BTW it also seems to me that the pricing structure of digitalocean and vultr tends to suggest that it can be better to deploy e.g. N nodes of size S than one node of size NxS. E.g. for $5 on vultr you get 1CPU and 1GB RAM while for $10 you get 1CPU and 2GB. So it's better to have 2 at $5 than 1 at $10 because you get an extra CPU. And better to have 4 at $5 than 1 at $20. Is there any downside to this approach? I know that each server comes with an overhead (basic things like docker and other libraries), so you're not getting as much useable RAM, but the extra CPUs are surely invaluable?

Each provider has its own schema. But keep in mind that 512MB instances are just for playing. First off, OS uses one-third of that RAM. Also, most complex builds fail with that small amount of RAM. You at least need 1GB. I suggest min 2GB.
If you're looking for a cheaper option, look at ScaleWay. Make sure you pick one of their x86 options, not their ARM CPUs as Captain is compiled for x86 CPUs. I am using their 2GB instance and it's 3.99 euro per month (I think)


PS: Your other questions and comments are related to your specific architecture and I cannot comment on it.

**Comment by drmrbrewer** [comment]
Sure, I understood that you could move the DB to node 1 already, but I'm questioning whether it would be preferable for the DB to be placed by captain onto node 1 (the master/leader) by default.

Thanks for the suggestion re scaleway, I'll have a look... their 2GB instance is EUR 2.99.  So far have they seemed to be reliable with good performance?

**Comment by githubsaturn** [comment]
> Sure, I understood that you could move the DB to node 1 already, but I'm questioning whether it would be preferable for the DB to be placed by captain onto node 1 (the master/leader) by default.

Depending on your application, it might be preferable and might not be. Docker swarm makes no presumption with regards to your application. If you find it good to have your DB locked down to your main node, you can do so. But the default behavior for docker swarm is totally unopinionated. 


> Thanks for the suggestion re scaleway, I'll have a look... their 2GB instance is EUR 2.99. So far have they seemed to be reliable with good performance?


So far so good. I am not running any mission critical app on their platform at the moment, but haven't faced any issues with my tiny deployments so far.
