### ISSUE TITLE
CI/CD integration

### ISSUE THREAD

**Issue by Rusfighter** [githubsaturn/captainduckduck#126]
Hello, 

First, great project!

Secondly, I have a question regarding continuous integration + continuous delivery pipeline. Currently as I am reading the wiki, it is only possible to listen for a push event on a specific branch. I wonder if it is possible to only listen for those push events if CI passes (CircleCI, travis), just like heroku offers for deployment. 

One workaround I am thinking of now is whenever CI passes, the service (eg CircleCI) merges the "development" branch into the "release" branch (for which cdd is configured). Am I correct? 

Thanks,

Ilija

**Comment by githubsaturn** [comment]
> One workaround I am thinking of now is whenever CI passes, the service (eg CircleCI) merges the "development" branch into the "release" branch (for which cdd is configured). Am I correct?

This is correct. For my deployment, I usually have a `captain-deploy` branch that I use.

**Comment by Rusfighter** [comment]
However, how to do this with monorepos?

**Comment by githubsaturn** [comment]
That very much depend on your monorepo structure. If you use git submodoules, you can deploy them independently. If you're entire project is one project, Captain can still handle it, but it's not optimal. Because for every microserver, the entire repo is pulled, but when running the app, you can give it a specific docker file instructions so that it would only run your specific microservice.

**Comment by Rusfighter** [comment]
> the entire repo is pulled
True, but you can minimize the pulls by having smart CD of some sort, I think?

As I check this repository, this is also kind of monorepo (without submodules). However since I don't see any CI files, I wonder how you would manage this project to have some continuous integration using (cicleci, travis etc)?

**Comment by githubsaturn** [comment]
> True, but you can minimize the pulls by having smart CD of some sort, I think?

Two things, first, supporting these edge cases for boosted performance on deploy is a lower priority compared to more general stuff that's sitting in the roadmap. Second, monorepos are not as popular as single repositories. So the effort can be spent where most benefit can be earned. But PRs are always welcome. If you find thing interesting, feel free to fork and PR it.

> As I check this repository, this is also kind of monorepo (without submodules). However since I don't see any CI files, I wonder how you would manage this project to have some continuous integration using (cicleci, travis etc)?

This project doesn't use CI at the moment, releases are done through some local scripts.

**Comment by Rusfighter** [comment]
> Two things, first, supporting these edge cases for boosted performance on deploy is a lower priority compared to more general stuff that's sitting in the roadmap. Second, monorepos are not as popular as single repositories. So the effort can be spent where most benefit can be earned. But PRs are always welcome. If you find thing interesting, feel free to fork and PR it.

The thing i was thinking about is to use cli from service like circleci/travis to deploy (so with ``captainduckduck deploy``, but I am not certain if it is possible since you have built in selection in the tool.

**Comment by Rusfighter** [comment]
Anyway, i made a pull request which should enable direct deployments (from any bash) https://github.com/githubsaturn/captainduckduck/pull/129
