### ISSUE TITLE
SSL access to postgres db

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#127]
I've created a postgres app via the captain console, and mapped container port 5432 to server port 5432 to expose the db to the outside world.

I connect to the db in my node.js app using [node-postgres](https://node-postgres.com/).  In the `config` object used when [opening a connection](https://node-postgres.com/api/client) to the database, with the heroku postgres db I would set `ssl` to `true`.

However, with the db app created by captain, this produces an error along the lines that SSL is not supported, though it works fine with `ssl` set to `false`.  This seems to be the case both for queries from other node apps running within captain, and also from node apps running on heroku.

Is it possible to set things up with captain to allow SSL connections to the pg database?  On the captain Dashboard I have enabled SSL, and also in my main node.js app.  But for the postgres one-click app I can't see any SSL related options to enable.

Thanks in advance.

**Comment by githubsaturn** [comment]
Short answer: No. Captain does not support out of the box SSL for postgres.

The reason is that it's not needed because all your DB and your apps sit on your private network. No communication is made that can endanger data. As a rule of thumb, when encryption is not needed you should not use it. Not having SSL means faster data transfer.

Having said this, it's not impossible to manually setup SSL. A step by step tutorial takes too long. But in short these are the things you should do:
- Map `/captain` in host to `/captain` in your Postgresql
- Now Postgres has access to SSL certs sitting in `/captain/letencrypt`
- Create a new `captain-definition` with dockerfileLines of 
```
FROM postgres:latest
COPY ./src/entry.sh
CMD ["entry.sh"]
```
and put it next to an `entry.sh` file which does:
- Copy SSL cert for `captain.root.domain.com` to `/var/lib/postgresql/data`
- RUN postgres with SSL enabled by adding required flags to `postgresql.conf`

Connect to your Postgres by enabling SSL, setting host to `captain.root.domain.com`


Would Captain at some point automate this? Yes, if it gets native support from `Postgresql` Docker. Creating that `entry.sh` file and requires more-than-beginner Postgres knowledge and continuous support.

**Comment by drmrbrewer** [comment]
Thanks for the informative reply, as ever.  

> all your DB and your apps sit on your private network. No communication is made that can endanger data

Except where the DB is exposed to the outside world by mapping the container port to a server port.  I'm doing this at present, but only during a transition period in which the database is still being queried from other places in the existing infrastructure... but mainly it is being queried from an app running alongside postgres.  Depending on whether the app is running locally or remote, I use one of two configs:

    const configRemote = {
        host: 'captain.myserver.mydomain.com',
        database: 'mydb',
        user: 'myuser',
        port: '5432',
        password: 'mypassword',
        ssl: false
    };

    const configLocal = {
        host: 'srv-captain--mypostgres',
        database: 'mydb',
        user: 'myuser',
        port: '5432',
        password: 'mypassword',
        ssl: false
    };

Outside access will diminish to nothing in a short timeframe so then, yes, the DB will (mainly) be accessed internally.  The only other time I would be making use of outside access is for ease of maintenance, e.g. querying the DB from a remote node e.g. to dump a backup... but the data risk then is quite small.

Presumably at a later stage I can decide to remove the port mapping from the postgres app in the captain console, without any effect on the database itself, so that the db once again becomes internal only?

**Comment by willvincent** [comment]
VPN is overkill for this.. easier to just use ssh tunneling. Most db gui clients already have it built in. Only trick is digging up the proper IP address of the docker container.

`docker exec [your-postgres-container-name] ip addr`

You're looking for the `172.x.x.x` address. 

Then in your db gui, select ssh tunnel, put in the appropriate domain/ip of your server

Put the 172.x.x.x address you looked up in as the host address for postgres, whichever port you're running on (5432 by default), user/pass/db as normal.. 

Boom, easy peasy. secure connection

**Comment by solomon23** [comment]
Wanted to follow up on this.  I wasn't able to get @willvincent version working.  I can find the ip address by doing a `docker container list` and then using `docker exec -it a30dd19a3724 exec sh` to get into the shell and ping the docker container containing the postgres instance by it's friendly name.  

Once leaving that shell the host can't ping that ip address though and using a client to ssh tunnel in doesn't work either against that ip.  is there a way for the host to connect to the postgres docker by an ip address ? It doesn't seem to resolve the friendly name like in the containers either. 

In an ideal world I would get SSL working like mentioned above but it's a bit over my head

**Comment by githubsaturn** [comment]
@solomon23 

I personally haven't tried SSH tunneling. Having said that, Docker containers are attached to multiple network interfaces. Not all of them are accessible from the host. For example:
```
root@docker-host-machine:~# docker exec -it 6fce9abab33c /bin/bash
root@6fce9abab33c:/# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
58669: eth0@if58670: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether 02:42:0a:00:00:68 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.104/24 brd 10.0.0.255 scope global eth0
       valid_lft forever preferred_lft forever
58671: eth1@if58672: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:12:00:07 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.7/16 brd 172.18.255.255 scope global eth1
       valid_lft forever preferred_lft forever
```

The second IP, `172.18.0.7`, is directly accessible from the host, but the first IP, `10.0.0.104`, is not.

**Comment by conao3** [comment]
`ip` commad is not installed `postgres:15.1` docker image.
I can use `hostname -I` to find postgres ip.
```
$ docker exec 25ca6d856279 hostname -I
10.0.0.9 172.18.0.7 10.0.1.23
```
(Then, I should access 172.18.0.7 to login postgres)
