### ISSUE TITLE
captainduckduck deploy using defaults

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#128]
I'd like to include `captainduckduck deploy` at the end of a shell script that performs some other stuff beforehand, but don't want to have to remember to sit there waiting for the actual deploy so that I can confirm the choices requested by the deploy method.  I'm always just accepting the defaults (from the previous deploy), so it would be nice if there were something like `captainduckduck deploy_with_defaults` that just does the deploy without asking any questions.  Or a switch e.g. `captainduckduck -d deploy`.

**Comment by Rusfighter** [comment]
I am also kind of busy with this, only I need to have the CLI in stateless way such that you always asked for a username, password then project name and then the branch. Thus giving the ability to just run one command for example: 

`captainduckduck deploy -u root -p captain42 --container test-project --branch master`

**Comment by Rusfighter** [comment]
@drmrbrewer btw there is already a flag for deploy, check `captainduckduck deploy --help`

**Comment by drmrbrewer** [comment]
@Rusfighter haha, @githubsaturn has thought of everything... thanks for pointing that out.  I agree that it would be extra nice to have command line options to specify the various elements explicitly too.

**Comment by githubsaturn** [comment]
`captainduckduck deploy --default` is already available. Also, thanks to @Rusfighter , soon we will have the option to pass in deployment data inline: https://github.com/githubsaturn/captainduckduck/pull/129/files
