### ISSUE TITLE
How can I help ?

### ISSUE THREAD

**Issue by etienne-dldc** [githubsaturn/captainduckduck#13]
Hi !

I really like CDD and want to know if I can do something to help you ?

Here are my skills: 
- Frontend: 🥇  it's been a while since I've used Angular 1. I'm mostly doing React & Typescript these days...
- Node: 🥈  Can help with that :) (even if I prefer frontent)
- Docker: 🥉  I'm a noob, but I can learn
- Writing doc & other : Sure can do, though english is not my native language.

Thanks for your work !
Etienne.

**Comment by angelopolotto** [comment]
I really liked that project! It is simple and very user friendly. I want to help too, if possible.
Can you talk more about the demands of this project?

**Comment by githubsaturn** [comment]
Thanks @etienne-dldc and @angelopolotto !
I am in the process of planning & prioritizing tasks.  

@etienne-dldc Surely your Angular skills will be useful 👍
@angelopolotto What is your preference regarding the area of contribution?

I created a Telegram group so it's easier to chat:
https://t.me/joinchat/Bgv2LEkKHCwtH-RXU9v5Aw

Will add this link to readme.

**Comment by angelopolotto** [comment]
Thanks for you attention @githubsaturn !
My area is mobile development, IOT and Electronic Engineering. 
I'm a beginner with Angular, Node and Docker but I wanna the opportunity to learn more all those tools.
If possible, I wanna help with Node and Docker part.

**Comment by githubsaturn** [comment]
Sounds good! I am still planning out the roadmap. Once I reach a semi-stable state, I'll be needing much more help as things become more modular and people can work on different pieces without stepping on each other toes. The one area that will be ready to be worked on soon, hopefully by January, is automated testing. It'll be a perfect combination of Node and Docker. It'll involve testing nodejs code, talking to docker API, perhaps talking to DigitalOcean API and much more. I'll have more details for you soon. Please email me your contact info captainduckduck.github<AT-G MAIL DOT COM>

**Comment by angelopolotto** [comment]
Great! I'll send to my contact info to you.

**Comment by RohitK09** [comment]
@githubsaturn this seems really awesome, would like to help 

My skills ,nodejs, Angular 1 or 2 /4 and Java

**Comment by petercr** [comment]
@githubsaturn I am already a huge fan of this project, mainly because the idea is **SO AWESOME** 😎 
And I would love to help out if I can. I can do front-end stuff but have some familiarity with Linux, the command line, And I would be willing to help with writing any docs too 👍 :shipit:

**Comment by ivanthemeh** [comment]
I would like to get involved in this as well. I can pretty much learn anything and have dabbled in a lot of different frontend and backend frameworks.
Have you considered setting up a trello roadmap or something similar? 
I can see a lot of support for this is the future as it is REALLY cool and very promising.

Please let me know how I can get started helping with this even if its just where to start reviewing the current code to learn more about it and how it works. Thanks!

**Comment by ngoyal16** [comment]
hello team,

**Comment by ngoyal16** [comment]
my skills are Nodejs, Python, PHP, docker, and AWS. I just start looking into the system I can help with the design and backend part.

**Comment by githubsaturn** [comment]
# JOIN TELEGRAM CHANNEL:
https://github.com/githubsaturn/captainduckduck/issues/13#issuecomment-342008999

**Comment by etienne-dldc** [comment]
I guess I can close this issue right ? @githubsaturn  ?

**Comment by KaKi87** [comment]
Hello, the Slack invite link is down, thanks

**Comment by githubsaturn** [comment]
@KaKi87  - thanks for the ping, fixed. Please retry.

**Comment by KaKi87** [comment]
Il works now 😉

**Comment by Boscop** [comment]
> Thanks @etienne-dldc and @angelopolotto ! I am in the process of planning & prioritizing tasks.
> 
> @etienne-dldc Surely your Angular skills will be useful 👍 @angelopolotto What is your preference regarding the area of contribution?
> 
> I created a Slack group so it's easier to chat: (link at the footer of CapRover.com)
> 
> Will add this link to readme.

The [Slack invite link on the website](https://caprover.slack.com/join/shared_invite/zt-o8obmx7o-x9icEG5fDAtvE9zhHlltzQ#/shared-invite/error) doesn't work:

> This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link.

@githubsaturn What's the current link? :)

**Comment by githubsaturn** [comment]
Slack somehow invalidated the link. Updated the link again. Try again and let me know if it doesn't work.
