### ISSUE TITLE
Bad Gateway after sucessfull deployment

### ISSUE THREAD

**Issue by GitHubTodoOpen** [githubsaturn/captainduckduck#130]
Jenkins Docker app deployment is successfull but some issue related causes bad gateway.

docker service logs srv-captain-my-app --since 60m --follow

screencapture:
<img width="1635" alt="screen shot 2018-01-17 at 10 25 41 am" src="https://user-images.githubusercontent.com/31350366/35048140-9c34ce4a-fb72-11e7-939d-50141ea63240.png">

Kudos for all the good work on captainduckduck, I'm really loving it!

**Comment by githubsaturn** [comment]
If I remember correctly, Jenkins run on 8080, not 80. Nginx by default binds to port 80. If you want it to bind to a non-standard port, go to your apps settings, click on Edit Nginx Config and change this line:
```
set $upstream http://<%-s.localDomain%>;
```
to
```
set $upstream http://<%-s.localDomain%>:8080;
```

**Comment by GitHubTodoOpen** [comment]
Solution work perfectlly, thanks!
