### ISSUE TITLE
Backup / restore / moving to new server

### ISSUE THREAD

**Issue by dottodot** [githubsaturn/captainduckduck#131]
Just wondering if there is anything currently in place that would allow for moving my current installation and settings to a new server i.e by something like backup and restore.

**Comment by githubsaturn** [comment]
I haven't got around automating this. But these are the steps:
- Install Captain in the standard way on the new server. No need to run `captainduckduck serversetup`.
- Run `docker service logs captain-captain --follow` and wait for successful finish msg. It says "Captain is ready". When you this message, press ctrl+c and then type `docker service scale captain-captain=0`
- SSH to your server and convert your `/captain` directory to tar file
- Copy the tar file to the new server and extract it into `/captain` overwriting the existing directory.
- Open `/captain/config.conf` and remove these two lines: `captainRegistryAuthSecretVer` and `hashedPassword`. This will reset the password to `captain42` and removes the Docker registry. These two steps have to be manually re-applied (reason: these are secure values and use docker secret)
- Run `docker service scale captain-captain=1`

Caveat: this does not copy your persistent data from apps that are held in Docker volumes - such as DB data.
