### ISSUE TITLE
Minor UI issue on mobile

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#132]
Just a minor UI issue on the login page, when using a mobile browser in portrait orientation.  Landscape is fine.  It's not a huge problem for me since the password is auto filled, so I just hit the button, but may be worth looking at.  See below.

![35058630-74735762-fbb0-11e7-920e-a5c3548456f2](https://user-images.githubusercontent.com/9009792/35087260-83d41990-fc27-11e7-9be9-8c247948a92a.jpg)
![35058646-80d90f74-fbb0-11e7-9784-bdadf8e41fa9](https://user-images.githubusercontent.com/9009792/35087264-875f6560-fc27-11e7-9859-be6435a33109.png)

**Comment by githubsaturn** [comment]
It's not just the login screen. Most elements do not work properly on mobile. Since you can't do much on mobile anyways, this is very low priority.

**Comment by drmrbrewer** [comment]
> most elements do not work properly on mobile

That's not my experience.  Apart from the login screen, most of the other elements are laid out pretty well, and it's all usable.  But I agree that this is low priority.

**Comment by Rusfighter** [comment]
You can request desktop version if you on mobile chrome?

**Comment by drmrbrewer** [comment]
Yes, true.  Desktop version does look better (with the usual issues with displaying a wide page on a small screen).

**Comment by githubsaturn** [comment]
Fixed in https://github.com/githubsaturn/captainduckduck/commit/adffcba20ff353b943b19662e2fac5b66742cfaf

Will be released in the next version
