### ISSUE TITLE
wiki: digitalocean plans

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#135]
Not that you probably want to be keeping a constant check on server pricing and updating your wiki, but I notice that digitalocean's plans have changed in the last couple of days, e.g. their $5 plan now gives 1GB not 512MB.  See [here](https://www.digitalocean.com/pricing/).  The [Getting Started](https://github.com/githubsaturn/captainduckduck/wiki/Getting-Started) page is therefore slightly out of date now... but I couldn't see a way of creating a pull request for a wiki page otherwise I would have offered an edit myself :)

**Comment by githubsaturn** [comment]
Thanks! Fixed.
