### ISSUE TITLE
Problem adding node

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#136]
Starting point:

- single node (digitalocean 1GB server)
- one node app with four instances, https enabled
- monitoring enabled
- one-click postgres app (obviously with persistent data), with port 5432 mapped from container to server

I then try to add a second node (again, digitalocean 1GB server).  I enter all the info in the Nodes page (having enabled self-hosted registry) and click Join Cluster.  I can't remember what, if any, error I got, but the node wasn't added successfully... nothing showing on the Nodes page.

Note: I've successfully set up a cluster before, following the same procedure.  So I'm pretty sure I'm not doing something completely dumb.  The only difference I can see between this time and the last time is that, this time I have a postgres app (obviously with persistent data) already set up on the first node... would that make the difference when trying to add a second node?

Anyway, so I try to add the node again, and I get error:

> Error during setup: Error response from daemon: This node is already part of a swarm. Use "docker swarm leave" to leave this swarm and join another one.

So I do that (on the second node).

Then I try to add the node again.  This time I immediately get the error:

![untitled-1](https://user-images.githubusercontent.com/9009792/35113689-43353a7e-fc7a-11e7-96da-f203961b826c.jpg)

Running `docker info` on the second node gives:

	Containers: 0
	 Running: 0
	 Paused: 0
	 Stopped: 0
	Images: 3
	Server Version: 17.12.0-ce
	Storage Driver: overlay2
	 Backing Filesystem: extfs
	 Supports d_type: true
	 Native Overlay Diff: true
	Logging Driver: json-file
	Cgroup Driver: cgroupfs
	Plugins:
	 Volume: local
	 Network: bridge host macvlan null overlay
	 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
	Swarm: error
	 NodeID: 
	 Error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
	 Is Manager: false
	 Node Address: xxx.yy.zz.215
	Runtimes: runc
	Default Runtime: runc
	Init Binary: docker-init
	containerd version: 89623f28b87a6004d4b785663257362d1658a729
	runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
	init version: 949e6fa
	Security Options:
	 apparmor
	 seccomp
	  Profile: default
	Kernel Version: 4.4.0-109-generic
	Operating System: Ubuntu 16.04.3 LTS
	OSType: linux
	Architecture: x86_64
	CPUs: 1
	Total Memory: 992.3MiB
	Name: testserver-02
	ID: DR4I:GOIE:LDMJ:AFE4:NFJ3:EY7X:44OS:E6VU:RHLC:YQUA:KKYR:BIDZ
	Docker Root Dir: /var/lib/docker
	Debug Mode (client): false
	Debug Mode (server): false
	Registry: https://index.docker.io/v1/
	Labels:
	Experimental: false
	Insecure Registries:
	 127.0.0.0/8
	Live Restore Enabled: false

And on the first node:

	Containers: 11
	 Running: 10
	 Paused: 0
	 Stopped: 1
	Images: 28
	Server Version: 17.12.0-ce
	Storage Driver: overlay2
	 Backing Filesystem: extfs
	 Supports d_type: true
	 Native Overlay Diff: true
	Logging Driver: json-file
	Cgroup Driver: cgroupfs
	Plugins:
	 Volume: local
	 Network: bridge host macvlan null overlay
	 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
	Swarm: active
	 NodeID: t67y24ylysyy4et0yvcoyump0
	 Is Manager: true
	 ClusterID: 4s9oqfhvdqowia1w0lnveklud
	 Managers: 1
	 Nodes: 1
	 Orchestration:
	  Task History Retention Limit: 5
	 Raft:
	  Snapshot Interval: 10000
	  Number of Old Snapshots to Retain: 0
	  Heartbeat Tick: 1
	  Election Tick: 3
	 Dispatcher:
	  Heartbeat Period: 5 seconds
	 CA Configuration:
	  Expiry Duration: 3 months
	  Force Rotate: 0
	 Autolock Managers: false
	 Root Rotation In Progress: false
	 Node Address: 159.65.28.214
	 Manager Addresses:
	  xxx.yy.zz.214:2377
	Runtimes: runc
	Default Runtime: runc
	Init Binary: docker-init
	containerd version: 89623f28b87a6004d4b785663257362d1658a729
	runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
	init version: 949e6fa
	Security Options:
	 apparmor
	 seccomp
	  Profile: default
	Kernel Version: 4.4.0-109-generic
	Operating System: Ubuntu 16.04.3 LTS
	OSType: linux
	Architecture: x86_64
	CPUs: 1
	Total Memory: 992.3MiB
	Name: testserver-01
	ID: ONYK:FEXV:WPLZ:XGIK:E7G2:4CMX:FKT2:JJ6I:SRW3:JURC:6FSI:L3VT
	Docker Root Dir: /var/lib/docker
	Debug Mode (client): false
	Debug Mode (server): false
	Registry: https://index.docker.io/v1/
	Labels:
	Experimental: false
	Insecure Registries:
	 127.0.0.0/8
	Live Restore Enabled: false

EDIT with more info... I went through the whole process again, with another two test server... first and second again as above, with same setup.  This time I took more careful note of what happened when I first clicked on Join Cluster to add the second node... I get the following error in the corner:

![afteraddingnode](https://user-images.githubusercontent.com/9009792/35115096-ecf0668e-fc7e-11e7-9ec6-a19d65a69895.jpg)

The same error flashes up every time I click on any tab in the console.  So, I log out, then back in again.  The auth token error isn't showing anymore, BUT on the Nodes page... still no second node showing.

So I add the details again and hit Join Cluster... this time a few moments pass with waiting icon, and then the same "Timeout" error as above.  With all the info still on the page, I hit Join Cluster again... which leads to the "already part of a swarm" error.  The `docker info` on the second node seems to be same as above, with `DeadlineExceeded` error.

So it seems consistent that I cannot successfully add a node with the first server configured as above.  Any ideas?

**Comment by drmrbrewer** [comment]
I'm now more convinced than ever that you are a genius:

![success](https://user-images.githubusercontent.com/9009792/35117594-ffb00c18-fc86-11e7-9ac8-c6acf6a75fd8.jpg)

... and then `ufw enable` on both nodes?

Is this likely to need to happen in all cases?  I don't recall this before, but maybe I was doing it with vultr servers rather than digitalocean and maybe they're set up differently.

BTW why the "auth token" error after Join Cluster, with need to log out / in again?  Is there any way to avoid that?  It's a bit confusing / disturbing.

**Comment by githubsaturn** [comment]
> ... and then ufw enable on both nodes?


No. By enabling it, you would cut the connection again between the main node the secondary node. If you want to enable it, you can refer to Ports section in wiki to keep the ports that are used by Docker swarm open.

> So maybe ufw is only present and enabled with some server providers?

`ufw` is built in with ubuntu. Some providers might have a modified version of ubuntu that uses another linux based firewall such as `firewall-cmd` and etc.


> BTW why the "auth token" error after Join Cluster, with need to log out / in again? Is there any way to avoid that? It's a bit confusing / disturbing.

This is intentional - it's a security feature where part of the hash salt used for authenticating the token is changed with each restart. This enables the instant disabling of current auth tokens if password changes.

**Comment by drmrbrewer** [comment]
> ufw is built in with ubuntu

OK, well it seems that scaleway use a modified version without `ufw`... no `firewall-cmd` either.

**Comment by drmrbrewer** [comment]
Re the "auth tokens" error that appears after doing Join Cluster... maybe it's an idea to pre-warn the user about this, so that it doesn't come as a surprise/worry, and advising them briefly what to do... just log out and back in again is enough?
