### ISSUE TITLE
Question about domains

### ISSUE THREAD

**Issue by Sparo** [githubsaturn/captainduckduck#138]
Hi, 

great job with capetainduckduck!

I have a question about domains. Followed tutorial about setting things up, and for now all looks fine, but I wanted to know is it possible to control domains. For example:

My root domain (by following this tutorial) is [blah.example.com](blah.example.com), the **captain** is on [captain.blah.example.com](captain.blah.example.com), so I wanted to setup application which is going to have multiple domains (subdomain) layers. 

I would want to have App on [example.com](example.com) (or www.example.com with some redirection to this probably), next I would want App on [blah.example.com](blah.example.com) and finally App on [custom.blah.example.com](custom.blah.example.com), like captain domain level.

This all can be one App, If I could redirect internal (app) routes to specific domains as I mentioned above...  

(like app route is **/example/landing** would go to [www.example.com](www.example.com))
(like app route is **/blah/landing** would go to [blah.example.com](blah.example.com))
(like app route is **/custom/landing** would go to [custom.blah.example.com](custom.blah.example.com))

Is this even possible? :)

**Comment by githubsaturn** [comment]
I am not sure what exactly you're asking. But if you're asking about custom domains and custom routing, it's totally possible. 

1. You have an app called `main-app`, by default, it's accessible at `main-app.blah.example.com`
- You want this app to be accessible from `www.example.com`: You go to apps dashboard and add a custom domain of `www.example.com`
- You want this app to be accessible from `example.com`: Similar to above

2. You also have another app called, `sub-app`. You want users going to `www.example.com/something` be served with this app:
- In this scenario, you go to dashboard and open your `main-app` config page. You click and edit nginx config and add the following block, at the bottom of the nginx config:
```
    location /something {
        rewrite ^/something(.*) /$1 break;
        proxy_pass srv-captain--sub-app;
    }
```

**Comment by drmrbrewer** [comment]
What if you want `main-app` to be available also at `blah-blah.example.com`?  I tried adding another entry to the DNS table with `blah-blah.example.com` pointing to the same IP address as `*.blah.example.com` but it doesn't work.

**Comment by githubsaturn** [comment]
Adding DNS is the first step. Second step is to add blah-blah.example.com as a custom domain to your main-app

**Comment by drmrbrewer** [comment]
Ah so you can add a sub-domain, not just a top level domain.  I was under the impression that you could only assign example.com to the app.

**Comment by drmrbrewer** [comment]
And in the console, where it says "Connect new Domain" (or subdomain), does that *replace* the default myapp.something.mydomain.com, or is it an *additional* mapping?  And will it be *https* if you've enabled that already on the app page?

**Comment by drmrbrewer** [comment]
And I have now found that you can add as many domains (or subdomains) as you like to an app (or at least it didn't complain about three)... works nicely.  Thanks!

**Comment by Sparo** [comment]
Tnx for a clarification !
