### ISSUE TITLE
restore database mysql one-click app?

### ISSUE THREAD

**Issue by sibinphilip** [githubsaturn/captainduckduck#139]
How to restore a mysql database in a one-click app in captainduckduck with captain-definition file?

**Comment by githubsaturn** [comment]
What do you mean by restoring database via `captain-definition` file?  `captain-definition` is the base image for your app. You deploy your app/db via `captain-definition` file and then, you connect to it to do operations such as restoring/importing data.

The easiest way to deploy a PhpMyAdmin one click app, then import connect to your DB and import data. To do so, just google _phpmyadmin import data_
