### ISSUE TITLE
UI issue when enabling self-hosted registry

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#140]
After clicking the `Enable Self Hosted Registry` button, the following error message appears in the console:

![error](https://user-images.githubusercontent.com/9009792/35146407-c81ff85e-fd02-11e7-9222-a080b80c35ab.png)

Furthermore, the `Root Domain` field is now blank and the `Enable Self Hosted Registry` button is still clickable.  

To the user, therefore, it looks like there has been a problem.  They may try to click on the `Enable Self Hosted Registry` button again.

However, if you log out and then straight back in again, in fact all is OK... the `Root Domain` field is now correct and the `Enable Self Hosted Registry` button is now non-clickable.  

Perhaps the feedback to the user can be improved so as not to give the impression that there is a problem?

Similar for the auth token error I describe at the end of [this post](https://github.com/githubsaturn/captainduckduck/issues/136#issue-289726217)... creates the impression that a disaster has occurred when in fact it hasn't.

**Comment by githubsaturn** [comment]
Added some notes 

https://github.com/githubsaturn/captainduckduck/commit/08e5a6ae9785d90c4b3e893b6a73e11915528c43
