### ISSUE TITLE
SSL issue on custom domain

### ISSUE THREAD

**Issue by yunghan** [githubsaturn/captainduckduck#143]
I have setup the captainduckduck installation, and the captain admin page is running on captain.xxx.mydomain.com. I'm encountering some issues when enabling https on custom domains.

I'm setting the custom domain of my app to point to the root domain, mydomain.com, and it works fine. But when I press the "Enable HTTPS" button, the acme-certbot issues an error, and https is not set up correctly.

Enabling https on the default domain, i.e., my-app.xxx.mydomain.com works fine though.

**Comment by githubsaturn** [comment]
Does it only happen with `mydomain.com`? Or you get the same error with any custom domain, such as `www.mydomain.com` as well?

Also, can you please copy the error here?

**Comment by yunghan** [comment]
I tried changing the domain to myname.mydomain.com, and I also get the same error.

This is the output log:

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for mydomain.com
Using the webroot path /captain-webroot/mydomain.com for all unmatched domains.
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. mydomain.com (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://mydomain.com/.well-known/acme-challenge/s0flX0G6zpxlfJzL0S8TXk_bCQ6aU03cIpEbDh3Mx_U: Timeout
[1m
IMPORTANT NOTES:
[0m - The following errors were reported by the server:

   Domain: mydomain.com
   Type:   connection
   Detail: Fetching
   http://mydomain.com/.well-known/acme-challenge/s0flX0G6zpxlfJzL0S8TXk_bCQ6aU03cIpEbDh3Mx_U:
   Timeout

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
">Unexpected output when enabling SSL formydomain.com with ACME Certbot 
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for mydomain.com
Using the webroot path /captain-webroot/mydomain.com for all unmatched domains.
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. mydomain.com (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://mydomain.com/.well-known/acme-challenge/s0flX0G6zpxlfJzL0S8TXk_bCQ6aU03cIpEbDh3Mx_U: Timeout
[1m
IMPORTANT NOTES:
[0m - The following errors were reported by the server:

   Domain: mydomain.com
   Type:   connection
   Detail: Fetching
   http://mydomain.com/.well-known/acme-challenge/s0flX0G6zpxlfJzL0S8TXk_bCQ6aU03cIpEbDh3Mx_U:
   Timeout

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
```

**Comment by githubsaturn** [comment]
Just to confirm, the logs you added shows logs for `mydomain.com` and not `myname.mydomain.com`, right?

Anyways, I just tested this on various test cases and I cannot repo the issue. The logs suggest that there is no LetsEncrypt servers cannot connet to `mydomain.com`. Is your domain publicly accessible. You can verify by using a 3rd party tool like http://www.hurl.it to make sure you can access `http://mydomain.com` and it resolves to "Nothing Here Yet" message from CaptainDuckDuck. Are you able to verify that?

**Comment by yunghan** [comment]
Yeah, the domain was just a typo.

Anyways, I figured out what was wrong with my setup. I combed through various sources and I learned that when both IPv4 and IPv6 address are set up in the DNS records, Letsencrypt will default to IPv6. In my setup, I have set up an A and AAAA record for my `myname.mydomain.com` (IPv4 and IPv6). When I tried accessing the site through IPv6, I was not able to access it. Seems like nginx might not be responding to IPv6 requests correctly.

I deleted my AAAA record and I'm able to generate the cert correctly now. Will have to live without IPv6 for the moment I guess.

**Comment by githubsaturn** [comment]
Glad you sorted it out. 

For IPv6, there are providers that support IPv6. I think DigitalOcean supports it. Give it a shot if IPv6 is important to you.

**Comment by yunghan** [comment]
I’m on Linode, and I see that I’m assigned an IPv6 address. Not sure why it’s not working. I’ll try to have another look sometime later.

But if anyone else on Linode are facing the same issues, this can be the temporary workaround.

**Comment by yunghan** [comment]
Not sure, but my best guess is, it might. From what I understand, Letsencrypt’s algo defaults to using IPv6 address whenever it’s available, so if you enable it, it may fail as it might probably be using the same set of logic.

From what I can gather, the reason is by default, docker is not properly configured for IPv6. I can’t access my containers through v6 correctly using the default configuration.

**Comment by githubsaturn** [comment]
@yunghan is correct. My personal experience with ipv6 on Docker wasn't pleasant. But anyways, once you enable ipv6 with docke things should work. But without that manual change, let's encrypt will fail to re-verify

**Comment by chrisfritsche** [comment]
Hello everybody!
This topic is old but, i have currently a similar issue. I can obtain a certificate for the root domain, but not for any custom domain. 
I'm using CloudFlare, who enable ipv6 as default (don't showing explicit but if you loockup its there). After reading the comments here i disabled it with an API call, but this don't solve the problem, and, it also don't make sense for me because it works for the root domain (that also have ipv4 and ipv6).

- My server is hosted on AWS (EC2 - Ubuntu 18.04, docker 20.10.4).

- There are all my DNS entries: (all type A and public accessible with HTTP)
  - mydomain.com.br
  - www
  - *.captainroot
  - api

- my app "api" successful accepted a letsencrypt certificate for the root domain "https://api.captainroot.mydomain.com.br"

- Custom domain:
  - api.mydomain.com.br (no success to get the certificate and only accessible with HTTP). 

- My error message:
```
Error: Unexpected output when enabling SSL forapi.mydomain.com.br with ACME Certbot 
 Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for api.mydomain.com.br
                      captain-captain.1.siin94qk17m3@ip-172-31-3-202    | Using the webroot path /captain-webroot/api.mydomain.com.br for all unmatched domains.
Waiting for verification...
Challenge failed for domain api.mydomain.com.br
                     captain-captain.1.siin94qk17m3@ip-172-31-3-202    | http-01 challenge for api.mydomain.com.br
                                                                                               captain-captain.1.siin94qk17m3@ip-172-31-3-202    | Cleaning up challenges
Some challenges have failed.
IMPORTANT NOTES:
 - The following errors were reported by the server:
   Domain: api.mydomain.com.br
   Type:   unauthorized
   Detail: Invalid response from
   http://api.mydomain.com.br/.well-known/acme-challenge/hoP00H1eTTuNpINLWFGBH5cmSw8e117emQceHitAp5M
   [2606:4700:3033::ac43:d112]: "<!DOCTYPE html>\n<!--[if lt IE 7]>
   <html class=\"no-js ie6 oldie\" lang=\"en-US\">
   <![endif]-->\n<!--[if IE 7]>    <html class=\"no-js "
   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
                                                      captain-captain.1.siin94qk17m3@ip-172-31-3-202    |    contain(s) the right IP address.
    at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:8:16)
    at /usr/src/app/built/user/system/CertbotManager.js:65:48
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)


```
**NOTE**: the error type is an  **unauthorized**!. Is some CAA flag or something else missing from my side?
I really don't know more what i can do. Any idea?? Thank you very much for any help.

**Comment by jakobwarnhjelm** [comment]
Removing the AAAA-pointers in my DNS panel solved the Letsencrypt 1107 failed acme challenge error precisely as @yunghan described. So i'm adding this comment so others may see that it is still relevant even though it is 2024.
It was on a fresh captain rover install with a single app, the "one-click" redirect app that utilizes nginx.
