### ISSUE TITLE
Mongodb one click app client

### ISSUE THREAD

**Issue by Kimkykie** [githubsaturn/captainduckduck#145]
Hello. I have created a mongodb one click app and I'm trying to connect the database with Mongodb compass so I could check the entries in my database. Is there a way I can go around this?

**Comment by githubsaturn** [comment]
https://github.com/githubsaturn/captainduckduck/wiki/App-Configuration#port-mapping

- Go to Captain dashboard
- Select your MongoDB app
- Go to Port Mapping section and add a port map: `Host: 1234` -> `Container: 27017`
- In your local machine user this schema: `mongodb://dbuser:dbpassword@SERVER_IP_ADDRESS:1234/dbname`

Of course, you should use your own values for `dbuser` `dbpassword` `SERVER_IP_ADDRESS` and `dbname`. Also, you can use any free port instead of `1234`

**Comment by Kimkykie** [comment]
Okay Thank you, this worked really well. I have some issues I would really request for you to clarify to me if possible, Thanks.
1. Netdata engine won't start on my captainduckduck on my leader node. I get the Netdata Succesfully started notification but it resets to Start Netdata Engine after I click okay.
2. My project has images that are stored in a public/uploads folder, I am trying to set a persistent directory so these images won't get deleted once their a restart but I've been unable to.

**Comment by githubsaturn** [comment]
> Netdata engine won't start on my captainduckduck on my leader node. I get the Netdata Succesfully started notification but it resets to Start Netdata Engine after I click okay.

Wait for a few minutes and retry. If it still doesn't work, try after restarting Captain with `docker service update catain-captain --force`

> My project has images that are stored in a public/uploads folder, I am trying to set a persistent directory so these images won't get deleted once their a restart but I've been unable to.

What do you mean by unable to? What was the problem?
- Does it get deleted after restart?
- Does your application stop running if you set the persistent directory?

The persistent directory is NOT A relative path to your application. In case of NodeJS application, your app sits in `/usr/src/app`. Therefore, if there is a folder named `/upload` at the root of your nodejs directory (next to package.json), you should set the "Container Path" for persistent directory as `/usr/src/app/upload`

**Comment by Kimkykie** [comment]
Thanks, I was able to fix the persistent directory issue. I was setting the path to /uploads instead of the /usr/src/app. I need to read more on docker.
On the Netdata issue, I am on version 0.5.4. Issue still persists.

**Comment by githubsaturn** [comment]
If you have a solid repro steps to observe the NetData bug, let me know.

What server provider you use?
