### ISSUE TITLE
How can i browse for the file and directory structure of app

### ISSUE THREAD

**Issue by iamrommel** [githubsaturn/captainduckduck#148]
I want know the path and directory structure of my app after it was deployed on CDD, how can i do that?

Actually i just want to know the my "public" dir (yeah i was looking for this folder named public), so i can use that as default public URL on my express setup.

**Comment by githubsaturn** [comment]
If you're asking the path that your app will be sitting on the server, it varies depending on your dockerfile, for nodejs app, it's located at `/usr/src/app`. For example, your `public` folder is at `/usr/src/app/public`

Having said this, you should NEVER rely on this absolute path. In case of ExpressJS, you should use `__direname+'/public'`.


More info: http://www.fullstacktraining.com/articles/how-to-serve-static-files-with-express
