### ISSUE TITLE
NetData email notifications

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#149]
In the Captain console I have entered all the relevant information into the Email (SMTP) section and clicked Update NetData.  But still I don't get any email notifications... the server is behaving generally quite well but in the NetData dashboard itself, I do get the occasional warning alert pop up, with an entry in the NetData log, but no email is sent.

Do I need to configure anything else on the server to make this work?  Even if the issue is not specifically relating to Captain, if an extra step is required then it should either be done when enabling this feature or a note about it should be on the NetData page of the Captain console.

Again, thanks so much for such a wonderful tool, and the time and effort you've put into this!

**Comment by githubsaturn** [comment]
No particular configuration is needed. CaptainDuckDuck uses https://github.com/titpetric/netdata dockerized version of NetData. If you're seeing an issue, please raise an issue with the respected project on GitHub. Make sure to include output of the following command as it shows the environmental variables that are required for email notifications to work - this will help the project maintainer to track down the issue.

```
docker container inspect captain-netdata-container
```
