### ISSUE TITLE
View build log (git build)

### ISSUE THREAD

**Issue by vincelwt** [githubsaturn/captainduckduck#150]
Hello,
My app's build (from a git repo) is failing due to some npm dependency and I'm struggling to fix it.

The command
`sudo docker service logs captain-captain --since 10m --follow`
is helpful but only gives which command failed and not the full log.

Is there a way to view the full log for git builds ? If not that would be a nice addition.

Thanks

**Comment by vincelwt** [comment]
I've ended up using `captainduckduck deploy` to have the full logs but would be great to be able to see the logs for the other deploy methods!

**Comment by githubsaturn** [comment]
Correct. It is mentioned in the docs that CLI in the only method which shows the build logs. 
https://github.com/githubsaturn/captainduckduck/wiki/Deployment-Methods#deploy-via-cli

**Comment by vincelwt** [comment]
Would it be hard to implement for other deploy methods?

**Comment by githubsaturn** [comment]
Architecturally speaking, no, it's not too difficult. 

When I ran a quick survey back when I was implementing the feature, it turned out that CLI deploy is where people are more interested in viewing the logs. 

If things go well, I'll add build logs to the web dashboard in the next release.

**Comment by vincelwt** [comment]
I see. Thanks for the awesome project!
