### ISSUE TITLE
Enhancement: View Build Logs on Web

### ISSUE THREAD

**Issue by githubsaturn** [githubsaturn/captainduckduck#153]
Having the ability to view build logs on web dashboard is useful, particularly when deployment is done through webhooks.

**Comment by iamrommel** [comment]
Not only the build logs, but even application logs.  Sometimes if i do the console.log on the nodejs codes, i want to view it also. Basically what the 
`docker service logs srv-captain--my-app --since 60m --follow`
output is, should be good i guess

**Comment by githubsaturn** [comment]
Application logs go through docker log driver.

**Comment by iamrommel** [comment]
But can it shown on the web dashboard?

**Comment by githubsaturn** [comment]
Theoretically yes - but it's very complicated. Application log aggregation on itself is a very complicated service. Just google "Docker Log Aggregator" and you'll see a bunch of them.

To put it in a nutshell: if such a thing ever comes to CaptainDuckDuck, it'll be a one-click app and won't be part of the core - because of its complexity.

**Comment by githubsaturn** [comment]
Added in https://github.com/githubsaturn/captainduckduck/commit/07bf695395b2f14812365f3b3a3a91af54263132

Will be released in the next version
