### ISSUE TITLE
captain-nginx error

### ISSUE THREAD

**Issue by lohazo** [githubsaturn/captainduckduck#154]
All my web on server is down i try to do something but not success
I was try to run this command: 
`docker service logs captain-nginx --since 60m --follow`

This is the message:
`captain-nginx.1.uai4ie4peedh@captainduckduck    | 2018/01/30 07:36:12 [emerg] 1#1: unknown "0" variable
captain-nginx.1.uai4ie4peedh@captainduckduck    | nginx: [emerg] unknown "0" variable`

And `docker service ls`

`mcs5jlbwwnh6        captain-captain                   replicated          1/1                 dockersaturn/captainduckduck:0.5.4      *:3000->3000/tcp
m5v3auorakk6        captain-certbot                   replicated          1/1                 dockersaturn/certbot-sleeping:v0.17.0
x78g5szit332        captain-nginx                     replicated          0/1                 nginx                                   *:80->80/tcp,*:443->443/tcp`

everything running accept captain-nginx

**Comment by githubsaturn** [comment]
Did you modify nginx config to some arbitrary configuration? If so, see:
https://serverfault.com/questions/629158/nginx-emerg-unknown-0-variable
https://stackoverflow.com/questions/25888204/nginx-emerg-unknown-0-variable

**Comment by lohazo** [comment]
Yes. I made a change to nginx
What i should do to fix the configuration file

**Comment by githubsaturn** [comment]
Modifying Nginx Configuration is an advanced task. Make sure you understand it before making these sort of changes. To fix you have to do the following:

- run `docker service scale captain-captain=0`
- create a backup of the configuration file by running `cp /captain/config.conf /captain/config.bak`
- run `nano /captain/config.conf`
- Remove all custom nginx configurations that you see in this json. Remove both KEY and the VALUE.
- Exit nano and save the config file.
- To double check, run `cat /captain/config.conf` and make sure that your content is valid. If it's an invalid json, it will get wiped once captain starts up. So make sure commas are removed when you remove keys and values related to custom captain config.
- Finally, start the captain by running `docker service scale captain-captain=1`

**Comment by lohazo** [comment]
Awesome! Captain is work fine now.
Thanks

**Comment by drmrbrewer** [comment]
@githubsaturn is the `captain-captain` service just there to provide the Captain console?  Scaling the service to `0` is to prevent any attempted access from the Captain console to the config file concerned, while manual changes are taking place?

**Comment by githubsaturn** [comment]
Yes.

**Comment by lohazo** [comment]
Oh one more thing @githubsaturn I updated to 0.5.4  but my monitoring still not work

**Comment by githubsaturn** [comment]
What VPS provider you're using?

**Comment by lohazo** [comment]
I use vultr centos 7 (ubuntu is same)
Yes it going to loading state and then nothing happen only one button

**Comment by githubsaturn** [comment]
Just tried on both Centos and Ubuntu instances of Vultr, I am getting monitoring tool to show up on the first try. This is really bizarre.
