### ISSUE TITLE
Postgres db not found

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#156]
I'm suddenly getting the following error in my app logs

    Error: getaddrinfo ENOTFOUND srv-captain--mydb  srv-captain--mydb:5432

I've tried restarting everything (save in app page of Captain console), but no joy.

I haven't changed anything from what was previously working.

Any hints about what to try?

**Comment by githubsaturn** [comment]
What is the steps to repro? How did you get to this state?

Try `docker service update captain-captain --force` - it may solve the issue.

**Comment by drmrbrewer** [comment]
I have no idea what happened.  Everything was running smoothly and the next minute the pg database was not responsive.  The following info suggests that the pg image has disappeared:

	# docker service ps srv-captain--mypostgresdb
	ID                  NAME                            IMAGE                       NODE                DESIRED STATE       CURRENT STATE           ERROR                              PORTS
	433q5l7vqnlv        srv-captain--mypostgresdb.1       img-captain--mypostgresdb:1   pluto-01            Ready               Rejected 1 second ago   "No such image: img-captain--m…"   
	zyxqx5ap7ac6         \_ srv-captain--mypostgresdb.1   img-captain--mypostgresdb:1   pluto-01            Shutdown            Rejected 2 hours ago    "No such image: img-captain--m…"   
	zythg56dcc4d         \_ srv-captain--mypostgresdb.1   img-captain--mypostgresdb:1   pluto-01            Shutdown            Rejected 3 hours ago    "No such image: img-captain--m…"   
	zyia1476hwiz         \_ srv-captain--mypostgresdb.1   img-captain--mypostgresdb:1   pluto-01            Shutdown            Rejected 3 hours ago    "No such image: img-captain--m…"   
	zyt4lt8nt469         \_ srv-captain--mypostgresdb.1   img-captain--mypostgresdb:1   pluto-01            Shutdown            Shutdown 4 hours ago    

Unlike other 'apps' it's not possible to deploy it again to create a fresh one.  As mentioned, I did try to "restart" it from the Captain console.

It's not critical... I just spun up a new server and added everything back, but I'm curious to know whether it's possible to recover the failed setup via Captain.

I'm happy if you close this as being not-captain-related but it would be interesting to hear your thoughts.

**Comment by githubsaturn** [comment]
Is it possible that you cleaned up your images when this service was not running? Removing an image would cause the service to stop.

To fix, you don't need to spin up a new server. Just run the following command:
```
docker service update --image postgres:latest srv-captain--mypostgresdb 
```

**Comment by drmrbrewer** [comment]
Before trying what you suggest above, I did:

	$ docker service ls
	ID                  NAME                        MODE                REPLICAS            IMAGE                                                                    PORTS
	clejvaxqlagd        srv-captain--myapp          replicated          0/2                 registry.pluto.cloud3squared.com:996/captain/img-captain--myapp:24   
	p0gcnrndqa4y        srv-captain--mypostgresdb   replicated          0/1                 img-captain--mypostgresdb:1                                                *:5432->5432/tcp,*:5432->5432/udp

So the postgres db and my app were both on `replicas: 0/n`.

Then I did you suggestion:

    $ docker service update --image postgres:latest srv-captain--mypostgresdb

Sure enough, this fixes the `srv-captain--mypostgresdb` line:

	p0gcnrndqa4y        srv-captain--mypostgresdb   replicated          1/1                 postgres:latest                                                          *:5432->5432/tcp,*:5432->5432/udp

For my app, I tried just doing `Save and Update Configuration` (without changes... instances still set at 2) but this didn't help.  But a full `captainduckduck deploy` did the trick, and all services are now back to normal, and the server seems to be behaving well.

I'm still using the replacement server I span up, but it's really useful to know how to react the next time this occurs... still have no idea what happened... I wasn't changing anything at the time (I was away from any tech completely)... and I haven't done a disk cleanup for several days now.

**Comment by githubsaturn** [comment]
`Save and Update Configuration` restarts the app but does not recreate the image. To recreate the image, you'll have to re-deploy - which you did and it worked 👍 

I personally haven't seen the issue you mentioned, i.e., Docker self destroying in-use images. I am not sure what caused it, if it's a Docker bug, or if it was a human error. The only thing that I can tell you with certainty is that Captain does not prune images behind the scene. It only prunes stopped containers.

**Comment by drmrbrewer** [comment]
No, it's a mystery why it happens.  Anyway, I've learned a little more in fixing it.  Thanks.

**Comment by negati-ve** [comment]
This is a common scenario I face on servers with less than 6GB of ram.

When I run a big enough build for the server to run out of ram, usually the servers crashes and restarts and all the instances restart too. 

BUT one click deploy apps do not recover similar to how postgres instance did not recover for @drmrbrewer in above comments

above solution works too!
