### ISSUE TITLE
Set up cron job in postgres container

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#158]
I'd like to set up a cron job in my postgres container, to schedule a regular backup that uploads a pg_dump file to a remote host.  My current thinking is that I would just shell into the postgres container, once it is created by Captain via a one-click app, and set up the cron job manually.  However, this is of course another thing to remember to do when setting up a new server with all the various components in place.  So, is there a way in which Captain can make this easier / more automated?  I suppose this is something that would normally be included in the dockerfile (or captain-definition file) that is used to deploy an app using Captain, but with the one-click apps there is no dockerfile (or captain-definition) to use for this purpose.

**Comment by githubsaturn** [comment]
Correct. You do need a customized Dockerfile (using a captain-definition). 

You can re-deploy a postgres using a custom image. Simply go through the steps for one click apps and deploy your regular postgres app. Now create a custom captain-definition file, archive it as `.tar` file and upload it on the dashboard as your postgres app. 

Alternatively, you can even do this without one click app. Simply create an app with persistent data and set the persistent directories and also environmental variables needed for postgres container. Then upload the custom captain-definition file. 

For more information regarding adding a cron job to your dockerfile, see this:
https://stackoverflow.com/questions/37458287/how-to-run-a-cron-job-inside-a-docker-container
