### ISSUE TITLE
Is there a way to restore or make a new password?

### ISSUE THREAD

**Issue by Firro49** [githubsaturn/captainduckduck#159]
Ok this may be a bit stupid but ehm, I accidentally typed in a password with a password manager and overwrote my clipboard LOL. That's stupid, I know. Is there a way to access it again though? I can still ssh into my machine and I have the hashed password ._. 
Help would be appreciated

**Comment by githubsaturn** [comment]
I haven't tried this, but it may work:
- SSH to server
- run `docker service scale captain-captain=0`
- run `nano /captain/config.conf` and remove the hashed password, both key and value
- run `docker service scale captain-captain=1`
- Now try to login with `captain42` as password

**Comment by Firro49** [comment]
Yikes, that worked. Thanks a lot!

**Comment by mbariola** [comment]
By the way, I tried that too, to see if I could revert another config change ... and I saw that in /captain there is a `letencrypt` folder. It's a minor typo, but maybe it would be good to change it to `letsencrypt`?

**Comment by githubsaturn** [comment]
Unfortunately, that typo fix won't be backward compatible. That typo is here to stay until a breaking major change... Sorry :-(

**Comment by mbariola** [comment]
It's ok, not a big thing!

**Comment by comontes** [comment]
thanks @githubsaturn for your reply, I didn't make any changes to the DNS. The output for your command goes as follows:

`root@docker-s-1vcpu-1gb-sfo2-01:~# docker exec -it $(docker ps --filter name=captain-certbot -q) /bin/sh -c 'certbot certificates --non-interactive; certbot renew --non-interactive'
Saving debug log to /var/log/letsencrypt/letsencrypt.log
openssl not installed, can't check revocation

Found the following certs:
  Certificate Name: vfp-bot.duck.mydomain.com
    Domains: vfp-bot.duck.mydomain.com
    Expiry Date: 2019-02-23 03:27:49+00:00 (VALID: 50 days)
    Certificate Path: /etc/letsencrypt/live/vfp-bot.duck.mydomain.com/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/vfp-bot.duck.mydomain.com/privkey.pem
  Certificate Name: registry.duck.mydomain.com
    Domains: registry.duck.mydomain.com
    Expiry Date: 2019-02-19 18:15:49+00:00 (VALID: 46 days)
    Certificate Path: /etc/letsencrypt/live/registry.duck.mydomain.com/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/registry.duck.mydomain.com/privkey.pem
  Certificate Name: captain.duck.mydomain.com
    Domains: captain.duck.mydomain.com
    Expiry Date: 2019-02-19 18:15:56+00:00 (VALID: 46 days)
    Certificate Path: /etc/letsencrypt/live/captain.duck.mydomain.com/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/captain.duck.mydomain.com/privkey.pem
  Certificate Name: vfp.duck.mydomain.com
    Domains: vfp.duck.mydomain.com
    Expiry Date: 2019-02-19 18:16:03+00:00 (VALID: 46 days)
    Certificate Path: /etc/letsencrypt/live/vfp.duck.mydomain.com/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/vfp.duck.mydomain.com/privkey.pem

Saving debug log to /var/log/letsencrypt/letsencrypt.log

Processing /etc/letsencrypt/renewal/vfp-bot.duck.mydomain.com.conf
Cert not yet due for renewal

Processing /etc/letsencrypt/renewal/registry.duck.mydomain.com.conf
Cert not yet due for renewal

Processing /etc/letsencrypt/renewal/captain.duck.mydomain.com.conf
Cert not yet due for renewal

Processing /etc/letsencrypt/renewal/vfp.duck.mydomain.com.conf
Cert not yet due for renewal

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/vfp-bot.duck.mydomain.com/fullchain.pem (skipped)
  /etc/letsencrypt/live/registry.duck.mydomain.com/fullchain.pem (skipped)
  /etc/letsencrypt/live/captain.duck.mydomain.com/fullchain.pem (skipped)
  /etc/letsencrypt/live/vfp.duck.mydomain.com/fullchain.pem (skipped)
No renewals were attempted.`

**Comment by githubsaturn** [comment]
```
docker service update captain-registry --force
```

**Comment by gustavol3v** [comment]
> I haven't tried this, but it may work:
> 
> * SSH to server
> * run `docker service scale captain-captain=0`
> * run `nano /captain/config.conf` and remove the hashed password, both key and value
> * run `docker service scale captain-captain=1`
> * Now try to login with `captain42` as password

There is no `config.conf` in my /captain folder. Did it changed?

**Comment by gustavol3v** [comment]
Ok sorry, for me it was in `/captain/data/config-captain.json`. The procedure still works thought 👊🏻

**Comment by githubsaturn** [comment]
Yes, it's moved in CapRover refactoring. I've updated the original post.

**Comment by ivalsaraj** [comment]
> I haven't tried this, but it may work:
> 
> * SSH to server
> * run `docker service scale captain-captain=0`
> * run `nano /captain/data/config-captain.json` (`nano /captain/config.conf` if you use older CaptainDuckDuck) and remove the hashed password, both key and value
> * run `docker service scale captain-captain=1`
> * Now try to login with `captain42` as password

This didn't work for me and didn't find the password key in the config.

But this worked for me like a charm: https://caprover.com/docs/troubleshooting.html#reset-password

`docker service scale captain-captain=0`

# backup config
`cp /captain/data/config-captain.json /captain/data/config-captain.json.backup`

# delete old password
`jq 'del(.hashedPassword)' /captain/data/config-captain.json > /captain/data/config-captain.json.new
cat /captain/data/config-captain.json.new > /captain/data/config-captain.json
rm /captain/data/config-captain.json.new`

# set a temporary password
`docker service update --env-add DEFAULT_PASSWORD=mytemppassword captain-captain`
`docker service scale captain-captain=1`

**Comment by coffseducation** [comment]
> It looks like your certs are valid. Perhaps try restarting your registry container and this should resolve the issue:
> 
> ```
> docker service update captain-registry --force
> ```

There is (no longer) a captain-registry. Is there an alternative?
What about 'docker service update captain-certbot --force'?

**Comment by githubsaturn** [comment]
@coffseducation  - this thread talks about two separate issues. Password change and the other one is for registry certs. What's the issue you're having?

**Comment by coffseducation** [comment]
> @coffseducation - this thread talks about two separate issues. Password change and the other one is for registry certs. What's the issue you're having?

Hi! I could not connect a new domain name. After a reboot it is now working. Thanks for the reply.
