### ISSUE TITLE
Failed to add node

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#161]
I added a new node in the nodes page, and an error message popped up... can't recall what it said because it disappeared too quick.  I tried the same adding another node, with same result.  Anyway, the problem was `ufw`, which I disabled on the nodes concerned.  The third node has now appeared in the cluster, but the second node hasn't.  When I try to add the second node again on Captain, it complains as follows:

![untitled-1](https://user-images.githubusercontent.com/9009792/35742580-ca1b2026-0832-11e8-82e9-8aa8826cb259.jpg)

But on the main node now I still see:

    # docker node ls
    ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
    lckkmuz290r12kou2zrlp9hj8 *   test-01             Ready               Active              Leader
    100teo5y4viyzvi2cgykxilql     test-03             Ready               Active              

i.e. `test-02` node still hasn't appeared, and I cannot add it via Captain.  Of course, it's not a major issue because I can spin up a `test-04` node and add that instead, but it bothers me a bit to leave it in this state, and I wonder how to recover from this sitation.  

I checked again, and on `test-02` I see:

    root@test-02:~# ufw status
    WARN: / is group writable!
    Status: inactive

**Comment by githubsaturn** [comment]
I am not sure what could have caused this inconsistency. But anyways, you can forcefully make test-02 to leave the swarm. SSH to test-02 and run `docker swarm leave --force`.

**Comment by drmrbrewer** [comment]
That worked to enable test-02 to be added again.  However, after adding it, and shutting down test-04, I was getting strange nginx 502 errors when accessing the main app.  I restarted/redeployed everything I could, and nginx error now gone on main app, but I've been getting ENOTFOUND log errors when trying to connect internally from my app container (node app) to another container via http://srv... ... was working fine before.

Never mind, I'll give this server setup up as a bad job and start again with a new group of servers.
