### ISSUE TITLE
Server Clustering with Captain

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#162]
I've read the [wiki](https://github.com/githubsaturn/captainduckduck/wiki/Server-Clustering-and-App-Scaling), and the various linked pages about docker swarm.  I still do not quite understand the interaction between Captain and Docker when creating and maintaining the swarm, however.

It seems that in Captain you can create more than one manager node, i.e. corresponding to the [docker swarm architecture](https://docs.docker.com/engine/swarm/how-swarm-mode-works/nodes/).  Having more than one manager is supposed to [improve resiliency](https://docs.docker.com/engine/swarm/how-swarm-mode-works/nodes/#manager-nodes) against loss of a manager node.

However, as I understand it, when you set up the swarm via Captain, there is still a single entry point to the cluster, i.e. the main (captain) node.  The app that you deploy (with multiple instances across the various nodes) is still only available via the single entry point, e.g. https://myapp.myproject.mydomain.com.  I assume that nginx is installed on that node, and is responsible for routing requests as appropriate to other nodes.

But doesn't this mean that, no matter how many manager or worker nodes you set up via Captain, if the main node goes down then you've basically lost the whole lot, because the main node is the only point of entry?

Would be great to know a bit more about setting up a resilient swarm using Captain.

**Comment by githubsaturn** [comment]
Your understanding is correct. More details:

>  Having more than one manager is supposed to improve resiliency against loss of a manager node.

This is true only for a system with no container that has persistent data. This includes databases, and even a simple nginx container, which might look a non-persistent app, but indeed it has a configuration file that dictates how requests should be mapped and even SSL keys. 

On top of this, another problem is the DNS entries. Generally speakings, for consumer level DNS provider, you only get to assign a single IP address to your domain. That means that IP needs to be mapped to a single machine which is the single point of failure for your service. A solution for this is a round-robin based DNS, which typically requires a custom DNS server.

Having said that, creating a really distributed system is totally doable via Docker - but it requires some customizations that cannot be open-sourced - things like a remote storage driver that can host `/captain` directory. There open source projects, but they require access to amazon S3 or so, look at: https://rexray.thecodeteam.com/

In theory, if you share `/captain` directory between your manager nodes, and you have a customized DNS server, if your main node goes down. You can move Captain to the second node and it'll work. But this is not an easy task - only big companies do these kinds of stuff.

**Comment by drmrbrewer** [comment]
If we assume for now that we have no requirement for a database with persistent data, the following article seems to suggest that a service running in the swarm can be made accessible via the IP address of *any* node in the swarm, not just a single entry point:

https://sysally.com/blog/howto-high-availability-docker-swarm/

How does the swarm architecture implemented by Captain differ from the above?

**Comment by githubsaturn** [comment]
It is not different. You can set your DNS IP address to point to any of your Captain cluster and things still work as expected. 

The problem is that all your SSL keys and configuration files sit on the main node - hence they will be unavailable once your main node goes down.

**Comment by drmrbrewer** [comment]
OK that's interesting, thanks.  I hadn't appreciated that the custom domain you add to an app in Captain can be associated with the IP address of any of of the nodes of the cluster.  I just tried this, and sure enough -- once a custom domain with the second node's IP address is added to the app -- the app is available via the second node.  And, when I powered down the main node, the app was no longer working (whether via the main node or the second node), and only returned once the main node was powered up again.  So having multiple nodes helps with resiliency so far as worker nodes  are concerned (if you lose one or more of those then the others will take up the slack) but if you lose your main node then you're pretty much stuck... switching over to a new or backup server is the only option.  Hopefully my comments are not too far from the truth ;)

**Comment by voarsh2** [comment]
This is kind of a biggie issue for me.

I already am not considering using MySQL/MariaDB inside Caprover because, well, clustering is not easy. Better to run outside with replication and failover application level.

This issue was raised some time ago, and I ask again if there's any way of failover for captain itself?
Load balancer in-between two manager nodes? Clone the file system at intervals?

**Comment by githubsaturn** [comment]
That's correct. Persistent data resiliency is beyond CapRover's current scope. It requires a huge amount of work on integrating with a storage cluster like Ceph or Gluster.

**Comment by voarsh2** [comment]
> That's correct. Persistent data resiliency is beyond CapRover's current scope. It requires a huge amount of work on integrating with a storage cluster like Ceph or Gluster.

Yes, I see.
But is cloning Caprover itself and deploying it on another machine (which I would probably automate) and "switch" a load balancer a go to approach instead?

**Comment by githubsaturn** [comment]
Cloning server may not work depending how you clone it. CapRover encrypts the data using Docker swarm key. If you start a new swarm, your key may be different. 

The only way that works is to take a [backup of your CapRover](https://caprover.com/docs/backup-and-restore.html#backup--restore). I use a script like this for periodic downloads of the backup file.

```
create_caprover_backup() {

    API_TOKEN=$(curl $CAPROVER_URL/api/v2/login \
        -H 'x-namespace: captain' \
        -H 'content-type: application/json;charset=UTF-8' \
        --data-raw "{\"password\":\"$CAPROVER_PASSWORD\"}" \
        --compressed --silent | jq -r ".data.token")

    DOWNLOAD_TOKEN=$(curl $CAPROVER_URL/api/v2/user/system/createbackup \
        -H "x-captain-auth: $API_TOKEN" \
        -H 'x-namespace: captain' \
        --data-raw '{"postDownloadFileName":"backup.tar"}' \
        --compressed --silent | jq -r ".data.downloadToken")

    if [ ${#DOWNLOAD_TOKEN} -le 10 ]; then
        echo "DOWNLOAD_TOKEN must be at least 10 char long"
        exit 1
    fi

    wget "$CAPROVER_URL/api/v2/downloads/?namespace=captain&downloadToken=$DOWNLOAD_TOKEN" -O backup.tar

    mv backup.tar $backup_directory_base/

}
```

**Comment by voarsh2** [comment]
Thanks.
I'll likely be running a VM, so it's be a full system clone.
But that script may help those on bare metal.

**Comment by PaulKlumpp** [comment]
Wouldn't it be a good match to integrate Docker Volume Driver to share state between Swarm nodes into captain?
https://docs.docker.com/engine/extend/legacy_plugins/#volume-plugins

Depending on persistence type, it might be a paid option. Still, I can't imagine it being expensive as there's not much space needed.
