### ISSUE TITLE
Adding new node: Captain IP Address (as seen by remote)

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#163]
It's always struck me that, when adding a new node on the Nodes page of Captain, the "Captain IP Address" field seems to be somewhat redundant... surely this information is already known to Captain?  To me it potentially just confuses the user, because all they are trying to do is add a new node to the cluster, and therefore they would expect only to have to supply the IP address of the new node, not any of the existing nodes.  Why is Captain's IP address required again?

**Comment by githubsaturn** [comment]
Captain IP address is "usually" the public IP address of the main node. But it's not always true. You can have a worker node sitting on a private network (192.168.0.0/24 for example), then the Captain IP address as seen by the new node is NOT public IP address of the Captain, but it is 192.168.0.1 for example.
