### ISSUE TITLE
API sending 302 redirect when using Postman

### ISSUE THREAD

**Issue by dkimot** [githubsaturn/captainduckduck#167]
I'm building a service that uses the CDD API to launch static web server containers. In testing, I was sending a POST request with Postman (OSX) to the /api/v1/login route and getting a Not Found error.

I was puzzled because this is the same endpoint documented in the code as working. I checked the server logs and found out that CDD was sending a 302 status code back to Postman which apparently then tried a GET request resulting in the Not Found error I saw.

I tried the same request from Curl and got a token back successfully. After checking the server logs it appears that CDD only sent the 302 status back to Postman. Any idea why this would happen?

**Comment by tuefekci** [comment]
I have an somewhat close error and i think it is related to force https check if you get redirected from http to https.

**Comment by githubsaturn** [comment]
@tuefekci is correct. This is due to HTTPS redirection. Try postman with HTTPS schema
