### ISSUE TITLE
Connection Refused - Cannot connect after server reboot

### ISSUE THREAD

**Issue by mbariola** [githubsaturn/captainduckduck#169]
What is the problem?

Connection Refused both via browser and CLI after server reboot (was taking a snapshot ...)

If applicable, content of `captain-definition` file:

Steps to reproduce the problem:

Install CDD server and client on DigitalOcean Droplet following instructions
captainduckduck serversetup , set up captain incl. https and changing password
create wordpress app from web
stop server via CLI with init 0, execute snapshot (was doing this to make sure to be able to revert after trying again to change captain conf, see #168 )
restart Droplet, try to connect either via console or web
Connection Refused

Answers to the following questions where applicable:
- Your OS and version?
Linux Ubuntu 16.04, fully updated
- RAM?
2 GB

**Comment by githubsaturn** [comment]
Post restart, please run the following command and copy the output here:

```
docker service ls
```

**Comment by mbariola** [comment]
# docker service ls
ID                  NAME                                 MODE                REPLICAS            IMAGE                                   PORTS
gh7zzrazni7q        captain-captain                      replicated          1/1                 dockersaturn/captainduckduck:0.5.4      *:3000->3000/tcp
knqljjvjplzk        captain-certbot                      replicated          1/1                 dockersaturn/certbot-sleeping:v0.17.0
6tv0dug2xpi9        captain-nginx                        replicated          0/1                 nginx                                   *:80->80/tcp,*:443->443/tcp
boah87w12305        srv-captain--hillsdalecircle         replicated          1/1                 img-captain--hillsdalecircle:1
63afosvhcckx        srv-captain--hillsdalecircle-mysql   replicated          1/1                 img-captain--hillsdalecircle-mysql:1

**Comment by mbariola** [comment]
`# docker service ls
ID                  NAME                                 MODE                REPLICAS            IMAGE                                   PORTS
gh7zzrazni7q        captain-captain                      replicated          1/1                 dockersaturn/captainduckduck:0.5.4      *:3000->3000/tcp
knqljjvjplzk        captain-certbot                      replicated          1/1                 dockersaturn/certbot-sleeping:v0.17.0
6tv0dug2xpi9        captain-nginx                        replicated          0/1                 nginx                                   *:80->80/tcp,*:443->443/tcp
boah87w12305        srv-captain--hillsdalecircle         replicated          1/1                 img-captain--hillsdalecircle:1
63afosvhcckx        srv-captain--hillsdalecircle-mysql   replicated          1/1                 img-captain--hillsdalecircle-mysql:1
`

**Comment by githubsaturn** [comment]
Thanks. I'll try to repro this on a DigitalOcean instance tonight. The output suggests all containers booted up except the nginx container.  Next step would be to look into the details of nginx logs, try running this:

```
docker service ps captain-captain --no-trunc
```

**Comment by mbariola** [comment]
`~# docker service ps captain-nginx --no-trunc
ID                          NAME                  IMAGE               NODE                DESIRED STATE       CURRENT STATE                      ERROR                       PORTS
ruasnotizbit0h0e89ri9vqq4   captain-nginx.1       nginx               Khariton-DO         Ready               Preparing less than a second ago                          
9sr2p9n8lxu8dkxkzrrr2hwb6    \_ captain-nginx.1   nginx               Khariton-DO         Shutdown            Failed less than a second ago      "task: non-zero exit (1)"
zwqcq5mat92v8uebal8xi6w91    \_ captain-nginx.1   nginx               Khariton-DO         Shutdown            Failed 8 minutes ago               "task: non-zero exit (1)"
zrtz9jhtyjv9muofeoeuaaab2    \_ captain-nginx.1   nginx               Khariton-DO         Shutdown            Failed 28 minutes ago              "task: non-zero exit (1)"
zt1jcd2lau2a7fzfucm9le449    \_ captain-nginx.1   nginx               Khariton-DO         Shutdown            Failed about an hour ago           "task: non-zero exit (1)"
zydb1oyuuum4u2rdudvowe9zt    \_ captain-nginx.1   nginx               Khariton-DO         Shutdown            Failed about an hour ago           "task: non-zero exit (1)"
`

**Comment by githubsaturn** [comment]
We're getting there... Hopefully, this one gives us better indication of what's happening:

```
docker service update --force --detach captain-captain
docker service logs captain-nginx --since 60m --follow
```

Hopefully, it'll show the root cause here.

**Comment by mbariola** [comment]
`
# docker service update --force --detach captain-captain
captain-captain

# docker service logs captain-nginx --since 60m --follow
captain-nginx.1.rv59tsus9a56@Khariton-DO    | 2018/02/07 19:29:32 [emerg] 1#1: could not build server_names_hash, you should increase server_names_hash_bucket_size: 64
captain-nginx.1.rv59tsus9a56@Khariton-DO    | nginx: [emerg] could not build server_names_hash, you should increase server_names_hash_bucket_size: 64
captain-nginx.1.7moi9kygaies@Khariton-DO    | 2018/02/07 19:29:51 [emerg] 1#1: could not build server_names_hash, you should increase server_names_hash_bucket_size: 64
captain-nginx.1.7moi9kygaies@Khariton-DO    | nginx: [emerg] could not build server_names_hash, you should increase server_names_hash_bucket_size: 64


`

**Comment by githubsaturn** [comment]
`server_names_hash` error is thrown if your domain name is really long. 

It's also confusing why it works before restart. If `server_names_hash` is really the problem, it should never work. Anyways, I'll try to repro tonight on Digital Ocean and will update here. 

How long is your longest domain? How many characters is in `your-app-name.root-captain.your-domain.com`?

**Comment by mbariola** [comment]
hillsdalecircle.labs.massimilianobariola.consulting. Yes, I regret having taken that domain name :-)

**Comment by mbariola** [comment]
51 characters. Yes, I regret having taken that domain name :-)

**Comment by mbariola** [comment]
sorry, more than that, I had forgotten that the wordpress app also has the mysql container. So it'd be 58.

**Comment by githubsaturn** [comment]
Fixed, see: https://github.com/githubsaturn/captainduckduck/issues/168#issuecomment-364003368
