### ISSUE TITLE
Captain and CLI on same server?

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#171]
Is it possible to have the Captain CLI installed on the same server as the Captain machine?  With this, you could deploy an app to the same server as the one you're deploying from.  I did try it, and it failed, but I didn't persist because there's probably a reason why this just isn't possible.  Background is: I'd like to deploy a large third-party repo to an app on a dedicate server, but don't want that repo taking up space on my own IDE (limited space).  I could spin up a "deployment server" with the CLI and repo on that, and deploy from there to the production server, but this is an additional server (or having to create one temporarily just to get the app deployed to the production server).

**Comment by githubsaturn** [comment]
Yes. This is what I do for development purposes.
