### ISSUE TITLE
httpd container not successfully starting after deploy

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#172]
I'm trying to deploy [this repo](https://github.com/drmrbrewer/astro-api).  In theory it should create an apache server to serve requests for astro info.  The above is just a fork from a [third-party repo](https://github.com/FrankThomasTveter/astro-api), and all I've done in my fork is to add a `captain-definition` file, based on the Dockerfile already in the repo.

However, on deploying this (I needed to change `client_max_body_size` as described [here](https://github.com/githubsaturn/captainduckduck/issues/168#issuecomment-363837518)) I find that a `docker ps -a` on the remote server shows a container continually being started and then apparently stopped and replaced by a new one.

Any idea what I'm doing wrong?

**Comment by githubsaturn** [comment]
If your container getting renewed it means it keeps dying. It can be a misconfiguration in your app, missing data, or even not enough memory. Try to get some logs using
```
docker service logs srv-captain--your-app-name --follow
```
as mentioned [here](https://github.com/githubsaturn/captainduckduck/wiki/Troubleshooting#how-to-view-my-applications-log).


Also, from personal experience: a ton of 3rd party random Dockerfiles that you find on the internet are not maintained properly. Try to use a well documented and supported dockerfile.

**Comment by drmrbrewer** [comment]
There is nothing in the logs at all for the service.  And I'm not even sure that the containers are dying... the following suggests that multiple ones are being created (all have status `CREATED`)?

    $ docker ps -a

	CONTAINER ID        IMAGE                                   COMMAND                  CREATED              STATUS              PORTS               NAMES
	4db873920d19        img-captain--astro:1                    "/usr/sbin/httpd"        1 second ago         Created                                 srv-captain--astro.1.kklpja6fefzwiktgojdo4h9mk
	42639e1d92e3        img-captain--astro:1                    "/usr/sbin/httpd"        7 seconds ago        Created             80/tcp              srv-captain--astro.1.byxsa5ldvqhhfda7s57y035ss
	b87724476692        img-captain--astro:1                    "/usr/sbin/httpd"        About a minute ago   Created             80/tcp              srv-captain--astro.1.zqvcrlpgykri5ahmrgul93srw
	2cda6052a20c        img-captain--astro:1                    "/usr/sbin/httpd"        9 minutes ago        Created             80/tcp              srv-captain--astro.1.zj4cilqwrgqx12j6bz9cryb7a
	abe97a38e687        img-captain--astro:1                    "/usr/sbin/httpd"        19 minutes ago       Created             80/tcp              srv-captain--astro.1.zjib7inwn2jnbhslorvt6w3a5
	646654bbacc6        img-captain--astro:1                    "/usr/sbin/httpd"        41 minutes ago       Created             80/tcp              srv-captain--astro.1.zt6ydh5tz588q8rnyq8rig7v8
	39a18e274144        dockersaturn/certbot-sleeping:v0.17.0   "/bin/sh -c 'sleep 9…"   About an hour ago    Up About an hour    80/tcp, 443/tcp     captain-certbot.1.bbgde4tbcafz030ovbhkl4j1n
	da908b7446c7        nginx:latest                            "nginx -g 'daemon of…"   About an hour ago    Up About an hour    80/tcp              captain-nginx.1.nhixucy2pmxn5pl6zli2vfmq3
	58c070fbd132        dockersaturn/captainduckduck:0.5.4      "npm start"              About an hour ago    Up About an hour    3000/tcp            captain-captain.1.179yggv5u8se5s1ct9cer6i2i

**Comment by githubsaturn** [comment]
https://stackoverflow.com/questions/43734412/what-does-created-container-mean-in-docker

There is a problem in the Dockerfile.

**Comment by githubsaturn** [comment]
Taking another look at your dockerfile, I spotted at least one issue, you're using cd command in RUN. https://stackoverflow.com/questions/17891981/docker-run-cd-does-not-work-as-expected

As I said, if you want to use custom Dockerfile, either make sure it's a well documented and supported Dockerfile. Or take a day or two and learn Dockerfiles. Try building on your local machine. It is actually way easier than what it might look. Being able to build a Docker image on your local machine before deploying to Captain always gives you the confidence that your Dockerfile is tested and proved to be working.

**Comment by githubsaturn** [comment]
Try removing `"ENTRYPOINT [\"/usr/sbin/httpd\"]"` this line. This is why you don't see any logs. httpd by default runs on background. If you remove this line, it uses a "foreground" flag from the base image.

**Comment by drmrbrewer** [comment]
> Try removing "ENTRYPOINT..."

Then the logs show:

	$ docker service logs srv-captain--astro --follow --timestamps
	2018-02-08T16:48:25.895391075Z srv-captain--astro.1.s1ga5wrxad23@astro    | AH00534: httpd: Configuration error: No MPM loaded.
	2018-02-08T16:48:31.748450748Z srv-captain--astro.1.835t8q1uf6ni@astro    | AH00534: httpd: Configuration error: No MPM loaded.
	2018-02-08T16:48:37.700146908Z srv-captain--astro.1.fii7b0m6p48h@astro    | AH00534: httpd: Configuration error: No MPM loaded.
	2018-02-08T16:48:43.667489617Z srv-captain--astro.1.qe8zcy2dmabn@astro    | AH00534: httpd: Configuration error: No MPM loaded.
	2018-02-08T16:48:49.576831738Z srv-captain--astro.1.yfsdl343lkt1@astro    | AH00534: httpd: Configuration error: No MPM loaded.
	
	etc...

**Comment by drmrbrewer** [comment]
OK I made progress... seems like the default location for file in the apache distribution [vary a lot](https://wiki.apache.org/httpd/DistrosDefaultLayout).  Using the ones for ubuntu in the dockerfile, I seem to have the apache container up and running... though still further work to do to get the actual astro stuff to be accessible.  Thanks for the pointers.
