### ISSUE TITLE
Deploying via github

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#173]
I'm just tried [deploying via github](https://github.com/githubsaturn/captainduckduck/wiki/Deployment-Methods#deploy-using-github-bitbucket-and-etc) for the first time.  This is really neat, because it's for use with a repo which I don't need to actively work on, so I can do the odd little tweak (if required) directly on github (no need to keep and work on a local copy in my IDE).  And when I commit a change directly on github, sure enough this triggers a deploy via the webhook... neat!

Quick question: when using the above method, I assume that it still takes advantage of docker layers during the build, so that docker can re-use most of a previous build?  For example, if I just edit the README file in the repo, then the triggered build will not be too time consuming?

**Comment by tuefekci** [comment]
If an image gets rebuild docker handles the caching itself so if you only change app a bit and not the container there should be not a full rebuild.
