### ISSUE TITLE
Support for DotNet Core + ASP.net Core? [question]

### ISSUE THREAD

**Issue by fredyfx** [githubsaturn/captainduckduck#174]
Are you planning to implement support for DotNet Core? ASP.net Core runs on GNU/Linux and it is possible to use docker with it.

**Comment by tuefekci** [comment]
Why do you think it would not be supported if it is a docker container captain can run it?

**Comment by githubsaturn** [comment]
This is a tool where you can convert any Dockerfile into captain-definition:
https://githubsaturn.github.io/dockerfile-to-captain/
