### ISSUE TITLE
Increase PHP file upload limit for wordpress

### ISSUE THREAD

**Issue by seospace** [githubsaturn/captainduckduck#175]
https://github.com/docker-library/wordpress/issues/10

Just for A [web] developer who does not like spending hours and days setting up a server, build tools, sending code to server.

I know it can be done after deployment, but this does not apply to concept of single-click app.
Amazing project btw. thank you 👍

**Comment by tuefekci** [comment]
Theres http://php.net/manual/en/function.ini-set.php for runtime settings which should work in your wp config but im not sure how the image is handled, this should in my opinion not be handled by captain because everybody wants and needs different settings.

If you go the proper way with nicer application development etc. anyway perhaps you should think about not hosting your files on the same box most cloud providers support spaces now which makes the whole container setup way more usefull.

**Comment by seospace** [comment]
@tuefekci can you tell more about "whole container setup more usefull"?

**Comment by githubsaturn** [comment]
@seospace 
Unfortunately, these are application specific. If WordPress maintainers expose those values through some environmental variable, CaptainDuckDuck can add them to one-click app. Otherwise, the only way for CaptainDuckDuck to support this is to fork WordPress Docker image and have its own version of WordPress which is obviously impossible to maintain.

**Comment by rafaelstz** [comment]
If you try to change in the Docker container the configuration will be missed during the container reloads, in order to customize it and keep using the native Docker from WordPress you just need to access your server, create a file uploads.ini which is including your changes, and set this file as persistent, I created a file in this path below with the respective content.

    /var/lib/docker/volumes/caprover--rafael-wp-data/uploads.ini

```
file_uploads = On
memory_limit = 500M
upload_max_filesize = 500M
post_max_size = 500M
max_execution_time = 600
```

After setting it, your container will be reloaded and it's going to be like this image below.

![Screen Shot 2021-04-10 at 12 31 09 AM](https://user-images.githubusercontent.com/610598/114258374-15824300-9994-11eb-84c6-df3cd152ad23.png)

**Comment by TeamWolfyta** [comment]
I know this is an old thread but i found another way which feels easier and doesnt require editing persistent directories...

1. After you access your server, Goto `/var/lib/docker/volumes/`

2. After your there, look for a folder labeled `captain-{your wordpress name in the captain ui}-data`, Once you find it go inside it,
My url path now looks like this: `/var/lib/docker/volumes/captain--wordpress-wp-data/`

3. Within that folder should be another folder labeled `_data`, Click on it and confirm there is a wordpress instnace in there..
My url path now looks like this: `/var/lib/docker/volumes/captain--wordpress-wp-data/_data/`

4. In that `_data` folder create a new file named `php.ini` and then paste this in: 
```ini
# Change the values to what you need them to be!
upload_max_filesize = 64M
post_max_size = 64M
max_execution_time = 300
```

5. After you have created the new file head over to the captain dashboard, Locate the wordpress instance and click "save and update" to get the container to reload with the `php.ini` 

**Done!**
This worked for, Id imagen it would work for anyone else, if it doesnt work for you then i do appologise!

**Comment by Cristy94** [comment]
> I know this is an old thread but i found another way which feels easier and doesnt require editing persistent directories...
> 
> 1. After you access your server, Goto `/var/lib/docker/volumes/`
> 2. After your there, look for a folder labeled `captain-{your wordpress name in the captain ui}-data`, Once you find it go inside it,
>    My url path now looks like this: `/var/lib/docker/volumes/captain--wordpress-wp-data/`
> 3. Within that folder should be another folder labeled `_data`, Click on it and confirm there is a wordpress instnace in there..
>    My url path now looks like this: `/var/lib/docker/volumes/captain--wordpress-wp-data/_data/`
> 4. In that `_data` folder create a new file named `php.ini` and then paste this in:
> 
> ```ini
> # Change the values to what you need them to be!
> upload_max_filesize = 64M
> post_max_size = 64M
> max_execution_time = 300
> ```
> 
> 5. After you have created the new file head over to the captain dashboard, Locate the wordpress instance and click "save and update" to get the container to reload with the `php.ini`
> 
> **Done!** This worked for, Id imagen it would work for anyone else, if it doesnt work for you then i do appologise!

This worked, thank you!

Any idea why this works? Does caprover do something specific to copy the php.ini, or is it a WP app specific thing?

**Comment by githubsaturn** [comment]
CapRover doesn't do anything specific, this is purely just WordPress app.

**Comment by aistablediffusion** [comment]
> I know this is an old thread but i found another way which feels easier and doesnt require editing persistent directories...
> 
>     1. After you access your server, Goto `/var/lib/docker/volumes/`
> 
>     2. After your there, look for a folder labeled `captain-{your wordpress name in the captain ui}-data`, Once you find it go inside it,
>        My url path now looks like this: `/var/lib/docker/volumes/captain--wordpress-wp-data/`
> 
>     3. Within that folder should be another folder labeled `_data`, Click on it and confirm there is a wordpress instnace in there..
>        My url path now looks like this: `/var/lib/docker/volumes/captain--wordpress-wp-data/_data/`
> 
>     4. In that `_data` folder create a new file named `php.ini` and then paste this in:
> 
> 
> ```ini
> # Change the values to what you need them to be!
> upload_max_filesize = 64M
> post_max_size = 64M
> max_execution_time = 300
> ```
> 
>     5. After you have created the new file head over to the captain dashboard, Locate the wordpress instance and click "save and update" to get the container to reload with the `php.ini`
> 
> 
> **Done!** This worked for, Id imagen it would work for anyone else, if it doesnt work for you then i do appologise!

This don't work for me

**Comment by Cristy94** [comment]
> > I know this is an old thread but i found another way which feels easier and doesnt require editing persistent directories...
> > ```
> > 1. After you access your server, Goto `/var/lib/docker/volumes/`
> > 
> > 2. After your there, look for a folder labeled `captain-{your wordpress name in the captain ui}-data`, Once you find it go inside it,
> >    My url path now looks like this: `/var/lib/docker/volumes/captain--wordpress-wp-data/`
> > 
> > 3. Within that folder should be another folder labeled `_data`, Click on it and confirm there is a wordpress instnace in there..
> >    My url path now looks like this: `/var/lib/docker/volumes/captain--wordpress-wp-data/_data/`
> > 
> > 4. In that `_data` folder create a new file named `php.ini` and then paste this in:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```ini
> > # Change the values to what you need them to be!
> > upload_max_filesize = 64M
> > post_max_size = 64M
> > max_execution_time = 300
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 5. After you have created the new file head over to the captain dashboard, Locate the wordpress instance and click "save and update" to get the container to reload with the `php.ini`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Done!** This worked for, Id imagen it would work for anyone else, if it doesnt work for you then i do appologise!
> 
> This don't work for me

Did you restart the container or at least apache?

**Comment by Fernandodacruz** [comment]
After a lot of research and trial and error you helped me and it worked perfectly. Thank you very much!.

> Eu sei que este é um tópico antigo, mas encontrei outra maneira que parece mais fácil e não requer a edição de diretórios persistentes ...
> 
> 1. Depois de acessar seu servidor, Goto`/var/lib/docker/volumes/`
> 2. Depois de chegar lá, procure uma pasta rotulada `captain-{your wordpress name in the captain ui}-data`. Depois de encontrá-la, entre nela. 
>    Meu caminho de url agora se parece com isto:`/var/lib/docker/volumes/captain--wordpress-wp-data/`
> 3. Dentro dessa pasta deve haver outra pasta rotulada `_data`, clique nela e confirme se há uma instância do wordpress lá. 
>    Meu caminho de url agora se parece com isto:`/var/lib/docker/volumes/captain--wordpress-wp-data/_data/`
> 4. Nessa `_data`pasta, crie um novo arquivo chamado `php.ini`e cole-o em:
> 
> ```ini
> # Change the values to what you need them to be!
> upload_max_filesize = 64M
> post_max_size = 64M
> max_execution_time = 300
> ```
> 
> 5. Depois de criar o novo arquivo, vá para o painel do capitão, localize a instância do wordpress e clique em "salvar e atualizar" para que o contêiner seja recarregado com o`php.ini`
> 
> **Feito! ** Isso funcionou, imagino que funcionaria para qualquer outra pessoa, se não funcionar para você, peço desculpas!

After a lot of research and trial and error you helped me and it worked perfectly. Thank you very much!

**Comment by cykyy** [comment]
> > I know this is an old thread but i found another way which feels easier and doesnt require editing persistent directories...
> > 
> > 1. After you access your server, Goto `/var/lib/docker/volumes/`
> > 2. After your there, look for a folder labeled `captain-{your wordpress name in the captain ui}-data`, Once you find it go inside it,
> >    My url path now looks like this: `/var/lib/docker/volumes/captain--wordpress-wp-data/`
> > 3. Within that folder should be another folder labeled `_data`, Click on it and confirm there is a wordpress instnace in there..
> >    My url path now looks like this: `/var/lib/docker/volumes/captain--wordpress-wp-data/_data/`
> > 4. In that `_data` folder create a new file named `php.ini` and then paste this in:
> > 
> > ```ini
> > # Change the values to what you need them to be!
> > upload_max_filesize = 64M
> > post_max_size = 64M
> > max_execution_time = 300
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 5. After you have created the new file head over to the captain dashboard, Locate the wordpress instance and click "save and update" to get the container to reload with the `php.ini`
> > 
> > **Done!** This worked for, Id imagen it would work for anyone else, if it doesnt work for you then i do appologise!
> 
> This worked, thank you!
> 
> Any idea why this works? Does caprover do something specific to copy the php.ini, or is it a WP app specific thing?

It worked for me. Thanks a lot.

**Comment by uebmaster** [comment]
Ok, i've tried the @TeamWolfyta 's method but doesn't works for me.

What i did was the next:

I followed the path mentioned above.

Inside the volume's folder for the wordpress instance (/_data) i've edited the .htaccess file and added the lines:

```
php_value upload_max_filesize 256M
php_value post_max_size 256M
php_value max_execution_time 300
php_value max_input_time 300
```

Then save & restart the app in caprover and refresh the website.

 That's all.

I hope this will be useful for someone.

PD: Sorry for my bad english.

**Comment by xeddmc** [comment]
> I know this is an old thread but i found another way which feels easier and doesnt require editing persistent directories...
> 
> 1. After you access your server, Goto `/var/lib/docker/volumes/`
> 2. After your there, look for a folder labeled `captain-{your wordpress name in the captain ui}-data`, Once you find it go inside it,
>    My url path now looks like this: `/var/lib/docker/volumes/captain--wordpress-wp-data/`
> 3. Within that folder should be another folder labeled `_data`, Click on it and confirm there is a wordpress instnace in there..
>    My url path now looks like this: `/var/lib/docker/volumes/captain--wordpress-wp-data/_data/`
> 4. In that `_data` folder create a new file named `php.ini` and then paste this in:
> 
> # Change the values to what you need them to be!
> upload_max_filesize = 64M
> post_max_size = 64M
> max_execution_time = 300
> 5. After you have created the new file head over to the captain dashboard, Locate the wordpress instance and click "save and update" to get the container to reload with the `php.ini`
> 
> **Done!** This worked for, Id imagen it would work for anyone else, if it doesnt work for you then i do appologise!

You sir, are my personal jesus.
