### ISSUE TITLE
Feature Request 2FA

### ISSUE THREAD

**Issue by Ar1sC** [githubsaturn/captainduckduck#177]
Add 2FA Support if possible.

**Comment by githubsaturn** [comment]
Can't do that. It requires a dependency on a third party usually paid & non-opensource system.

**Comment by BamButz** [comment]
I would like to reopen this feature request.

> Can't do that. It requires a dependency on a third party usually paid & non-opensource system.

I think that's not true.
A 2FA can be implemented via TOTP the algorithm is open (https://tools.ietf.org/html/rfc6238) and there are also many free apps. (and of course closed source like Microsoft Authenticator)

I would be very pleased if we received an additional factor for authentication.

**Comment by devxpy** [comment]
Hello friend, thanks for the hard work caprover! 

On the paid front - firebase is practically free, and its client libraries are quite simple to use. 

Would you be open to the possibility of integrating firebase auth into caprover? It would also be really nice to have it for the basic HTTP auth for individual apps.

If firebase gives off too much of a proprietary vibe, maybe a plugin system so caprover doesn't get associated with a 3rd party.

I'm just too paranoid about 2FA after the twitter hack :D

**Comment by githubsaturn** [comment]
Please read [the discussion](https://github.com/caprover/caprover/issues/493). There is not much added security provided by 2FA in contrary to the perceived value. CapRover already provides guards against brute-force attack. Just use a password that is unique and long, and use a password manager.
