### ISSUE TITLE
Cannot deploy now to CDD using method1 or method3,

### ISSUE THREAD

**Issue by iamrommel** [githubsaturn/captainduckduck#178]
I was using always method 3 (via gitlab hooks) and the deployment is always a success...  Now i'm getting build logs

```
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/sliced 52ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/create-react-class 49ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/regexp-clone 58ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/muri 66ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/hooks-fixed 162ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/loose-envify 32ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/hoist-non-react-statics 34ms
[0m
[[ TRUNCATED ]]
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/ast-types-flow 42ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/axobject-query 44ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/damerau-levenshtein 42ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/emoji-regex 48ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/jsx-ast-utils 45ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/builtin-modules 32ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/contains-path 41ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/eslint-import-resolver-node 40ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/eslint-module-utils 40ms
[0m
[[ TRUNCATED ]]
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/decamelize 54ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/postcss-calc 48ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/postcss-colormin 45ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/postcss-convert-values 39ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/postcss-discard-comments 39ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/postcss-discard-duplicates 37ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/postcss-discard-empty 38ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/postcss-discard-overridden 38ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/postcss-discard-unused 42ms
[0m
[[ TRUNCATED ]]
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/tar-pack 50ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/tar 61ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/extsprintf 49ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/json-schema 47ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/verror 47ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/asn1 35ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/dashdash 39ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/getpass 37ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/jsbn 38ms
[0m
[[ TRUNCATED ]]
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/isobject 53ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/randomatic 54ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/repeat-string 49ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/p-try 50ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/spdx-license-ids 58ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/amdefine 56ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/is-utf8 57ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/tmpl 21ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/longest 13ms
[0m
[91mnpm[0m
[91m [0m
[91mhttp[0m
[91m [0m
[91mfetch[0m
[91m GET 200 https://registry.npmjs.org/fsevents/-/fsevents-1.1.3.tgz 554ms
[0m
[91mnpm[0m
[91m [0m
[91mERR![0m
[91m [0m
[91mcode[0m
[91m ENOGIT
[0m
[91mnpm[0m
[91m [0m
[91mERR![0m
[91m No git binary found in $PATH
[0m
[91mnpm[0m
[91m [0m
[91mERR![0m
[91m 
[0m
[91mnpm[0m
[91m [0m
[91mERR![0m
[91m Failed using git.
[0m
[91mnpm[0m
[91m [0m
[91mERR![0m
[91m Please check if you have git installed and in your PATH.
[0m
[91m
[0m
[91mnpm[0m
[91m [0m
[91mERR![0m
[91m A complete log of this run can be found in:
[0m
[91mnpm[0m
[91m [0m
[91mERR![0m
[91m     /root/.npm/_logs/2018-02-11T06_03_55_952Z-debug.log
[0m
{"code":1,"message":"The command '/bin/sh -c npm install && npm cache clean --force' returned a non-zero code: 1"}
The command '/bin/sh -c npm install && npm cache clean --force' returned a non-zero code: 1
----------------------
Deploy failed!
Error: {"code":1,"message":"The command '/bin/sh -c npm install && npm cache clean --force' returned a non-zero code: 1"}
The command '/bin/sh -c npm install && npm cache clean --force' returned a non-zero code: 1
```

Does any one have a hint i got that "No git binary found in $PATH"

**Comment by iamrommel** [comment]
I was able to build it on my local machine, but when ever i try this on CDD i got that error. Is there a need to have git on CDD container for this work?

**Comment by githubsaturn** [comment]
Did you add a dependency and then your build broke?

**Comment by githubsaturn** [comment]
This is not a Captain issue. Check this link https://github.com/npm/npm/issues/17985

Can you copy your `package.json` and your `captain-definition` file here please?

**Comment by iamrommel** [comment]
here is the definition
`{
 "schemaVersion" :1 ,
 "templateId" :"node/8.7.0"
}

`


here is the package.json
`{
  "name": "hauler",
  "private": true,
  "version": "1.20.3",
  "license": "MIT",
  "scripts": {
    "db": "mongod",
    "dev": "razzle start",
    "build": "razzle build && rm -rf dist && ncp build dist",
    "test": "mocha --require ./mocha-register.js  ./src/**/*.spec.js",
    "test:watch": "mocha --require ./mocha-register.js --watch  ./src/**/*.spec.js",
    "start": "NODE_ENV=production node dist/server.js",
    "deploy": "publish.sh",
    "tunnel": "ngrok http 3000"
  },
  "dependencies": {
    "apollo-cache-inmemory": "^1.1.5",
    "apollo-client": "^2.2.0",
    "apollo-link-batch-http": "^1.0.4",
    "apollo-link-context": "^1.0.3",
    "apollo-server-express": "^1.3.2",
    "body-parser": "  ^1.18.2",
    "express": "^4.16.2",
    "google-map-react": "^0.24.0",
    "graphql": "^0.12.3",
    "graphql-date": "^1.0.3",
    "graphql-tag": "^2.6.1",
    "graphql-tools": "^2.19.0",
    "lodash": "^4.17.4",
    "mailgun.js": "^2.0.1",
    "moment": "^2.19.1",
    "mongoose": "4.11.7",
    "pcmli.umbrella.backend": "^3.0.17",
    "pcmli.umbrella.core": "^5.4.11",
    "pcmli.umbrella.uni-core": "^0.7.7",
    "pcmli.umbrella.web-ui": "^6.1.10",
    "react": "^15.5.4",
    "react-apollo": "^2.0.4",
    "react-bootstrap": "^0.31.2",
    "react-dom": "^15.6.1",
    "react-dropdown": "^1.3.6",
    "react-redux": "^4.4.6",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "react-router-redux": "^4.0.8",
    "react-stripe-elements": "^1.3.2",
    "recharts": "^1.0.0-beta.10",
    "recompose": "^0.26.0",
    "redux": "^3.7.0",
    "redux-form": "^7.0.0",
    "redux-thunk": "^2.1.0",
    "stripe": "^5.4.0",
    "sweetalert": "^2.1.0",
    "toastr": "^2.1.4"
  },
  "devDependencies": {
    "@storybook/addons": "^3.3.11",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.5.1",
    "babel-preset-env": "^1.6.1",
    "chai": "^4.1.1",
    "chai-as-promised": "^7.1.1",
    "chai-enzyme": "^1.0.0-beta.0",
    "chai-subset": "^1.6.0",
    "concurrently": "^3.5.1",
    "enzyme": "^3.1.1",
    "enzyme-adapter-react-15": "^1.0.5",
    "ignore-styles": "^5.0.1",
    "jsdom": "^11.3.0",
    "mocha": "^4.0.1",
    "ncp": "^2.0.0",
    "raf": "^3.4.0",
    "razzle": "0.8.11",
    "react-addons-test-utils": "^15.6.2",
    "react-test-renderer": "15.6.1",
    "testdouble": "^3.2.5"
  }
}
`

**Comment by iamrommel** [comment]
So do we need to have git included on the cdd container or something.? I' did not use any git path for my packages that my application uses, but i'm not sure with the sub-sub dependencies. 

I was able to build correctly when i using my windows or ubuntu machine as long as there is a git on it.

 I'm trying now the 2nd method of deloyment

**Comment by iamrommel** [comment]
Same error when using method 2. 

What if there is a build method that just copies the files to the server. There is no need to run the dependencies that that was on my package.json. What if there is just a "dist" folder where all my runnanble deployment assests are packed and ready to run. I think it is a good deployment stategy just like the netlify.com does.

**Comment by githubsaturn** [comment]
This is due to an issue with npm as I mentioned above. npm requires git to install some dependecies. Simply use a full node image to get around this problem. Change your captain-definition file to this:
```
 {
  "schemaVersion" :1 ,
  "dockerfileLines" :[
                        "FROM node:8.7.0-alpine",
                        "RUN mkdir -p /usr/src/app",
                        "WORKDIR /usr/src/app",
                        "COPY ./src/package.json /usr/src/app/",
                        "RUN npm install && npm cache clean --force",
                        "COPY ./src /usr/src/app",
                        "ENV NODE_ENV production",
                        "ENV PORT 80",
                        "EXPOSE 80",
                        "CMD [ \"npm\", \"start\" ]"
                    ]
 }
```

You won't need to change anything else.

**Comment by githubsaturn** [comment]
PS: if your website is static and you have a `dist` directory, you can use a php image just to serve your static assets. To do so use this captain-definition file:

```
{
  "schemaVersion": 1,
  "dockerfileLines": [
    "FROM php7.2.2-apache",
    "COPY ./src/dist /var/www/html/"
  ]
}
```


Using this approach, Captain will not re-build your repo. Instead it simply serves all files statically from your dist folder. This assumes that you have an `index.html` for example sitting in your `dist` directory.

**Comment by iamrommel** [comment]
changing the captain-definition still does not work. same git not found error problem

**Comment by githubsaturn** [comment]
Did you commit this change? You have to commit the change. Otherwise, it won't be pushed to Captain.

**Comment by iamrommel** [comment]
yes sir, it was committed and push to my gitlab repo.. I even triple check from the gitlab web interface and it was there. I tried to run using gitlab push trigger webhooks, then it was triggered from CDD and starts building. The build logs shows using the node alpine

![image](https://user-images.githubusercontent.com/177265/36071252-828fce80-0f46-11e8-8b6d-7f9a2929d8ce.png)

**Comment by githubsaturn** [comment]
God.... My bad. I should have dropped the `-alpine` suffix. I updated my comment above. Please see that.

**Comment by iamrommel** [comment]
ALAS it works! Thank you very much, i really appreciate this. 

Your tip about using the PHP image for static sites are cool too. I think can put that on the wiki or something
