### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#179]
I see that Captain itself has a method to update itself, via the Settings page of the console.

What about updates to other packages... e.g. NetData, nginx, postgres (and other one click apps)?  When updates to those packages are released by their respective owners, is there a mechanism for doing this locally?  Perhaps it would be done as part of a Captain update?

**Comment by githubsaturn** [comment]
NetData and nginx, particularly nginx, are parts of Captain eco-system and they will be updated when CaptainDuckDuck gets an update. However, soon I'll add a new feature that allows users to override some variables - this is aimed at advanced users. Once I implement that, you don't even need to wait for Captain update to get an updated version of NetData.

For one-click apps, it is different. They are not part of the Captain ecosystem. They are pretty much like any other app that you deploy. For example, when you deploy a MySql one-click app, it is EXACTLY equivalent to deploying a folder with only one file in it - that is `captain-definition` and the content will be:
```
{
  "schemaVersion": 1,
  "dockerfileLines": [
    "FROM mysql:latest"
  ]
}
```

The only thing that Captain is doing on top of this is to set the volumes path for you, so you don't have to read MySql docs, https://hub.docker.com/_/mysql/

Note that the approach that Captain generally takes is similar to linux package managers, it uses the `:latest` suffix, not a specific tagged version. By using `FROM mysql:latest`, Captain makes sure that the version that gets deployed at the time of deployment is the latest version of MySql. However, in rare circumstances, you might need to deploy a specific version of MySql, say 5.7 for example. If so, simply create a `captain-definition` file, convert it to a`tar` file and deploy it to Captain via web dashboard.
```
{
  "schemaVersion": 1,
  "dockerfileLines": [
    "FROM mysql:5.7"
  ]
}
```
Next time you want to upgrade your `5.7` to `8.0`, you can simply create a `captain-definition` file like above, except, use `8.0` in it and deploy it via dashboard.

**Comment by drmrbrewer** [comment]
Thanks for the info.  For postgres, from [here](https://github.com/githubsaturn/captainduckduck/blob/99086bab24be0f3813ae818172f6c804449def69/app-frontend/src/oneclick-apps/postgres.js) I see that the `captain-definition` used is just:

	{
		schemaVersion: 1,
		dockerfileLines: [
			"FROM postgres:latest"
		]
	} 

So to update to the latest postgres I simply deploy that single file (as a `tar` file) to the `postgres` app (it doesn't matter that the app was created in the first place via the one-click convenience helper... now it's just an app like any other).

But you mention the persistent storage (docker volume)... what effect does deploying the above have on the volume, and the link between the `postgres` container and its volume?  Nothing?  The above is all I need to do, without having to re-do the volume setup?

**Comment by githubsaturn** [comment]
> But you mention the persistent storage (docker volume)... what effect does deploying the above have on the volume, and the link between the postgres container and its volume? Nothing? The above is all I need to do, without having to re-do the volume setup?

If you have an existing volume mapping, it'll stay as is.

**Comment by drmrbrewer** [comment]
I assume that if we choose to (re)deploy the postgres app by creating a very simple git repo (with just the simple `captain-definition` file in it) and doing a `captainduckduck deploy`, the existing volume mapping would also be preserved?

**Comment by githubsaturn** [comment]
Yes
