### ISSUE TITLE
Feature Request: Custom Dashboard URL

### ISSUE THREAD

**Issue by j7an** [githubsaturn/captainduckduck#181]
During initial setup there's no ability to customize the CDD subdomain. It automatically uses captain as subdomain.

I would like to use my own subdomain to either make it quicker to type and/or obfuscate that I'm running CDD e.g. "c.example.com" in case script kiddies are scanning for captain subdomains for possible vulnerabilities.

**Comment by tuefekci** [comment]
For the moment you can do your own fork and change the https://github.com/githubsaturn/captainduckduck/blob/master/app-backend/src/utils/CaptainConstants.js do your needs. I dont know tho if there needs more to be changed but you could try it.

**Comment by githubsaturn** [comment]
Done in https://github.com/githubsaturn/captainduckduck/commit/19e705d34606a802c3eb7e0641a09baff973de54

Will be released in 0.7.0

**Comment by koolamusic** [comment]
I cannot find a reference in the docs for how to make this happen. A sample `command` would be appreciated

**Comment by strathausen** [comment]
There's an example here https://github.com/caprover/caprover/issues/203#issuecomment-761255966
