### ISSUE TITLE
How can i connect to my monngodb intance externally

### ISSUE THREAD

**Issue by iamrommel** [githubsaturn/captainduckduck#182]
So i deployed i CDD's mongodb apps and it was successful. I created another nodejs app followed the guidelines from https://github.com/githubsaturn/captainduckduck/wiki/Complete-Webapp-Tutorial and everything works which is very sweet. This assures me that my mongodb installation is correct and working as expected. I did also check the docker service logs <my-mongodb-instance-here> and it's returning mongodb logs, so i can prove that everything works in the perspective of mongodb installation

Now i want to manage my mongodb from the OUTSIDE, do some backup to separate server, fiddle some documents and collection using RoboMongo (my favorite mongodb client) but i was not able to connect to it.

I read some articles saying that connecting to containered mongodb has different approach. In summary
1. provide SSH details of the server
2. Get Mongodb container ID using, docker ps
3. Get local IP of the docker container using, docker inspect
4. use the above container IP to connect

I was able to connect to the server using ssh tunnel but I was not able to connect to mongodb because i guess i dont have the IP address of mongodb, which i cannot find it from the NetworkSettings of container after doing some docker inspect
![image](https://user-images.githubusercontent.com/177265/36083915-07473828-0ff3-11e8-8b5d-485d902f916d.png)

Is this intentional? Is there a way to have the local address there? I tried the captain-overlay-network (e.g. 10.0.0.7) on my robomongo connection but still not able to connect to. Any advice is appreaciated

**Comment by githubsaturn** [comment]
See https://github.com/githubsaturn/captainduckduck/issues/145

**Comment by iamrommel** [comment]
holy shit it works. Thanks
