### ISSUE TITLE
Question: what would be the most lightweight app to just serve some static content?

### ISSUE THREAD

**Issue by mbariola** [githubsaturn/captainduckduck#184]
I have a folder with assets for a static website (ok logic is Javascript but it's not a node app).

a PHP container seems a little overkill (unless it's running without Apache/Nginx) and the format of the website does not conform to Node apps format.

What would you recommend?

**Comment by j7an** [comment]
It should be fine. If you're not running PHP code, then the PHP interpreter should be dormant.

If you're concerned with security and / or performance, you can configure the Captain Definition File to always use the latest PHP container instead of a specific version.

**Comment by githubsaturn** [comment]
As @j7an , a simple php is usually good enough. If you want additional performance boost / reduction of memory consumption, use a custom `nginx` image, but it's a bit more involved as it requires creating a relatively complicated captain-definition file (dockerfile), compared to a simple php (apache):
```
{
 "schemaVersion" :1 ,
 "templateId" :"php/7.1.10"
}
```

I personally like the caching that nginx gives you, if you have a high traffic website, I think it's worth to explore the more complicated solution (custom nginx image).


Finally, the ultimate option is to use a plain Linux image, and map your source files to a volume and copy all source files to the volume and have it directly served by Captain's core nginx container. This is quite complicated and the benefit you get from it usually doesn't justify the complexity.
