### ISSUE TITLE
Feature Request: Turn On and Off Dashboard Access From CLI

### ISSUE THREAD

**Issue by j7an** [githubsaturn/captainduckduck#185]
Once I've setup my CDD and apps, I don't need to have the dashboard constantly running. I only need to use it once in a while to check Netdata or admin the apps.

It would be great if the CLI can turn on and off dashboard access as needed.

This will prevent brute force password cracking of the dashboard which controls all apps running on the server.

**Comment by githubsaturn** [comment]
The dashboard is just a front-end to the API. Disabling dashboard (front-end) doesn't increase the security. The API is what is being used to get auth token (login) and we cannot disable this. Well... technically, we "can" disable this but it means you won't be able to deploy apps. Your apps will still be functional, but you cannot deploy new versions of your app. If this is actually what you want, you can do it by completely turning off captain via:
```
docker service scale captain-captain=0
```

If you want to re-enable it, run:
```
docker service scale captain-captain=1
```

**Comment by j7an** [comment]
Thanks. I'll also try using Cloudflare since I can create the following page rules for the dashboard to slow down brute force attempts.

- Browser Integrity Check
- Security Level: I'm Under Attack
