### ISSUE TITLE
One-click app suggestion: Cloud9 IDE

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#186]
See [here](https://hub.docker.com/r/kdelfour/cloud9-docker/).  I got it up and running on a test server, but it would be nice if it were available easily via a captain one-click app, including setting up a persistent directory (volume).  However, even without specifying a volume in the `docker run` command I was able to create a workspace, so I'm not sure how a custom volume would be of benefit.  It looks like, by default, the above installation creates two randomly-named volumes within `/var/lib/docker/volumes`, one to hold the user files from the workspace, and another to hold a `cloud9.conf` file (that's all I've seen in there so far).

There's also a more recent one [here](https://hub.docker.com/r/mstev0du/cloud9-ide/), but it seems to be based on the same docker image... not sure how it differs.  As well as the above two, there also seem to be various (more recent) entries [here](https://hub.docker.com/u/cloud9/), under what looks like the "official" cloud9 account... not really sure what they are but I would imagine that you'd need [shared](https://hub.docker.com/r/cloud9/shared/) and one of the workspaces, e.g. [nodejs](https://hub.docker.com/r/cloud9/ws-nodejs/).  

It's also not clear to me what status the Cloud9 IDE is, because Cloud9 (the company) was acquired by Amazon Web Services, but from the [wiki page](https://en.wikipedia.org/wiki/Cloud9_IDE) it seems that the Cloud9 IDE itself is freeware (non commercial).

**Comment by githubsaturn** [comment]
Integrating non-official / non well-supported images is a security hole. So, 3rd party docker images are no-go zone.

The two links that you shared look to be official, but they have zero documentation. And I couldn't find any link from Cloud9 website that points to that Docker images - which makes them fishy to me. But if you find an official / well-supported image of cloud9 I'll be more than happy to integrate it.


I think you already know this, but for the sake of other readers, I have to reiterate this:
Keep in mind that just because they are available as one-click apps, it doesn't mean you cannot use them with Captain. It just means that it'll be about 10 clicks... :smile: 

For example, if you want to use this: https://hub.docker.com/r/kdelfour/cloud9-docker/
All you need to do is:
1. Create an app with Persistent data on Captain dashboard
2. Create `captain-definition` file with this content:
```
{
  "schemaVersion": 1,
  "dockerfileLines": [
    "FROM kdelfour/cloud9-docker"
  ]
}
```

3. Convert `captain-definition` file to `tar` file

4. Upload `tar` file to Captain dashboard (under Deployment in your newly created app)

5. Done

**Comment by drmrbrewer** [comment]
About the "official" Docker images, there is at least [this reference](https://community.c9.io/t/how-to-mimic-the-c9-environment-on-a-local-machine/9860/2) from someone from Cloud9 to the [ws-default](https://hub.docker.com/r/cloud9/ws-default/) and [shared](https://hub.docker.com/r/cloud9/shared/) images... to quote: "Our workspaces use docker images and most of them are publicly available".

**Comment by githubsaturn** [comment]
Sweet. Thanks! Any docs explaining the usage?

**Comment by drmrbrewer** [comment]
Can't find any yet.

**Comment by drmrbrewer** [comment]
I'm struggling to understand how to get the "official" docker images to work (not experienced enough... yet).  But I've been looking at a couple of other dockerfiles, including the one originally linked above:

https://hub.docker.com/r/kdelfour/cloud9-docker/~/dockerfile/
https://hub.docker.com/r/agungf/c9-ide/~/dockerfile/

These seem to have in common that (a) they rely on installing the standard ubuntu package `supervisor`; and (b) they also clone the [C9 Core](https://github.com/c9/core.git).  The base image for the `agungf` dockerfile seems to be just a standard-ish ubuntu image (probably the "official" ubuntu image would be fine), and everything else seems also to be "standard" or "official", including the Cloud 9 stuff which comes from the "official" [Cloud 9 Core](https://github.com/c9/core.git).

So, as far as I can see, everything in these dockerfiles (particularly the second one, which starts from a base ubuntu image) is from "official" or "standard" sources, so there is nothing to be concerned about?  

On this basis, is it possible to add something like this as a one-click app?  Would be *really* neat... :-)

**Comment by drmrbrewer** [comment]
An alternative (and better documented) cloud IDE is https://eclipse.org/che/

**Comment by drmrbrewer** [comment]
When I said "easy to get up and running", it certainly is from the CLI on the server itself, with:

    # docker run -ti -v /var/run/docker.sock:/var/run/docker.sock -v /root/data:/data eclipse/che start

But I still haven't been able to create a suitable `captain-definition` file to deploy it as a captain app :-/

Eclipse Che does look good though... :-)

**Comment by drmrbrewer** [comment]
Whilst Eclipse Che is really good, probably for my purposes it's a bit overkill.  Cloud 9 does all I need, while Eclipse Che aims to go a lot further, and probably with a lot of bloat I don't need and never will.  So, if Cloud 9 is too "undocumented" to add as a one-click app in Captain, I'll probably just create my own 10-click app based on `kdelfour/cloud9-docker` (I will copy the dockerfile and tweak a little for my purposes).  One question... on Captain, when creating an app with persistent data, is it actually necessary to do `Add Directory` in the app settings to add a volume?  Because it seems to work without that... the docker volumes required are seemingly added already as part of the installation... is it even necessary to tick "with persistent directories" when creating the app in Captain?

**Comment by drmrbrewer** [comment]
OK I've been trying to get a bare-bones `captain-definition` for running a Cloud9 IDE instance in an Ubuntu container.  It seems common with example dockerfiles out there to install some unnecessary stuff, and also to run `supervisor` or `forever`.  The latter are there, I understand, to keep Cloud9 running (e.g. if it crashes) but I've tried to strip that out to get back to basics.

Finally managed to get it working, with the following `captain-definition` to install Cloud9... *note*: everything in this is from an "official" and even [documented](https://cloud9-sdk.readme.io/v0.1/docs/running-the-sdk) source :-)  The only thing in my mind is the slight uncertainty about the future of the Cloud9 APK (at least the open-source version) given the takeover by AWS.

    {
      "schemaVersion": 1,
      "dockerfileLines": [
        "FROM ubuntu:latest",
    
        "# Install build dependencies...",
        "RUN apt update && apt install -y build-essential git curl",
    
        "# Install node.js...",
        "RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -",
        "RUN apt-get install -y nodejs",
    
        "# Install Cloud9...",
        "RUN git clone https://github.com/c9/core.git /cloud9 && \\",
        "    cd /cloud9 && \\",
        "    scripts/install-sdk.sh",
    
        "# Clean up apt stuff now that we've finished...",
        "RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*",
    
        "# Add volume...",
        "RUN mkdir /workspace",
        "VOLUME /workspace",
    
        "# Set up stuff for Cloud9...",
        "ENV c9addr 0.0.0.0",
        "ENV c9port 80",
        "ENV c9user cloud9",
        "ENV c9pass rocks",
        "ENV c9workspace \"/workspace\"",
    
        "# Expose port...",
        "EXPOSE 80",
    
        "# And kick it all off...",
        "CMD node /cloud9/server.js --listen $c9addr --port $c9port --auth $c9user:$c9pass -w $c9workspace"
      ]
    }

I'm still not sure I'm doing the docker volume (persistent storage) setup correctly... you'll see I'm using the `VOLUME` directive in the `captain-definition`, but I'm not sure how this relates to what you might set up in the App page in Captain.

I'm also not sure if there's a better way to pass the login details to the `node` command that starts the Cloud9 instance... e.g. to set up that via the App page on the Captain console... is that possible?

**Comment by githubsaturn** [comment]
> Whilst Eclipse Che is really good, probably for my purposes it's a bit overkill. Cloud 9 does all I need, while Eclipse Che aims to go a lot further, and probably with a lot of bloat I don't need and never will. So, if Cloud 9 is too "undocumented" to add as a one-click app in Captain, I'll probably just create my own 10-click app based on kdelfour/cloud9-docker (I will copy the dockerfile and tweak a little for my purposes). One question... on Captain, when creating an app with persistent data, is it actually necessary to do Add Directory in the app settings to add a volume? Because it seems to work without that... the docker volumes required are seemingly added already as part of the installation... is it even necessary to tick "with persistent directories" when creating the app in Captain?

Checking the Persistent Data checkmarks locks down your app to one single machine. Even if you have a volume with Docker, if Docker moves your app from one machine to another (due to restart or etc), you will lose all the data.

> I'm still not sure I'm doing the docker volume (persistent storage) setup correctly... you'll see I'm using the VOLUME directive in the captain-definition, but I'm not sure how this relates to what you might set up in the App page in Captain. I am finding that I'm getting different (random) volume names under /var/lib/docker/volumes/ each time I rebuild the app, which clearly isn't ideal... need a fixed and consistent name so that the same volume (and user data) is used each time... any hints appreciated!

Creating volume mapping on dashboard is necessary. Without that, the volume would be a temporary one. To test, simply restart your machine. Your volume data will be gone.

> I'm also not sure if there's a better way to pass the login details to the node command that starts the Cloud9 instance... e.g. to set up that via the App page on the Captain console... is that possible?

Simply remove these lines from your DockerfileLines:
```
    "ENV c9user cloud9",
    "ENV c9pass rocks",
```

And add them as env variables on Captain dashboard. For example:
- Key: `c9pass`    Value: `rocks`

**Comment by drmrbrewer** [comment]
Do you know why, when I launch the IDE in the browser via the public URL, I get a `WebSocket connection` error showing up in the browser's console?  

	ide.html:186 Total Load Time:  624
	08:59:40.124 default.js:156517 WebSocket connection to 'wss://cloud9.test.example.com/vfs/1/9cALhHXyVk9gBIwM/socket/?access_token=token&EIO=3&transport=websocket&sid=w8z6LoGnkKq2SDE9AABG' failed: Error during WebSocket handshake: Unexpected response code: 400
	08:59:40.404 default.js:16956 Collab connecting
	08:59:40.885 default.js:43838 PubSub connected
	08:59:40.897 default.js:17024 COLLAB connected - SLAVE

Is this possibily a nginx issue connecting into the Cloud9 container?

**Comment by githubsaturn** [comment]
Yes - websocket needs special treatment for nginx:
https://www.nginx.com/blog/nginx-nodejs-websockets-socketio/

**Comment by drmrbrewer** [comment]
Hmm, I'd already tried that (or rather the advice [here](https://github.com/c9/core/issues/301) which is basically much the same).  Still can't get rid of that message :(  The IDE seems to work regardless, but it troubles me that the websocket connection error will cause me grief in some way that I don't yet know.

The `captain-definition` I'm using now to install this 10-click app is:

	{
		"schemaVersion": 1,
		"dockerfileLines": [
			"FROM ubuntu:latest",
			"RUN apt update && apt install -y build-essential git curl",
			"RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -",
			"RUN apt-get install -y nodejs",
			"RUN git clone https://github.com/c9/core.git /cloud9 && \\",
			"    cd /cloud9 && \\",
			"    scripts/install-sdk.sh",
			"RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*",
			"RUN mkdir /workspace",
			"ENV c9addr 0.0.0.0",
			"ENV c9port 80",
			"ENV c9workspace \"/workspace\"",
			"EXPOSE 80",
			"CMD node /cloud9/server.js --listen $c9addr --port $c9port --auth $c9user:$c9pass -w $c9workspace --collab --packed"
		]
	}

With app settings in Captain:

    HTTPS enabled
    ENV c9user : cloud9
    ENV c9pass : rocks
    PERSISTENT DIR /workspace : cloud9

**Comment by drmrbrewer** [comment]
The fix was to add three lines to the app's nginx configuration file:

        location / {

            ........................
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
            ........................

            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

This is based on [this](https://www.nginx.com/blog/nginx-nodejs-websockets-socketio/).  Are the above three lines very special to this use case, or could they be included in the default nginx config so that websockets will work out of the box with a Captain app?

**Comment by githubsaturn** [comment]
It's a good idea to add it to default as most modern apps use it anyways. I need to do some research to make sure there's no gotchas.

**Comment by githubsaturn** [comment]
Update on this:
I did some research on nginx websocket configs, and it turned out pretty much all credible resources, apply this connection upgrade on the route that needs the upgrade. i.e., it is only applied to `/chat` or `/ws`, and not by default applied to `/`. There seems to be some sort of overhead associated with this. I couldn't find any resource that points out the potential issues, but since all examples, use this upgrade on a particular path makes me believe this is the recommended way of doing it. Therefore, we cannot by default enable this config to nginx config.

See:
http://nginx.org/en/docs/http/websocket.html
and
https://www.nginx.com/blog/websocket-nginx/
and
https://blog.jverkamp.com/2015/07/20/configuring-websockets-behind-an-aws-elb/

**Comment by drmrbrewer** [comment]
Fair enough!  Worth checking out though.

**Comment by drmrbrewer** [comment]
It may be difficult for you to comment, but the last hurdle I've come up against with this Cloud 9 IDE app is that when I run a node app (based on an `express` server) inside the cloud 9 app, the server is only available via http... e.g. `http://cloud9.myserver.com:8080/test` and not via https.  I have of course enabled all HTTPS options in Captain settings, and whilst this makes the cloud9 app itself (i.e. the IDE) accessible via https, the node server running inside the cloud9 container is only accessible via http, via the port specified when starting up the cloud 9 server: `CMD node /cloud9/server.js --listen $c9addr --port $c9port`.  It's not a big issue because this is only of course for testing node apps, but it would be nice to get it right.

**Comment by githubsaturn** [comment]
This completely bypasses Captain and nginx. If you want HTTPS, you have implement your own https using Let'sEcnrypt "already-generate" certificate and create your own https binding in NodeJS. Something like this: https://stackoverflow.com/questions/5998694/how-to-create-an-https-server-in-node-js

**Comment by drmrbrewer** [comment]
Thanks.  I went a little way with that approach and could see how it would be possible.  But it seemed a bit complicated to know which of the various options to use with `certbot` / `letsencrypt`.  And also how to manage auto-renewal of the certificate.  It's probably easy when you know how, but it got me thinking how Cloud9 (i.e. the "real" Cloud9) managed to provide the node app running in the IDE on `https`, even though in the node app I was only starting the express server normally, i.e. not specifying any https certificates or anything.  With "real" Cloud9 the app is accessed on a different URL to the IDE.  So I figured that a similar approach with my Captain/Cloud9 setup would be to have a very simple node app that has the sole job of receiving requests over `https` and forwarding the request internally to the Cloud9 app over `http`.  So the cloud9 app is set up for https, but only for the actual IDE interface. 
 And the node app started within the IDE is accessed over https via what is effectively a proxy.  Benefit of this approach is that I can forget all about SSL keys etc and let Captain manage that for me :)  Seems to be working nicely.

Thanks for the push in the right direction!

**Comment by kristijanPetr** [comment]
Hi , 
Instead to open new Enhancement  I am writing here. Would like to suggest if its possible to implement as OneClick App NextCloud [link](https://github.com/nextcloud/server) 
or if you can tell me how to install through captain-definition schema file. Here is a [link](https://github.com/nextcloud/docker) to Docker Image of NextCloud 

Thanks
