### ISSUE TITLE
Assistance please,for deploying mongo 3.4

### ISSUE THREAD

**Issue by iamrommel** [githubsaturn/captainduckduck#190]
I was trying to do deploy using mongo 3.4 from from here https://github.com/docker-library/mongo/tree/cd03aec6375197ae86191886a876a12e8f2eaac7/3.4
and converted the dockerFile into captain definition, but it does not work. Here the steps that i  did

1. Copy the docker file from https://github.com/docker-library/mongo/blob/cd03aec6375197ae86191886a876a12e8f2eaac7/3.4/Dockerfile and converted it into captain definition using the above tool
-- i deleted the entry to copying the docker-entrypoint.sh (line 87 of the docker file) intentionally AFAIK, its for backward compatability stuff only.

2. Create 1 folder, and inside it create a captain captain-definition which contains the  above converted values.

3. Create a one-click--app mongo database, named it hauler. I intentionally cerated from the existing instance so directory structure will be defined initially

4. After successful creation of the app, upload my new tar file to the hauler app instance

5. The docker file script runs ok, but my mongod instance is not working. 
![image](https://user-images.githubusercontent.com/177265/36406478-24b5b584-1632-11e8-9ee1-fa900a0f34d7.png)

Can you share the captain definition file, on how you did it on the one-click-app for mongodb.

All i want is the mongo 3.4 instance, if there is better way please let me know

**Comment by githubsaturn** [comment]
This is the Dockerfile content from one click app.
https://github.com/githubsaturn/captainduckduck/blob/master/app-frontend/src/oneclick-apps/mongodb.js#L131


If you want 3.4, you can simply use this as your captain-definition file:
```
{
                    schemaVersion: 1,
                    dockerfileLines: [
                        "FROM mongo:3.4-jessie"
                    ]
 }
```

Don't forget to set persistent directories and environmental variables BEFORE you deploy your captain-definition file. To learn what persistent directories you should assign, simply create a one-click mongo db and see what environmental variables and persistent directories it's using.
