### ISSUE TITLE
Modifying app's nginx conf

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#193]
I see that in `/captain/generated/nginx/` there is `captain-root.conf` and `captain.conf`.  The latter is what seems to control how requests to your app are handled by nginx, i.e. requests to `myapp.myserver.mydomain.com`.

I can see that `captain-root.conf` is editable via the Settings page in Captain console.  But I can't see how the `captain.conf` file can be modified... I've done it directly on the `captain.conf` file itself, and I've got it to have the desired effect (to solve [this issue](https://github.com/githubsaturn/captainduckduck/issues/186#issuecomment-366902799)), but of course that file is generated and therefore will be overwritten at some point... need to edit captain's template instead.

**Comment by githubsaturn** [comment]
`captain.conf` is the app specific configuration. The content can be editted per app. To edit:
- Go to the dashboard
- Apps
- Select the app whose config you want to modify
- Click on the blue button which says `Edit Default Nginx Configurations`

**Comment by drmrbrewer** [comment]
D'oh!  I honestly did look in the app page but couldn't see it.  I was probably looking for something that appeared like the nginx stuff on the Settings page, rather than a button... and the nginx button is quite light compared to others, and it looks at first sight light it is "greyed out" / disabled, so I must have skipped over it:

not greyed out:
![image](https://user-images.githubusercontent.com/9009792/36583552-28eab81e-186e-11e8-960e-bd295abfc310.png)


greyed out:
![image](https://user-images.githubusercontent.com/9009792/36583590-4566f07a-186e-11e8-9b52-de448ceeb756.png)

not greyed out:
![image](https://user-images.githubusercontent.com/9009792/36583606-5233a168-186e-11e8-82e1-3b5b5712757d.png)

**Comment by githubsaturn** [comment]
It uses the same color for `nginx` on the settings page. The light blue is a standard button color from the palette of bootstrap.

![image](https://user-images.githubusercontent.com/10582082/36584002-d8bc94c0-182c-11e8-903c-204463d379a1.png)
