### ISSUE TITLE
Change the name to "Captain" so that I can ask my boss if we can use it

### ISSUE THREAD

**Issue by nkkollaw** [githubsaturn/captainduckduck#194]
I think the name CaptainDuckDuck might be cute, but it unnecessarily makes it harder to adopt it.

How can I ask my boss if it's OK to move our infrastructure from Proxmox to Captain DuckDuck?

How can I tell customers there's an outage and we're restarting CaptainDuckDuck..?

**Comment by githubsaturn** [comment]
I totally see your point. But I don't have any short-term plans to do this. Because:
- There are probably 1000s of software packages named Captain, out of those, 500 are probably related to Docker.
- SEO stuff will break by renaming CaptainDuckDuck to Captain
- There will be a lot of name collisions on npm and Docker
- Nothing prohibits you to call this "Captain", or CDD, or anything you want :-) ... if the name is actually that important to your clients / boss (not 5M+ Docker pulls and thousands of stars on Github)

Having said this, I keep this thread open and see what people say - and maybe they come up with better names. Important things to me are being memorable, have no Docker / npm collisions, be unique enough to be easily SEOed.

**Comment by tuefekci** [comment]
Proxmox != DuckDuck in the first place start Adopting Docker and explain more than the name of a Software you want to use to your boss, in the end the name is just a name it should not make any difference DuckDuck could be named CDD1234W51 and it would do the same so this is not really of any importance at all for adopting it the features should.

**Comment by nkkollaw** [comment]
Whatever you say, guys. I think the name is important. I talked about the project when I first saw it on Hacker News and it was laughed off because of the name. No one has even took a look at it.

I will also not be able to mention it to any of my clients, they have no idea what a Docker pull or a GitHub star is, so the name is an important part in their first impression.

**Comment by drmrbrewer** [comment]
Whilst I personally can see beyond a name, and don't have to justify use of CaptainDuckDuck to anyone else, I can understand how having such a name might be a deterrent to wider acceptance and adoption of this amazing tool.  Ultimately I think it depends on what @githubsaturn wants from this project.  

It reminds me of the public poll in the UK that was conducted to come up with a name for a scientific research vessel (i.e. something serious and worthy).  The public [overwhelmingly chose](https://www.theguardian.com/environment/2016/apr/17/boaty-mcboatface-wins-poll-to-name-polar-research-vessel) "Boaty McBoatFace" as the name.  Unsurprisingly, it was decided not to use that name, and instead to use something with a bit more gravitas.  Instead, the name was used for an underwater autonomous vehicle... somewhat lower-key and mostly hidden from public view.

So, does CaptainDuckDuck want to be one of these:

![image](https://user-images.githubusercontent.com/9009792/36721984-51908fbc-1ba4-11e8-9ff9-37ee7d8422b3.png)

Or one of these:

![image](https://user-images.githubusercontent.com/9009792/36722183-d17f2ca6-1ba4-11e8-9885-aaabe3fee96a.png)

?

**Comment by dkimot** [comment]
Seeing as how CaptainDuckDuck (CDD) is a relatively thin wrapper around Docker & Docker Swarm couldn't you "publicly" call the main system Docker or Docker-based and access your Docker Swarm through the CaptainDuckDuck UI? Also, CDD is not, as I understand it, trying to be comparable or to replace a system like Proxmox. For starters, CDD has no user management. In fact, it only has one user. While this is great for CDD it is generally not going to be ideal for an enterprise situation.

**Comment by nkkollaw** [comment]
> Seeing as how CaptainDuckDuck (CDD) is a relatively thin wrapper around Docker & Docker Swarm couldn't you "publicly" call the main system Docker or Docker-based and access your Docker Swarm through the CaptainDuckDuck UI?

I personally cannot, but why would it make sense to have to do that? What advantage does the name "Captain Duck Duck" brings compared to DockerWrapper123? There is no NPM package called docker-wrapper-manager, and people wouldn't laugh at me if I said I used it.

> Also, CDD is not, as I understand it, trying to be comparable or to replace a system like Proxmox. For starters, CDD has no user management. In fact, it only has one user. While this is great for CDD it is generally not going to be ideal for an enterprise situation.

I don't fully get why we keep talking about Proxmox. No one is saying that CaptainDuckDuck is comparable to Proxmox. I just mentioned that I currently use Proxmox and I would have difficulties saying "We are thinking about replacing Proxmox with CaptainDuckDuck, would that be OK?".

**Comment by drmrbrewer** [comment]
What about CaptainDockDock?

**Comment by nkkollaw** [comment]
> What about CaptainDockDock?

CaptainDockDock, CaptainDuckDuck, CaptainFuckFuck--they are all too playful for something as serious and important as devops.

**Comment by drmrbrewer** [comment]
My suggestion was slightly tongue in cheek.

**Comment by nkkollaw** [comment]
> My suggestion was slightly tongue in cheek.

Look, if you guys are jokers that's fine.

I just thought I'd provide my point of view. Obviously you believe that I'm the only one who thinks this way and/or don't care about adoptions by companies that have to at least pretend to do things seriously.

**Comment by drmrbrewer** [comment]
> Obviously you believe that I'm the only one who thinks this way 

Please re-read my first post... I am basically in agreement with you!  It's a completely valid point to raise so I'm not sure why you have closed this issue.  If I were having to justify the use of CaptainDuckDuck to others in a professional environment, I too feel that the name would count against it, regardless of what it is actually capable of.  As it happens, I don't, so it's not an issue for me.  That said, I did have to explain to the wife why I was spending so much time on a web page that features a yellow duck so prominently.
