### ISSUE TITLE
Deployment into CDD

### ISSUE THREAD

**Issue by aswinsatish** [githubsaturn/captainduckduck#195]
Hi
We have successfully deployed an application into cdd server using git method and is working fine as expected . Now when we git-push a change , the changes are getting deployed however there is slight downtime in destroying the old existing container and creating new one.
In order to enhance continuous deployment, is there any method to avoid the downtime, like keeping the current container and pushing the changes to new container after successful build, destroying the old container

**Comment by githubsaturn** [comment]
It's not as easy as it sounds. Captain uses Docker Service under the hood. The downtime comes from `docker service update`. Note that Docker doesn't kill your container before the new container is built. It only kills it just a few milliseconds before new version starts up. More details: https://github.com/githubsaturn/captainduckduck/issues/191

**Comment by githubsaturn** [comment]
Also this:
https://github.com/moby/moby/issues/30321
