### ISSUE TITLE
Capatain Duck Duck High availability

### ISSUE THREAD

**Issue by Briston-KS** [githubsaturn/captainduckduck#197]
Hi there,

Is there any methods by which we can make the CDD server with high availability. For example consider a case in which CDD is deployed in one server and we have applications installed on this server. In worst case scenario consider if the server is rebooted or encounter any issues, the entire application will have a downtime.

I'm checking if there are any methods such as provisioning and clustering the entire CDD servers in high availability such that if one server goes down, the application will be served from the another server without changing the Domain name.

**Comment by githubsaturn** [comment]
Captain has native support for redundancy. You can create a cluster of webservers and docker swarm automatically puts application on appropriate server (considering load and etc). If a worker server goes down, all apps running on that machine automatically get load balanced on other machines. 

Having said this, it doesn't apply to your main node. Main node, i.e., the leader, has meta data about the cluster, has SSL certificates and etc. This is the server where your DNS record will point to. If this server goes down, the cluster is dead.

**Comment by Briston-KS** [comment]
Thanks for the information. 

Is there any option or methods to make the leader node in high availability like using it under Amazon Load balancer  or Haproxy  etc

**Comment by githubsaturn** [comment]
I looked into a few options, but couldn't find a "universal" solution that works. I have it on my list to revisit this in the future.

**Comment by dottodot** [comment]
So does that mean you can't just have multiple managers to make to have high availability or can there only be one leader?

**Comment by githubsaturn** [comment]
Multiple managers are possible, but there is no point to it. As there will be only one leader anyways.

**Comment by dyllan-to-yu** [comment]
To mitigate the risk of having a single centralized leader, would it be possible to set up the raft protocol to dynamically change the leader based on availability? I think this would mainly depend on how straightforward it is to change the Caprover leader. 

A custom integration of the raft protocol might not even be necessary if it's possible to change the leader, by utilizing the raft state that's already integrated into the docker swarm manager. 

If this is considered necro I can open a new issue. I just stumbled across this and am curious about feasibility

**Comment by githubsaturn** [comment]
It's been discussed in the past. Bottom line is that it's out of scope of CapRover.

It's more complex that what it might seem like. Electing a new leader will be done automatically by Docker swarm. The problem is:
1- Syncing of `/captain` directory content.
App's details, nginx configs and SSL certs are in this directory on the leader. You cannot just move the services to a new leader and expect things to work.

2- DNS pointing to the new leader
Even if you resolve the first problem through a NFS or etc, you will still have to update your DNS to point the requests to the new leader. This usually takes hours.
