### ISSUE TITLE
Scaling of apps with persistent storage

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#198]
It's not possible to scale up apps that have persistent storage.  I understand the reason for the restriction where you've got multiple nodes, because you don't want an instance of the app ending up on a completely different node to the persistent storage it's meant to be accessing.

But if you're only running a single node, with multiple CPUs, you might want to scale up the app within that single node to take advantage of the additional CPUs.  With only a single node, all app instances will be on the same node as the persistent storage, so why is it not possible to scale up an app in this situation?  As I understand it, a docker volume is just a storage area sitting on the server outside of any of the containers, and within a container you just map from a folder in the container to a folder in the volume outside the container.

Even where there are multiple nodes present, it would be nice if an app with persistent storage was still scalable... so long as Docker/Captain ensured that the additional containers are installed on the node with the persistent storage.  I believe that this should be possible by setting [constraints](https://docs.docker.com/engine/reference/commandline/service_create/#specify-service-constraints-constraint) when establishing the service?

Another scenario I have in mind is where the docker volume is being used not so much because it is "persistent", but more because it is "shared".  The use case is a cache folder that benefits from being shared at least between multiple containers running on the same node, so that the app with "persistent storage" could still be scaled up onto any node, but accessing a shared volume on whichever node it is on... at least there is sharing between scaled apps on the same node, even if not between nodes.

It surprises me that with Docker it's not anyway possible to have a volume that is mappable from any container anywhere in the swarm, even if the volume and container are on different nodes.

**Comment by githubsaturn** [comment]
> But if you're only running a single node, with multiple CPUs, you might want to scale up the app within that single node to take advantage of the additional CPUs. With only a single node, all app instances will be on the same node as the persistent storage, so why is it not possible to scale up an app in this situation? As I understand it, a docker volume is just a storage area sitting on the server outside of any of the containers, and within a container, you just map from a folder in the container to a folder in the volume outside the container.

This is one of the main reasons which led me to design the system not to allow this to happen. Allowing this opens a can worm. For example, think about two MySQL apps trying to modify the same file. You will end up with a completely wrecked database!!

A good architecture is the one that splits the parts that can be parallelized into modules and microservices. But there won't be any good examples in the industry where multiple instances of apps access the exact same files.

> Even where there are multiple nodes present, it would be nice if an app with persistent storage was still scalable... so long as Docker/Captain ensured that the additional containers are installed on the node with the persistent storage. I believe that this should be possible by setting constraints when establishing the service?

Due to the problem I mentioned above this will only possible if Docker makes sure that it only spins off your application to nodes that do not have the same volume defined on them. This will be difficult and will be extremely confusing for people to debug.


> Another scenario I have in mind is where the docker volume is being used not so much because it is "persistent", but more because it is "shared". The use case is a cache folder that benefits from being shared at least between multiple containers running on the same node, so that the app with "persistent storage" could still be scaled up onto any node, but accessing a shared volume on whichever node it is on... at least there is sharing between scaled apps on the same node, even if not between nodes.

This is a really bad practice and it's another scenario that can wreck your files. Two apps should never modify the same file.

**Comment by drmrbrewer** [comment]
> This is a really bad practice and it's another scenario that can wreck your files.  Two apps should never modify the same file.

But it can be arranged that two apps don't modify the same file!  As a simple case, let's consider that multiple apps need read-only access to a set of very large data files.  Is it more efficient for each container to have its own copy of these data files, or more efficient for there to be a central *read-only* data store to which each container has access?  For me, it's the latter.  Furthermore, there is no danger of files being modified by multiple apps, because the storage is made read-only.

**Comment by githubsaturn** [comment]
In theory yes - but in practice no. How are you going to populate those large files to be used by the apps? Are they going to be SSH-copied over to the server? -> bad! it's not a deployment method - back to the stone age when we use to ftp copy files to servers for each deploy :) 

With the modern tools and separation of concerns, proper architecture with the system that you described is to have a highly efficient static file serving app (nginx for example) whose only job is to serve those static files to the other two apps.

**Comment by drmrbrewer** [comment]
OK, point well made!
