### ISSUE TITLE
enforce HTTPS on app

### ISSUE THREAD

**Issue by PookMook** [githubsaturn/captainduckduck#2]
Hi, great project!
I wonder if there is a way to enforce HTTPS on apps created by captainDuckDuck.
I can enable HTTPS, and redirect it using .htaccess for instance, but a proper enforce at the NGinx gateway would be better!
Thanks!

**Comment by githubsaturn** [comment]
Thanks for your suggestion! 
The redirection to HTTPS is typically being done at the application level as it's very common to track this redirection. Anyways, adding it to nginx only requires an additional server block. But it's trivial on the Captain side. I'll keep this issue open for some time to see if other people think this is a good feature to have.

**Comment by githubsaturn** [comment]
Feature is implemented in v0.4.0  :tada: :confetti_ball: :tada: 

https://github.com/githubsaturn/captainduckduck/releases/tag/v0.4.0
