### ISSUE TITLE
Multiple nodes: changing SSH key

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#202]
The [wiki](https://github.com/githubsaturn/captainduckduck/wiki/Server-Clustering-and-App-Scaling) relating to app scaling makes it easy to understand how to enable app scaling.

But one question is in the back of my mind...

One of the steps, when adding a second node, is to enter the private half of the SSH key that you use to SSH onto the second server.

What happens if, in future, I change my IDE, and use a new SSH key to ssh onto the second server (and first server, for that matter)?  I suppose the existing node cluster will just continue to operate as it ever did, and it's only when adding a *third* node that something changes... you just enter the new SSH key at that point... so the node cluster now utilises two different SSH keys to form the links, but that matters not?

**Comment by githubsaturn** [comment]
SSH keys are like passwords. You should never rely on IDE to generate them for you. But yes, your cluster will continue work.

**Comment by drmrbrewer** [comment]
> You should never rely on IDE to generate [SSH keys] for you

What do you mean by this?  If you're ssh'ing from your IDE to your server then isn't it natural to use the IDE to generate the SSH keys for this connection?  The private half remains on the IDE and the public half is installed on the server, so that when the server sends an encrypted message using the IDE's public key, only the IDE can read it.  Are you saying that you should generate the SSH keys somewhere other than the IDE and then install them on the IDE, rather than just running `ssh-keygen -t rsa` at the IDE?

**Comment by githubsaturn** [comment]
I am saying that even if you use your IDE to generate the keys, you should always make a copy of the pair and keep them safe.
