### ISSUE TITLE
Autoscaling of nodes in docker swarm

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#204]
I've had some fun today hacking up a 'monitor' app that monitors server load, and when it rises above a certain threshold, a new server is automatically spun up and added to the docker swarm.  It's working OK, but before I refine this further (and it needs a *lot* of refining still) I thought I'd check whether this is something that is ever likely to be added to captainduckduck (because you would do it a lot better than I can)?  I'm guessing not, because it probably goes beyond what captain is about, and also because it will be very host-specific (in terms of the API used to spin up and destroy servers etc).

**Comment by drmrbrewer** [comment]
After I autoscale down, by deleting a node, I'm updating (reducing) the number of instances of certain apps by running a function that is basically a cut-down version of your `updateService()` function [here](https://github.com/githubsaturn/captainduckduck/blob/e34b25a56ff5a759a0238ee11f53904958524acd/app-backend/src/docker/DockerApi.js#L1067-L1260).  

The service update worked, to change the number of instances, as confirmed by `docker service ls`.  However, Captain is showing the previous instance number for the app, despite refreshing / logging out / logging in etc.

I did find the following error in my log:

	Prune Containers Failed!
	{ Error: (HTTP code 500) server error - a prune operation is already running 
		at /usr/src/app/node_modules/docker-modem/lib/modem.js:254:17
		at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:284:7)
		at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:253:5)
		at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:229:14)
		at emitNone (events.js:111:20)
		at IncomingMessage.emit (events.js:208:7)
		at endReadableNT (_stream_readable.js:1064:12)
		at _combinedTickCallback (internal/process/next_tick.js:138:11)
		at process._tickCallback (internal/process/next_tick.js:180:9)
	  reason: 'server error',
	  statusCode: 500,
	  json: { message: 'a prune operation is already running' } }

Could that be the cause of the incorrect instance count?  Any idea why a prune operation would already be running... maybe it is performed automatically when a node is lost and the services are re-distributing across the remaining nodes, so when the [prune operation](https://github.com/githubsaturn/captainduckduck/blob/e34b25a56ff5a759a0238ee11f53904958524acd/app-backend/src/docker/DockerApi.js#L1246-L1256) is called at the end of `updateService()` there is a prune operation running?

How do I resync Captain with reality?  Doesn't Captain read the present instance counts dynamically when populating the App pages?

**Comment by githubsaturn** [comment]
> I've had some fun today hacking up a 'monitor' app that monitors server load, and when it rises above a certain threshold, a new server is automatically spun up and added to the docker swarm. It's working OK, but before I refine this further (and it needs a lot of refining still) I thought I'd check whether this is something that is ever likely to be added to captainduckduck (because you would do it a lot better than I can)? I'm guessing not, because it probably goes beyond what captain is about, and also because it will be very host-specific (in terms of the API used to spin up and destroy servers etc).

Yes - it'll be host specific and more importantly app specific. I don't have plans to implement this.


> How do I resync Captain with reality? I seem to have managed it just by changing the instance count in Captain to match reality, then Save & Update Configuration, but is there a better way? Doesn't Captain read the present instance counts dynamically when populating the App pages?

By doing manual updates on the instance count you are interfering with Captain workflow. Instance counts are saved in `/captain/config.conf` file along with other info about the app. To implement such a feature, you either need to update the instance count using Captain API - but it means that you'll be limited to Captain's functionalities. Alternatively, you can create a home-brewed solution or use some other deployment helper such as https://github.com/jwilder/nginx-proxy which is similar to Captain except it operates at a lower level - meaning that you won't get the ready-out-of-the-box functionalities, but it's more appropriate for such manual tweaking.

**Comment by drmrbrewer** [comment]
OK thanks.  It doesn't sound like it does any harm by having the instance count in Captain being out of sync with the actual instance count, so I can probably just put up with it.  Or, if it bothers me later, I can edit the `/captain/config.conf` file as part of the auto-scale method (scaling Captain down / up to prevent multiple access to that file while editing takes place).  Overall, the auto-scaling is working quite nicely :)

> or use some other deployment helper such as nginx-proxy 

You can't get rid of me that easily ;-)

**Comment by githubsaturn** [comment]
Be careful about config being out of sync. Once you Save Config and Update your app, Captain will reset the instance count to what it needs to be according to config file.

**Comment by drmrbrewer** [comment]
Yes, though so long as I am aware of that, I can remember not to trust the instance count reported in captain, and instead set it always to what it needs to be based on the current server scaling, _before_ I hit Update & Save.  No doubt, I will end up implementing a further tweak to update the captain config file so that it is more idiot proof, but for now I will rely on my own memory :)

**Comment by drmrbrewer** [comment]
> No doubt, I will end up implementing a further tweak to update the captain config file

I'm at that stage now.  Rather than trying to hack my own solution I thought I'd check what you're doing and do it consistently with that.  It seems that the conf handling (including file reading / storing?) is based around the [configstore module](https://www.npmjs.com/package/configstore), but I'm struggling to work out a quick and easy way to use that to (a) read an existing conf file in; (b) change an instance value; (c) save back to conf file.  Do you have any quick hints?  Would also need to scale captain down/up before/after.

**Comment by githubsaturn** [comment]
config file is a simple json, you can simply read it and parse it as json and save it back to the file. However, do this at your own risk. The system hasn't been designed to respect the changes from outside. It'll probably work, but I haven't tested / designed for this case.

**Comment by drmrbrewer** [comment]
> config file is a simple json, you can simply read it and parse it as json and save it back to the file

Sure, I realised that, but I thought that using `configstore` as a helper would align things a little more closely with cdd.  In pseudo-code, I had in mind that it could maybe be used something along the lines of `const config = new Configstore(captainConfigFileLocation); config.apps.myapp.instanceCount = 3; config.save();` which would just be a lot more convenient than doing things manually... and the benefit would be that the config file would look and parse exactly as it does now... not that formatting matters with JSON but it would still be nice to maintain some degree of consistency.

**Comment by drmrbrewer** [comment]
So it is super easy using `configstore` as a helper (the following having mounted /captain from host as /captain in container):

    const data = new Configstore('captain-store', {});
    data.path = '/captain/config.conf';
    data.set('appDefinitions.myapp.instanceCount', parseInt(newInstanceCount, 10));

**Comment by aberba** [comment]
Auto-scaling is very important for unexpected traffic ...when things go viral
