### ISSUE TITLE
Container prune after service update

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#206]
Why is this [section of code](https://github.com/githubsaturn/captainduckduck/blob/e34b25a56ff5a759a0238ee11f53904958524acd/app-backend/src/docker/DockerApi.js#L1246-L1256) included, apparently for pruning stopped containers after a service update?  I thought that pruning containers was left as a [manual process](https://github.com/githubsaturn/captainduckduck/wiki/Disk-Clean-Up), and that care should be taken (at present) if a Docker registry is not set up (as you note in the wiki page)?  I note that when I include code like this in my auto-scale method, it always seems to result in an error `Prune Containers Failed!  Error: (HTTP code 500) server error - a prune operation is already running`.

**Comment by githubsaturn** [comment]
It's for the cleanup purpose. For regular use, Captain performs docker prune on "containers", which is a safe operation as old containers won't come back to life.  The line that you are referring to in wiki is a "just-in-case" operation to make sure there is nothing left from the past. 

As for why you're getting that error, I am not sure. But you may be executing two commands with a short gap, this will cause two "prune" calls overlap and you get that error.

**Comment by drmrbrewer** [comment]
> As for why you're getting that error, I am not sure. But you may be executing two commands with a short gap, this will cause two "prune" calls overlap and you get that error.

I'm pretty sure it's not me executing two prunes in quick succession... I've just re-used your code (linked above) and am only calling that once.  I wonder whether docker itself, as part of the service re-scale process, does a container prune... and the prune that I'm initiating conflicts with that.  Though I'd expect you also to be seeing that error. 

In fact, the following comment in that section of code seems to me to suggest that you already anticipate that the requested prune might fail, so maybe you've seen this error in the past?

    // give some time such that the new container is updated.
    // also we don't want to fail the update just because prune failed.
 

Ultimately, I don't suppose it's that critical... the prune is only failing because a prune is already in process (by some other trigger), so either way, the prune is happening.

**Comment by drmrbrewer** [comment]
> I'm pretty sure it's not me executing two prunes in quick succession

My bad... I was executing two `updateService()` commands in succession, but I was `await`ing one before executing the next, thinking that that would mean they wouldn't overlap.  But in fact at the end of the [function](https://github.com/githubsaturn/captainduckduck/blob/e34b25a56ff5a759a0238ee11f53904958524acd/app-backend/src/docker/DockerApi.js#L1246-L1256) it starts a 5s `setTimeout()` for the `prune` operation and returns immediately, so that the next one does overlap.  Or, at least, *did* overlap.  So, as usual, you were completely correct.
