### ISSUE TITLE
Apps menu item in Captain console

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#209]
When I click into the settings of a particular app, and have scrolled some way down, I always intuitively expect to be able to return to the apps listing by clicking on the Apps entry in the menu on the left:

![image](https://user-images.githubusercontent.com/9009792/37820496-b0dfc262-2e78-11e8-99ce-ba8723a742be.png)

However, it does nothing.  Of course, to get back to the apps listing I can scroll all the way back up and click the little cross at top right, but it just seems more intuitive to be able to navigate back to the listing by clicking the menu item again... and far more convenient because it is always there and visible.

**Comment by mathiasm74** [comment]
I think I can fix this... Please feel free to assign.

**Comment by mathiasm74** [comment]
> @mathiasm74
> Thanks! This was a long overdue task! Have you tested the code?

@githubsaturn 
Yes, the code seems to work, as far as I've been able to test it. You saw the commit, right? Let me know what you think.

Need to work out how to keep the unrelated commit 02ac8fa out of the pull-request before I can submit it... (I'm not new to git, but it's been 5+ years since I did anything more advanced than commit and push)

**Comment by githubsaturn** [comment]
@mathiasm74 

I think it's easier to create a brand new branch and re-apply the required changes on that branch, close the current PR and open a new one. Removing stuff from `git` is not very straightforward.

**Comment by githubsaturn** [comment]
> Yes, the code seems to work, as far as I've been able to test it. You saw the commit, right? Let me know what you think.

Looks good as far as I can tell. Haven't tested it yet, but it looks good. Good job! :+1:
