### ISSUE TITLE
NetData not work

### ISSUE THREAD

**Issue by klinkov** [githubsaturn/captainduckduck#213]
Hi

1. Install captainduckduck
2. setup apps
3. turn on NetData
4. press on Open NetData button ([screenshot](https://monosnap.com/file/nVMC2mJ4BqYY8eE8mLHErULWEaD7n3))
5. Open /net-data-monitor/ page

See next text
{"status":1106,"description":"Auth token corrupted"}

Current Version: 0.6.0

**Comment by githubsaturn** [comment]
You may have changed the password while you were logged in. To fix:
- Close your browser
- Login using your password
- Click on open NetData as per: https://monosnap.com/file/nVMC2mJ4BqYY8eE8mLHErULWEaD7n3

**Comment by klinkov** [comment]
@githubsaturn  Thank you!

**Comment by r-chris** [comment]
I recently ran into the same issue when using one of the "Remember Me" options ("Use localStorage (Most Persistent)"). I can not reproduce it, but I assume the relevant token could have been expired? I was able to fix it by logging out and back in again as suggested.

**Comment by AnandChowdhary** [comment]
Perhaps we can re-open this issue. If you use the "Remember me" option with local storage, the netdata token still expires and you need to logout and login again to prevent the "auth data corrupted" error.

**Comment by conradfr** [comment]
FWIW I still get this error today on version 1.8.2 on a fresh install.

I even tried login from another browser with the same effect.

**Comment by locvfx** [comment]
Just logout Caprover, then re-login Caprover, reload your netdata. it will work

**Comment by Cristy94** [comment]
> You may have changed the password while you were logged in. To fix:
> 
> * Close your browser
> * Login using your password
> * Click on open NetData as per: https://monosnap.com/file/nVMC2mJ4BqYY8eE8mLHErULWEaD7n3

This also happened to be and **I did not change the password**, it was working fine, logged in the next day, I got this error.

**Comment by minkbear** [comment]
Got this error. so just log out from caprover and login again.

**Comment by Cristy94** [comment]
Why is this still closed? This happens constantly if you have session `localStorage` remember me enabled. I always have to log-out and log-in again to access NetData otherwise I get `Auth token corrupted`.

**Comment by codercodingthecode** [comment]
Still an issue caprover netdata. 
It doesn't matter which way I select to log in. I still get this error.

**Comment by zfcsoftware** [comment]
The captainCookieAuth in the cookies is set to be active during the session. This seems to be the problem. If you change the duration of this cookie to a later date, it gets fixed.

![image](https://github.com/caprover/caprover/assets/123484092/7b1f73c3-6ee8-4c7e-b4de-3b1b29dbe529)
