### ISSUE TITLE
Converting Dockerfile into a captain-definition file

### ISSUE THREAD

**Issue by dkimot** [githubsaturn/captainduckduck#214]
I wrote a script that converts a Dockerfile into a captain-definition file and modifies every `COPY` line so it is compliant with CDD and the fact that it moves the source code into a `src` directory. I run it as a git pre-commit hook through NPM and thought I would post it here because automation is always nice.

``` js
const fs = require('fs');
const path = require('path');

const dockerfileLines = fs.readFileSync(path.join(__dirname, '..', 'Dockerfile')).toString().split('\n');

for (let i = 0; i < dockerfileLines.length; i += 1) {
  let line = dockerfileLines[i];
  if (line.indexOf('COPY .') === 0) {
    dockerfileLines[i] = line.replace('COPY .', 'COPY ./src');
  }
}

const captainDefinition = JSON.stringify({
  schemaVersion: 1,
  dockerfileLines,
});

fs.writeFileSync(path.join(__dirname, '..', 'captain-definition'), captainDefinition);
```

**Comment by githubsaturn** [comment]
Added to Wiki:
https://github.com/githubsaturn/captainduckduck/wiki/Captain-Definition-File

**Comment by ckc** [comment]
> Added to Wiki:
> https://github.com/githubsaturn/captainduckduck/wiki/Captain-Definition-File

Moved to:
https://caprover.com/docs/captain-definition-file.html#use-dockerfile-in-captain-definition

:)
