### ISSUE TITLE
Webook detects new push but doesn't build image.

### ISSUE THREAD

**Issue by devxpy** [githubsaturn/captainduckduck#216]
As soon as i push my code to bitbucket, i see this.
```
------------------------- Fri Mar 30 2018 20:50:06 GMT+0000 (UTC)
Build started for quiz-django

```

But it dosn't say anything after that.

When i manually use `captainduckduck deploy`, it builds the image as usual..

#### captain-definition
```
{
  "schemaVersion": 1,
  "dockerfileLines": [
    "FROM library/python:3.6.4-jessie",

    "RUN apt-get update && apt-get install -y binutils libproj-dev gdal-bin",
    "RUN mkdir -p /usr/src/app",
    "WORKDIR /usr/src/app",

    "RUN pip install pipenv --upgrade",
    "COPY ./src /usr/src/app",
    "RUN pipenv install --deploy --system",

    "EXPOSE 80",
    "COPY ./src/runserver.sh /usr/local/bin/",
    "CMD [\"sh\", \"runserver.sh\"]"
  ]
}

```

**Comment by githubsaturn** [comment]
Did you change your password? Try re-entering your git information again, replace your old webhook in bitbucket with the new one. Let me know if it doesn't solve the issue.

**Comment by devxpy** [comment]
I did change my repo name and updated it accordingly.
I even tried pruning my whole server actually.

**Comment by githubsaturn** [comment]
Do you have a reproducible case for this? If you still have the issue, please try the following steps:

1 - Create a test app on Captain
2 - Clone one of the sample apps and use `captainduckduck deploy` to push it Captain
3 - Use the same sample app and push it to Bitbucket, enter bitbucket info on Captain, make a dummy commit and push it Captain


Does this work? Does it fail at step 2? Does it fail at step 3?

**Comment by devxpy** [comment]
Looks like it was a formatting issue in the repo name

I had put `https://bitbucket.org/user/repo` while captain requires only `bitbucket.org/user/repo`

Sorry for the inconvenience caused
