### ISSUE TITLE
letsencrypt certificate renewals

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#218]
I've had a few renewal notices from letsencrypt for some test apps I deployed a while ago.

Does captain handle auto renewal of certificates that are still in use?

**Comment by githubsaturn** [comment]
Yes it does do that automatically. Even if you receive an email regarding a domain that's currently being in use, chances are that you previously used that domain on another server, and you killed that server. But you used the same domain on a new server.
