### ISSUE TITLE
Guidance for deploying mongodb in replica set and multiple nodes for CDD

### ISSUE THREAD

**Issue by iamrommel** [githubsaturn/captainduckduck#219]
Is there a guidance or sample on how we can deploy mongodb replicate sets on multiple nodes for CDD

**Comment by githubsaturn** [comment]
We don't have application specific tutorials as CaptainDuckDuck is not limited to specific applications.

To answer your question:
- Simply deploy 3 independent MongoDB instances using one-click app process.
- Go to the apps details page and set the NodeId such that you put the MongoDB instances on different nodes.
- At this point, just look for a tutorial that teaches how to create a MongoDB cluster using 3 instances of MongoDB. The 3 deployed instances are simply just MongoDB instances - not specific to CaptainDuckDuck.
