### ISSUE TITLE
problem captain-definition

### ISSUE THREAD

**Issue by dockmanaman** [githubsaturn/captainduckduck#22]
hello when I want to use your nodeJS exemple I upload the .tar file and everything work
but when I download it , decompress it and compress it again   on my computer.  the upload process   doesn't work at all 

Error
Captain Definition file does not exist!

step to reproduce the problem

1) - download node.tar on GitHub 
2) decrompress on your computer 
3) compress using  terminal  
command : tar cjf node.tar node/  
or  tar cvf node.tar  node/

no file was removed  or moved or changed   

how did you compress the directory into .tar ? (software, operating system ...)
thank you.

**Comment by dockmanaman** [comment]
the err

**Comment by githubsaturn** [comment]
I have added support for this case as well. With the next release, doing what I explained above will be unnecessary.

**Comment by githubsaturn** [comment]
Released here:
https://github.com/githubsaturn/captainduckduck/releases/tag/v0.2.1
