### ISSUE TITLE
Deleting a one-click app does not completely wipe it from the system

### ISSUE THREAD

**Issue by mathiasm74** [githubsaturn/captainduckduck#220]
Steps to reproduce:
1) create a one-click mongodb app, then a one-click mongodb-express app.
2) use the mongodb-express app to add a "database" to mongodb.
3) delete the mongodb and mongodb-express apps in the CDD web interface.
4) repeat step 1 with the exact same parameters.
5) log into mongodb-express app again and observe that the database created in step 2 is still present.

Expected:
That all traces of the docker container and persistent data created in step 1 would be removed by step 3

**Comment by drmrbrewer** [comment]
Hmm, surely it's a good thing that Captain leaves it to the user to decide when and how to delete the persistent data?  IMHO the app and the data are separate, and deleting the app should _not_ delete the data.  The user's data should be treated as sacrosanct.  The app is something that is easily recreated (just by re-deploying) but the data is not (even if regularly backed up, there will likely be changes to the data since the previous backup).  It's easy enough to [delete the persistent data](https://github.com/githubsaturn/captainduckduck/wiki/Disk-Clean-Up) when you're really sure that you want to do this.

**Comment by mathiasm74** [comment]
> Hmm, surely it's a good thing that Captain leaves it to the user to decide when and how to delete the persistent data?

Sure, but currently I'm not given the choice (when deleting the app), or even informed that the data isn't deleted together with the app.

**Comment by mathiasm74** [comment]
> It's easy enough to [delete the persistent data](https://github.com/githubsaturn/captainduckduck/wiki/Disk-Clean-Up) when you're really sure that you want to do this.

The wiki text talks about running docker commands. Am I correct in thinking that this is commands that must be run on the server itself? I.e. the instructions as they are written assumes you're running docker on your local machine, or that you are logged in with ssh on the remote CDD machine? If so then this should be explicitly stated, or better yet, a feature provided through the captinduckduck cli too and/or admin web UI.

**Comment by mathiasm74** [comment]
I should mention that I came across this "problem" when I tried to delete my initial mongodb deployment specifically for the purpose of recreating it with other settings, and spent quite a while trying to figure out why I couldn't connect to it with the new username and password.

**Comment by githubsaturn** [comment]
I am not keen on deleting volumes automatically on when the app is deleted. However, a clear warning note along with commands that need to be executed would be quite useful to the first-timers.

PS:
All docker commands in the docs are to be executed on the server.

**Comment by githubsaturn** [comment]
Added details in docs and when the app is getting deleted
https://github.com/githubsaturn/captainduckduck/wiki/App-Configuration

https://github.com/githubsaturn/captainduckduck/commit/f6b1cb038db5228a34be82cb9250fbacec0fcca2#diff-bcf2f2780f380a5c98ef0a2129417b9c
