### ISSUE TITLE
[documentation] how to connect remotely to one-click mongodb instance

### ISSUE THREAD

**Issue by mathiasm74** [githubsaturn/captainduckduck#222]
Steps to reproduce:
1) Create a one-click mongodb instance
2) Try to connect to it remotely, e.g. using [Compass](https://docs.mongodb.com/compass/master/install/). This will fail.

Expected
Easy remote access to the mongodb instance, possibly with configuration UI options if needed.

**Comment by mathiasm74** [comment]
I suspect the problem to connect stems from the one-click app's nginx configuration, or the server's firewall settings, but no change to these settings that I have tried has helped.

**Comment by mathiasm74** [comment]
Found the solution to the problem [here](https://github.com/githubsaturn/captainduckduck/wiki/App-Configuration#port-mapping). Adding a port mapping to port 27017 helped (thought this was one of the things I already tried). Somehow making this clearer in the UI would be helpful.

**Comment by githubsaturn** [comment]
I thought port mapping is very clear. I can't think of a generic way for showing this in the UI. Maybe, we should change the docs so that it's easier to find out early on.

**Comment by iamrommel** [comment]
I want to help to this great project!  I want to start with documentation, where can i start @githubsaturn ?

**Comment by iamrommel** [comment]
that would be great! Please let me know, i want to contribute to this awesome project

**Comment by githubsaturn** [comment]
Added to docs, How to Connect to Databases:
https://captainduckduck.com/docs/one-click-apps.html#connecting-to-databases

PS: The new `/docs` folder is where all documents live now.

**Comment by benoib** [comment]
Hey guys, not sure that it is the right place to. But I have this exact need, and I can't figure out how to do so.

I have "my-mongo-app" (one-click Mongo db). 

It is said to be accessible here: https://my-mongo-app.server.beyondmatching.com/ on port 80.

But I do not understand what I should do to simply access the app from my local machine.

I tried
-  finding the IP of https://my-mongo-app.server.beyondmatching.com/, and use port 80.
- Mapping 27017 of my server to 80 of my container.
- Doing both ufw allow 27017/tcp, ufw allow 80 
- Use directly https://my-mongo-app.server.beyondmatching.com/ as the host.

When I test the connection, it can't even access the server.

I read the documentation but I must be missing a step there,  despite my simple usecase.

Thanks :)
