### ISSUE TITLE
Enable (or clarify) HTTPS/SSL support for external access to one-click MongoDB "app"

### ISSUE THREAD

**Issue by mathiasm74** [githubsaturn/captainduckduck#223]
After creating a one-click mongodb app, the CDD web interface seems to indicate that HTTPS/SSL can be enabled for accessing the database remotely, but this does not appear to be the case, or?

**Comment by mathiasm74** [comment]
If enabling HTTPS is not the same thing as enabling SSL, and this cannot be added for some non-web apps, then the UI should reflect this. Ideally CDD should support enabling SSL support for MongoDB one-click apps.

**Comment by githubsaturn** [comment]
> After creating a one-click mongodb app, the CDD web interface seems to indicate that HTTPS/SSL can be enabled for accessing the database remotely

This is not true. After creating a one-click mongodb app, Captain automatically checks the box for DO NOT EXPOSE AS WEB APP:
![image](https://user-images.githubusercontent.com/10582082/38593441-33398136-3cf6-11e8-9096-1a73871114e9.png)

which hides the option for HTTPS. However, you can manually remove the checkbox, in that case, you'll see the option to enable HTTPS. The reason behind having this "available" as an option to the user is that Captain is completely app agnostic - meaning that it knows next to zero about a specific app. Image MongoDB, by default, had a port 80 binding for HTTP access. In that case, simply by enabling HTTPS, you would have enabled HTTPS for the HTTP access.
