### ISSUE TITLE
https / ssl error on local server with same domain outside/inside

### ISSUE THREAD

**Issue by bilicio** [githubsaturn/captainduckduck#224]
What is the problem?
I cant activate https.
I build a local ubuntu/docker server and installed the captains script.
Then i build a dns server to resolve my hostname and point directly to the docker.
All running fine, the problem is that i cannot enable http/ssl to the server. do you know why?
I can access the domain inside the lan and outside with no problem at all. 
the log error is:

× Enabling SSL...
Something bad happened. Cannot connect to "http://captain.node.antido.to/api/v1/user/system/enablessl/"
{
  "statusCode": 500,
  "body": "Internal Server Error",
  "headers": {
    "server": "nginx/1.13.12",
    "date": "Thu, 12 Apr 2018 23:07:48 GMT",
    "content-type": "text/plain; charset=utf-8",
    "content-length": "21",
    "connection": "close",
    "x-powered-by": "Express",
    "etag": "W/\"15-/6VXivhc2MKdLfIkLcUE47K6aH0\""
  },
  "request": {
    "uri": {
      "protocol": "http:",
      "slashes": true,
      "auth": null,
      "host": "captain.node.antido.to",
      "port": 80,
      "hostname": "captain.node.antido.to",
      "hash": null,
      "search": null,
      "query": null,
      "pathname": "/api/v1/user/system/enablessl/",
      "path": "/api/v1/user/system/enablessl/",
      "href": "http://captain.node.antido.to/api/v1/user/system/enablessl/"
    },
    "method": "POST",
    "headers": {
      "x-namespace": "captain",
      "x-captain-auth": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Im5hbWVzcGFjZSI6ImNhcHRhaW4iLCJ0b2tl
blZlcnNpb24iOiI1ZmEyYzhjMC0zY2E3LTQ5MmYtYWZmOS0xYTY2YjU2MjFlYTEifSwiaWF0IjoxNTIzNTc0NDU1LCJleHAiOjE1NTk1NzQ0NT
V9.vUsENPfhuha4vlHtszb3zWe4gQSg3ygjCWBwDR8ae2k",
      "content-type": "application/x-www-form-urlencoded",
      "content-length": 45
    }
  }
}

Steps to reproduce the problem:

Answers to the following questions where applicable:
- Your OS and version?
Ubuntu 16.04.04/ docker 17.06
- RAM?
2bg

thank you!

**Comment by githubsaturn** [comment]
Captain uses LetsEncrypt to provide SSL certificates. If you are running a local DNS server, you cannot enable SSL. Your server needs to be publicly accessible via the captain domain (from Let's Encrypt servers).

For local testing, you can still use captain, but you shouldn't enable SSL. Don't use `captainduckduck setversetup` command. Instead, use the web dashboard to perform setup and use `captainduckduck login` to login to your server.

**Comment by bilicio** [comment]
Thank you! but my address is  publicly accessible from everywhere outrside my company with the same address on local you can tryit "captain.node.antido.to", even then I can not enable https.

**Comment by bilicio** [comment]
Im insisting in ssl because im using an extension (qrcode on browser) that needs to run on https servers and i can not test the application.

**Comment by bilicio** [comment]
do you have any solution to enable ssl on local? or why i can make this work even accessing my domain from outside? thank you!

**Comment by githubsaturn** [comment]
I am confused. You said you set up your local DNS server. If your address is publicly available, why do you need a local DNS?

Anyways, if your address is publicly accessible, SSL should work. To find out what's happening, let's do the following:
- Login to your web dashboard
- At the same time, on your (local) server and run `docker service logs captain-captain --since 5m --follow`
- Go back to your browser and on the Captain web dashboard click on "Enable HTTPS"
- Copy and paste the logs from the logs here so that we can find out what's happening.

Also, run `docker service ls` and copy&paste output here.

**Comment by bilicio** [comment]
I got it Kasra, on the log it said to me that i was using a different email, when i try now with the email i was previously used it goes!. The problem now is that the certificate was show as not valid for the chrome. so, i will try to generate one on my machine to use a local certificate. How do i set captain to use my certificate instead of the letsencrypt?  

By the away, Im building a server that will work online and offline. so if the connection drops i still use the local docker/ubuntu server. 

thank you for help me out! :+1:
