### ISSUE TITLE
Django static files not being served

### ISSUE THREAD

**Issue by jialutu** [githubsaturn/captainduckduck#225]
Hi, recently I've been finding that my django web app is not serving static files, where everything else is working as expected. My captain file is as follows:

```
{
  "schemaVersion" :1 ,
  "dockerfileLines" :[
        "FROM python:3.6.5-alpine3.7",
        "RUN apk update",
        "RUN apk add --no-cache mariadb-dev mariadb-client mariadb-libs gcc libc-dev unixodbc-dev",
        "RUN mkdir -p /var/www/mysite",
        "WORKDIR /var/www/mysite",
        "COPY ./src /var/www/mysite",
        "RUN pip3 install --no-cache-dir -r requirements.txt",
        "RUN apk del gcc libc-dev unixodbc-dev",
        "RUN python3 manage.py collectstatic --noinput",
        "EXPOSE 80",
        "CMD [\"gunicorn\", \"-b\", \"0.0.0.0:80\", \"mysite.wsgi\"]"
  ]
}
```

So the docker container on my local machine works when I build and deploy it, with everything served as expected. One of the things I could potentially do is to put the static files and serve it directly from the nginx container, although I'd rather not do that.

Another thing is that this problem only started ocurring recently and also the static files from my node projects are being served as expected. 

Thanks in advance.

**Comment by githubsaturn** [comment]
What's the path that you have in your Django app to serve your static files on your local machine? Is it relative or absolute? Something like `/var/www/mysite/staticfiles`

**Comment by jialutu** [comment]
The path is a relative path in the location `/var/www/mysite/main/static`. Although there is a same file in the path `/var/www/mysite/static`, which is also not served.

**Comment by githubsaturn** [comment]
If the problem is only on static files, the only problem is the path. The request is making it through to the Django app, it's the Django app that cannot find the static file. 

If you can reproduce the issue using a hello work Django, I can look into it. It shouldn't be too hard to track down.

**Comment by jialutu** [comment]
After some digging around, it turned out the issue was due to a problem in django. The difference between the docker build and what I deployed to captainduckduck had a minor difference, hence the different result. The issue has been fixed now, sorry for the inconvenience caused and thanks for the help.

**Comment by bunya017** [comment]
> 
> 
> After some digging around, it turned out the issue was due to a problem in django. The difference between the docker build and what I deployed to captainduckduck had a minor difference, hence the different result. The issue has been fixed now, sorry for the inconvenience caused and thanks for the help.

Hello,

can you please show how you fixed this? I'm facing this issue too.

**Comment by bunya017** [comment]
Fortunately , I found the fix. One need to configure `STATICFILES_STORAGE` using the python package:
`whitenoise`. I followed the [quick start guide](http://whitenoise.evans.io/en/stable/#quickstart-for-django-apps) and it worked!!!

**Comment by ProfessorLogout** [comment]
@bunya017 
You may also refer to the django community sample provided in the documentation.
https://caprover.com/docs/sample-apps.html
Happy to help if there is anything unclear with the sample app

**Comment by bunya017** [comment]
@ProfessorLogout 
I did, then ran into this problem. I found the solution minutes after my first comment, so I posted it 
 the solution here since OP did not post his.
Thanks

**Comment by bunya017** [comment]
> 
> 
> @bunya017
> You may also refer to the django community sample provided in the documentation.
> https://caprover.com/docs/sample-apps.html
> Happy to help if there is anything unclear with the sample app

@ProfessorLogout 
How do I setup media root and media url?

**Comment by naveencom** [comment]
@bunya017 I am facing the same problem. Can you please share a sample of your settings file?

**Comment by bunya017** [comment]
> Fortunately , I found the fix. One need to configure `STATICFILES_STORAGE` using the python package:
> `whitenoise`. I followed their [quick start guide](http://whitenoise.evans.io/en/stable/#quickstart-for-django-apps) and it worked!!!

@naveencom kindly see the comment above.

**Comment by naveencom** [comment]
@bunya017 I saw that. It's not working.

Would be helpful if you show me your settings, captain-definition etc.

**Comment by bunya017** [comment]
> @bunya017 I saw that. It's not working.
> 
> Would be helpful if you show me your settings, captain-definition etc.

check this repo [galleria](https://github.com/bunya017/galleria)

**Comment by naveencom** [comment]
@bunya017 Thanks man. I'll looking into it.

Are you using Caprover in production?

**Comment by bunya017** [comment]
> @bunya017 Thanks man. I'll looking into it.
> 
> Are you using Caprover in production?

you're welcome...

not right now. But I have used it in production, and it didn't disappoint

**Comment by naveencom** [comment]
@bunya017 Ok, I have made my app run.

How do we run Django management commands on our app?

I'm completely new to server/hosting.

**Comment by bunya017** [comment]
> @bunya017 Ok, I have made my app run.
> 
> How do we run Django management commands on our app?
> 
> I'm completely new to server/hosting.

do you want to execute the commands at deployment time or while the app is actively running?

**Comment by naveencom** [comment]
@bunya017 I want to execute "python manage.py createsuperuser" or similar like custom commands.

**Comment by bunya017** [comment]
> @bunya017 I want to execute "python manage.py createsuperuser" or similar like custom commands.

You'll have to ssh into your VPS, then ssh into your app, and run the command.

According to [this link](https://caprover.com/docs/troubleshooting.html#how-to-run-shell-inside-my-application-inside-container), you should run this command to get shell access into your app:
`docker exec -it $(docker ps --filter name=srv-captain--myappname -q) /bin/sh`
Replace `myappname` with your app's name

**Comment by naveencom** [comment]
@bunya017 Thanks man, it worked.

**Comment by naveencom** [comment]
@bunya017 I deployed a one-click Postgres.

`Your app is internally available as srv-captain--postgres to other Captain apps. In case of web-app, it is accessible via http://srv-captain--postgres from other apps.`

```
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "database_name",
        "USER": "postgres",
        "PASSWORD": "password_goes_here",
        "HOST": "srv-captain--postgres",
        "PORT": "5432",
        "CONN_MAX_AGE": 0,
        "CONN_HEALTH_CHECKS": True,
    }
}
```
My Django app is not connecting with this database. 

Any idea?

**Comment by bunya017** [comment]
> @bunya017 I deployed a one-click Postgres.
> 
> `Your app is internally available as srv-captain--postgres to other Captain apps. In case of web-app, it is accessible via http://srv-captain--postgres from other apps.`
> 
> ```
> DATABASES = {
>     "default": {
>         "ENGINE": "django.db.backends.postgresql",
>         "NAME": "database_name",
>         "USER": "postgres",
>         "PASSWORD": "password_goes_here",
>         "HOST": "srv-captain--postgres",
>         "PORT": "5432",
>         "CONN_MAX_AGE": 0,
>         "CONN_HEALTH_CHECKS": True,
>     }
> }
> ```
> 
> My Django app is not connecting with this database.
> 
> Any idea?

what's the error?

**Comment by naveencom** [comment]
@bunya017 

  ```
 all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/checks/registry.py", line 88, in run_checks

    new_errors = check(app_configs=app_configs, databases=databases)

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/checks/model_checks.py", line 36, in check_all_models

    errors.extend(model.check(**kwargs))

                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 1622, in check

    *cls._check_constraints(databases),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 2472, in _check_constraints

    connection.features.supports_nulls_distinct_unique_constraints

  File "/usr/local/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)

                                         ^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/postgresql/features.py", line 141, in is_postgresql_15

    return self.connection.pg_version >= 150000

           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__

    res = instance.__dict__[self.name] = self.func(instance)

                                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 438, in pg_version

    with self.temporary_connection():
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__

    return next(self.gen)

           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 691, in temporary_connection

    with self.cursor() as cursor:

         ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 316, in cursor

    return self._cursor()

           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 292, in _cursor

    self.ensure_connection()

  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 274, in ensure_connection

    with self.wrap_database_errors:
  File "/usr/local/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 275, in ensure_connection

    self.connect()
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/base/base.py", line 256, in connect

    self.connection = self.get_new_connection(conn_params)

                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner

    return func(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 277, in get_new_connection

    connection = self.Database.connect(**conn_params)

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/psycopg/connection.py", line 98, in connect
    attempts = conninfo_attempts(params)

               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg/_conninfo_attempts.py", line 50, in conninfo_attempts

    raise e.OperationalError(str(last_exc))

django.db.utils.OperationalError: [Errno -2] Name or service not known

{"code":1,"message":"The command '/bin/sh -c python manage.py migrate' returned a non-zero code: 1"}
The command '/bin/sh -c python manage.py migrate' returned a non-zero code: 1
Build has failed!
----------------------
Deploy failed!
Error: {"code":1,"message":"The command '/bin/sh -c python manage.py migrate' returned a non-zero code: 1"}
The command '/bin/sh -c python manage.py migrate' returned a non-zero code: 1
```

**Comment by bunya017** [comment]
Did you create a db on your Caprover instance? If yes and your db url is `srv-captain--postgres`, then you should prepend `http://` to the `HOSTNAME, your new db config will be like this:
```python
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "database_name",
        "USER": "postgres",
        "PASSWORD": "password_goes_here",
        "HOST": "http://srv-captain--postgres", # Take note of this
        "PORT": "5432",
        "CONN_MAX_AGE": 0,
        "CONN_HEALTH_CHECKS": True,
    }
}
```

**Comment by naveencom** [comment]
> Did you create a db on your Caprover instance? If yes and your db url is `srv-captain--postgres`, then you should prepend `http://` to the `HOSTNAME, your new db config will be like this:
> 
> ```python
> DATABASES = {
>     "default": {
>         "ENGINE": "django.db.backends.postgresql",
>         "NAME": "database_name",
>         "USER": "postgres",
>         "PASSWORD": "password_goes_here",
>         "HOST": "http://srv-captain--postgres", # Take note of this
>         "PORT": "5432",
>         "CONN_MAX_AGE": 0,
>         "CONN_HEALTH_CHECKS": True,
>     }
> }
> ```

I tried that. It didn't work.

**Comment by bunya017** [comment]
> > Did you create a db on your Caprover instance? If yes and your db url is `srv-captain--postgres`, then you should prepend `http://` to the `HOSTNAME, your new db config will be like this:
> > ```python
> > DATABASES = {
> >     "default": {
> >         "ENGINE": "django.db.backends.postgresql",
> >         "NAME": "database_name",
> >         "USER": "postgres",
> >         "PASSWORD": "password_goes_here",
> >         "HOST": "http://srv-captain--postgres", # Take note of this
> >         "PORT": "5432",
> >         "CONN_MAX_AGE": 0,
> >         "CONN_HEALTH_CHECKS": True,
> >     }
> > }
> > ```
> 
> I tried that. It didn't work.

Does your migration work locally?

**Comment by naveencom** [comment]
@bunya017 Yes, it works fine. 

My Django app is able to connect with the DB through the port mapping feature of Caprover. I had done migrations this way.
