### ISSUE TITLE
custom domains for up

### ISSUE THREAD

**Issue by tvardy** [githubsaturn/captainduckduck#227]
It would be nice to be able to set a custom domain for whichever app I create instead of having automatic subdomains.

e.g.
- captain's dashboard -> captain.my-domain.com
- my main website -> my-domain.com
- my clients app -> clients-domain.com
- my side project -> some-free-domain-at-dot.tk

**Comment by githubsaturn** [comment]
Custom domains are supported. Just go to your app and click on a custom domain! 

Make sure you have your DNS records for the desired domain pointed to the server ip address.

**Comment by tvardy** [comment]
Good to know! Pity I couldn't find it in docs and previously decided not to run a test app. I will now ;)
