### ISSUE TITLE
unable to add an app in domain.com ( instead of app.mydomain.com )

### ISSUE THREAD

**Issue by Abh009** [githubsaturn/captainduckduck#228]
I am unable to add an app in domain.com
Even though  I have added an app like app.domain.com

**Comment by githubsaturn** [comment]
I just re-tested this. It works fine. You are probably using a subdomain. For example, if your app sits at `app.domain.com` you cannot use `www.domain.com`. However, you can use `domain.com`. For `www`, you can create an app whose name is `www`, you can also forward your `domain.com` to this `www` app as well.

**Comment by githubsaturn** [comment]
Make sure you're using the latest version. `Latest Stable Version: 0.6.0`
