### ISSUE TITLE
NetData is unstable

### ISSUE THREAD

**Issue by scott-laursen** [githubsaturn/captainduckduck#231]
NetData is a great addition to CaptainDuckDuck. Unfortunately it works less than optimally for me, and everytime I load it I get a bunch of errors.

Initially I will usually get an error trying to load the `bootstrap-3.3.7.min.js` file, then the `dygraph-combined-dd74404.js` file, after that alarms and data calls will randomly fail. However it is not entirely consistent and sometimes the javascript files will download but the alarms and data calls still randomly fail.

![image](https://user-images.githubusercontent.com/1535859/39406876-0b655500-4bbe-11e8-90cc-690e1d5fb88d.png)

After a few reloads I am usually able to see the NetData system but I will see the graphs pop in and out as shown in the image below:

![image](https://user-images.githubusercontent.com/1535859/39406874-ea09940c-4bbd-11e8-9c0c-5306530ae717.png)

The error returned in the requests are always "Something went wrong..." so not very helpful. The log from the captain container only shows me the status of the request and not what went wrong.

In the console I get the following types of error, the two first does not always show up:

```
ERROR 405: Cannot download charts index from server: https://<myserver>/net-data-monitor/api/v1/charts
ERROR 407: Cannot HELLO netdata server: https://<myserver>/net-data-monitor
ERROR 415: Netdata alarms download failed: https://<myserver>/net-data-monitor
```

Finally let me say CaptainDuckDuck is amazing! Well thought out and overall very easy to work with. Thank you.

**Comment by githubsaturn** [comment]
`Something went wrong` shows up when the connection between the NetData container and CaptainDuckDuck. 

I haven't seen any report of this inconsistency happening in the wild. But anyways, I added some logs so that the users are able to troubleshoot what's happening: https://github.com/githubsaturn/captainduckduck/commit/ab4f600bcfd670e93446a7e80ff00ed17cae2e46

Will be released in 0.7.0
