### ISSUE TITLE
Fail to install WordPress by One-Click app

### ISSUE THREAD

**Issue by ngvntoan** [githubsaturn/captainduckduck#233]
Dear @githubsaturn,

First thing, I  want to say thanks so much for your amazing tool. It's help me a lot. 
The second, I have problems with setup WordPress via One-Click app. I do exactly with your tutorial (https://www.youtube.com/watch?v=576RsaocNUE and https://www.youtube.com/watch?v=XDrTmGSDW3s), but it's still get 502 Bad Gateway when clicking on my WordPress URL: http://blog.admin.[mydomain].com (i have been waiting for long time, more than 15 minutes) after install success. I have try to create another app with several times, but the result is the same, still 502 :((

![image](https://user-images.githubusercontent.com/28523050/39468611-1e99c0ba-4d5e-11e8-87c9-6982210f54e3.png)

![image](https://user-images.githubusercontent.com/28523050/39468419-161d67f8-4d5d-11e8-94c3-b2873007aa0e.png)

![image](https://user-images.githubusercontent.com/28523050/39468605-100f9dc6-4d5e-11e8-9c7c-52976827114b.png)

Could you please help me resolve this issuse?

Thanks,
Toan

**Comment by githubsaturn** [comment]
502 means the container failed to start up. Can you try these resolutions:

- Restart your server (`sudo reboot`), wait a few minutes, if this didn't fix, proceed to the next:
- Remove your SQL and WordPress apps (both of them) and create a new WordPress app with *a different name* like `myblog`. Wait a few minutes, if this didn't fix, proceed to the next:
- If none of these solved the issue, SSH to your server and captain logs of your WordPress app and copy it here so we can identify the issue. To capture logs, run `docker service logs srv-captain--myblog`
See https://github.com/githubsaturn/captainduckduck/wiki/Troubleshooting#how-to-view-my-applications-log

**Comment by ngvntoan** [comment]
I have tried reboot & create another WordPress app, but can't fix this issue :((

Here is my logs:

> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | Warning: mysqli::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | Warning: mysqli::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | Warning: mysqli::__construct(): (HY000/2054): The server requested authentication method unknown to the client in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | Warning: mysqli::__construct(): (HY000/2054): The server requested authentication method unknown to the client in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | MySQL Connection Error: (2054) The server requested authentication method unknown to the client
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | MySQL Connection Error: (2054) The server requested authentication method unknown to the client
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | Warning: mysqli::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | Warning: mysqli::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | Warning: mysqli::__construct(): (HY000/2054): The server requested authentication method unknown to the client in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | Warning: mysqli::__construct(): (HY000/2054): The server requested authentication method unknown to the client in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | MySQL Connection Error: (2054) The server requested authentication method unknown to the client
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | MySQL Connection Error: (2054) The server requested authentication method unknown to the client
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | Warning: mysqli::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | Warning: mysqli::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | Warning: mysqli::__construct(): (HY000/2054): The server requested authentication method unknown to the client in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | Warning: mysqli::__construct(): (HY000/2054): The server requested authentication method unknown to the client in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | MySQL Connection Error: (2054) The server requested authentication method unknown to the client
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | MySQL Connection Error: (2054) The server requested authentication method unknown to the client
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | Warning: mysqli::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | Warning: mysqli::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | Warning: mysqli::__construct(): (HY000/2054): The server requested authentication method unknown to the client in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | Warning: mysqli::__construct(): (HY000/2054): The server requested authentication method unknown to the client in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | MySQL Connection Error: (2054) The server requested authentication method unknown to the client
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | MySQL Connection Error: (2054) The server requested authentication method unknown to the client
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | Warning: mysqli::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | Warning: mysqli::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | Warning: mysqli::__construct(): (HY000/2054): The server requested authentication method unknown to the client in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | Warning: mysqli::__construct(): (HY000/2054): The server requested authentication method unknown to the client in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | MySQL Connection Error: (2054) The server requested authentication method unknown to the client
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | MySQL Connection Error: (2054) The server requested authentication method unknown to the client
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | Warning: mysqli::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | Warning: mysqli::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | Warning: mysqli::__construct(): (HY000/2054): The server requested authentication method unknown to the client in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | Warning: mysqli::__construct(): (HY000/2054): The server requested authentication method unknown to the client in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | MySQL Connection Error: (2054) The server requested authentication method unknown to the client
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | MySQL Connection Error: (2054) The server requested authentication method unknown to the client
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | Warning: mysqli::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | Warning: mysqli::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in Standard input code on line 22
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | Warning: mysqli::__construct(): (HY000/2054): The server requested authentication method unknown to the client in Standard input code on line 22
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | Warning: mysqli::__construct(): (HY000/2054): The server requested authentication method unknown to the client in Standard input code on line 22
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | MySQL Connection Error: (2054) The server requested authentication method unknown to the client
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | MySQL Connection Error: (2054) The server requested authentication method unknown to the client
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | Warning: mysqli::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in Standard input code on line 22
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | Warning: mysqli::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in Standard input code on line 22
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | Warning: mysqli::__construct(): (HY000/2054): The server requested authentication method unknown to the client in Standard input code on line 22
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | Warning: mysqli::__construct(): (HY000/2054): The server requested authentication method unknown to the client in Standard input code on line 22
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | MySQL Connection Error: (2054) The server requested authentication method unknown to the client
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | MySQL Connection Error: (2054) The server requested authentication method unknown to the client
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | Warning: mysqli::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in Standard input code on line 22
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | Warning: mysqli::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in Standard input code on line 22
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | Warning: mysqli::__construct(): (HY000/2054): The server requested authentication method unknown to the client in Standard input code on line 22
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | Warning: mysqli::__construct(): (HY000/2054): The server requested authentication method unknown to the client in Standard input code on line 22
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    |
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | MySQL Connection Error: (2054) The server requested authentication method unknown to the client
> srv-captain--blog.1.px8gzrp9lyoi@toan-server    | MySQL Connection Error: (2054) The server requested authentication method unknown to the client
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | Warning: mysqli::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | Warning: mysqli::__construct(): (HY000/2054): The server requested authentication method unknown to the client in Standard input code on line 22
> srv-captain--blog.1.z76a73mo7a6d@toan-server    |
> srv-captain--blog.1.z76a73mo7a6d@toan-server    | MySQL Connection Error: (2054) The server requested authentication method unknown to the client
>

**Comment by ngvntoan** [comment]
I think there are problems with new MySQL version.
https://github.com/laradock/laradock/issues/1392
Hope you can find the way to fix it soon!

**Comment by githubsaturn** [comment]
CaptainDuckDuck automatically uses the latest versions of all containers for one-click apps. See:
https://github.com/githubsaturn/captainduckduck/blob/master/app-frontend/src/oneclick-apps/wordpress.js#L119
and
https://github.com/githubsaturn/captainduckduck/blob/master/app-frontend/src/oneclick-apps/wordpress.js#L186

But obviously here, the latest version of WordPress and/or MySql is broken. I am sure they'll fix the issue soon, but just to be completed, I'll add the custom versions to the next release of CaptainDuckDuck so that the user can select which version they want to use just in case the latest version of a particular app is not working.

The new feature will be part of v0.7.0 which will be released next week.

**Comment by iamrommel** [comment]
>   I'll add the custom versions to the next release of CaptainDuckDuck so that the user can select which version they want to use just in case the latest version of a particular app is not working.

These is good feature, in my case, i want to deploy mongo 3.4, see #190,   (which is not tagged as the latest from docker hub). I was able to resolved my issue by following your comment to create just a docker-definition and pulling from correct docker-hub version. But deploying from specific dockerhub tag is  good feature!

**Comment by githubsaturn** [comment]
Ability to add specific tags added in https://github.com/githubsaturn/captainduckduck/commit/07a3cf3960eb512eba524821e669a913269d0f88

Will be released in v0.7 in the upcoming week.
