### ISSUE TITLE
Disable apps

### ISSUE THREAD

**Issue by LouieK22** [githubsaturn/captainduckduck#235]
Sometimes I would like to disable an app for a period of time to save resources. However, I may not want to delete the app from captain.

**Comment by LouieK22** [comment]
This is an app with persistent data, so I cannot set the instance count to 0.

**Comment by githubsaturn** [comment]
You can still do the same via command line. Just ssh to your server and run:
```
docker service scale srv-captain--yourappname=0
```

when you want to enable your app, simply go to the web dashboard and click on Save & Update Configuration button. It will restart your app.

**Comment by LouieK22** [comment]
This feels more like a workaround than a fix. I can see this as being an issue for future users.

**Comment by githubsaturn** [comment]
It's not a workaround. It's a valid approach.

However, after seeing this issue, and a couple of other issues around instance count of persistent apps, I decided to give this opportunity to the user to change the instance count of persistent apps - provided with a warning that this could cause corrupting data.

https://github.com/githubsaturn/captainduckduck/commit/5c8cf1b601c6a97ac95585c25c86b22921ed04bd
