### ISSUE TITLE
docker service logs no longer showing any output?

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#238]
I can't really understand how it could be related, but since upgrading CDD to 0.7.1 the following is no longer showing any output:

    $ docker service logs srv-captain--myapp --since 10m --follow --timestamps --raw

The app itself is still working fine, I just can't see any logs anymore.  Any ideas?

**Comment by githubsaturn** [comment]
Nothing changed in v0.7 regarding logs. I am able to see the logs.
- Does it happen if you create a new sample app? for example, a MySQL app?
- Try rebooting your machine.
- Try another server. Can you repro the same behavior?

**Comment by drmrbrewer** [comment]
I thought it was very unlikely to have been caused by cdd.  A server reboot resolved it.  Thanks.
