### ISSUE TITLE
Build logs in console hangs without completing

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#240]
When deploying an app via the CLI, the end of the deploy process looks something like:

	---> Running in b427be6ef31w
	Removing intermediate container b427be6ef31w
	---> 6aabbbcdb64s
	Successfully built 6aabbbcdb64s
	Successfully tagged registry.myserver.mydomain.com:996/captain/img-captain--myapp:latest
	Pushing to remote: registry.myserver.mydomain.com:996/captain/img-captain--myapp:289
	Server: registry.myserver.mydomain.com:996
	This might take a few minutes...
	 
	Deployed successfully: myapp
	App is available at http://myapp.myserver.mydomain.com

But when viewing the same progress logs in the captain console, it gets to the following point:

	Pushing to remote: registry.myserver.mydomain.com:996/captain/img-captain--myapp:289
	Server: registry.myserver.mydomain.com:996
	This might take a few minutes...

And then never gets any further.  The interface is left as follows:

![image](https://user-images.githubusercontent.com/9009792/40353223-dbe559d6-5da8-11e8-8413-09d120de38eb.png)

So the build process has actually completed properly, but this isn't reflected in the console.  This is OK when you can confirm all is OK via the CLI, but when you're deploying via webhook without a CLI (which is when you need the build logs in the console most), this isn't ideal.

**Comment by githubsaturn** [comment]
Fixed and will be deployed with the next release
https://github.com/githubsaturn/captainduckduck/commit/8889f8563b864c8ade959dbe6bb620d539ccb1d4
