### ISSUE TITLE
SSL error on creating new app

### ISSUE THREAD

**Issue by aswinsatish** [githubsaturn/captainduckduck#241]
Whenever i am trying to deploy a new app in captain duck duck it is giving a SSL certificate error
ERROR 1000: Push failed: 
{"message":"Get https://registry.****.com:996/v1/_ping: x509: certificate has expired or is not yet valid"}Get https://registry.****.com:996/v1/_ping: x509: certificate has expired or is not yet valid

How do i renew the registry certificate for the same

**Comment by aswinsatish** [comment]
After restarting docker service in the CDD server, the issue was resolved

**Comment by githubsaturn** [comment]
CaptainDuckDuck automatically renew all certs. However, the Docker registry caches the old cert until a restart. This doesn't affect the user facing apps as nginx gets reloaded after renewals.
