### ISSUE TITLE
On deploy: Files are not copied over when a submodule is in the repo

### ISSUE THREAD

**Issue by funkhauscreative** [githubsaturn/captainduckduck#242]
I tried two methods to get one of our apps deployed:

1. CLI Method "captainduckduck deploy"
Build works fine, all files are there EXCEPT files in a submodule in the git I deploy

2. Web hook method
We are running our own git repo with gogs. The connection works fine. I added the POST link in the configuration of the repo in Gogh. The connection works fine. The build starts but never comes to an end. It's the same repo/captaindefintion like in method 1. I believe it has probably also something to do with the submodules in the repo?

**Comment by githubsaturn** [comment]
Yes. Submodules are pain in the back. It is possible to improve the git webhook to solve the issue. For method 1, Captain uses `git archive`, which you would think has a `--recursive` option, but it doesn't.

Anyways, I think this is some improvement that is worth doing. I'll put it on the roadmap. It should be done in about a month.

**Comment by githubsaturn** [comment]
Fixed:
- Recursive option is added to webhook (https://github.com/githubsaturn/captainduckduck/commit/83886d879560a8fb099c53e68e4fd82fc793c425) Will be available with the next release

- Option is added in order to let the user specify the tarfile to upload when deploying via CLI (already released in v1.0.15 of the CLI)

**Comment by AlejandroAkbal** [comment]
Hey, I'm trying to deploy a project which uses `git submodules`.

Unfortunately, I am unable to make it work, as `git submodules` are not fetched when pushing with the CLI.
E.g.`caprover deploy`.

I have tried to do a `git submodule update --init --recursive` in the Dockerfile, but with no luck.
It errors out with the following message:
`fatal: not a git repository (or any of the parent directories): .git`

What else can I try?

[Link to the Dockerfile](https://github.com/Rule-34/API/blob/d7a43750d064308f5007d74fb52b0ab633a06c92/Dockerfile).
