### ISSUE TITLE
Cross-Origin Read Blocking (CORB) caused by nginx proxy

### ISSUE THREAD

**Issue by aberba** [githubsaturn/captainduckduck#245]
**Problem**
(**Note**: I've changed my actually domain name)
My static site hosted on **mydomain.com** cannot make **POST** requests to server at **app.api.mydomain.com** using fetch() due to **Cross-Origin Read Blocking (CORB)**. GET seems to work alright. When I make POST request, I get this error in Chrome:

```
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://app.api.mydomain.com/core/v1/create_token with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

**Note the mime type. It gets changed to text/html by nginx proxy, I guess**

Firefox:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.api.mydomain.com/core/v1/create_token. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```
The server is a nodeJS server which sends a JSON response with res.json() but it **seems** the final Content-Type received in the browser is  `text/html` which violates [Cross-Origin Read Blocking (CORB)](https://chromium.googlesource.com/chromium/src/+/master/services/network/cross_origin_read_blocking_explainer.md). Especially when JSON response it sent with a text/html content type.

My guess it the nginx proxy modifies the response header. I've gone through the nginx config file but can't find where the issue is both in the global and app specific one. It don't really understand why the response it text/html cus its works when I host it outside captainduckduck (without a proxy).

**Comment by githubsaturn** [comment]
This is unrelated to CaptainDuckDuck. It's related to how you set your headers. For example see:
https://stackoverflow.com/questions/45611400/cross-origin-request-blocked-the-same-origin-policy-disallows-reading-the-remot

This might not exactly be the answer you're looking for. But it should give you a starting point. I suggest you post your question on StackOverflow and tag it with `nodejs` and `CORS`

**Comment by aberba** [comment]
I've already have cors setup. Read my issue again cus I'm not looking for how to setup cors. Nginx seems to be changing the headers going through it.

**Comment by githubsaturn** [comment]
No, default nginx config via CaptainDuckDuck does not add/modify any headers to the response. It only add some headers to the proxy request (not the response), which are here:
https://github.com/githubsaturn/captainduckduck/blob/master/app-backend/src/template/server-block-conf.ejs#L57

Therefore, if you have set headers in your nodejs app, you will see those headers getting passed to the client. 

Also, if you need to modify any default nginx property for a specific need, you can always edit the default one by going to the Captain's control panel, your app's settings and add any headers you want, for example, you can add the following lines:
```

**Comment by githubsaturn** [comment]
To debug your app, just open chrome dev console, and you will see the OPTIONS request that goes out before the POST request. You will see whether or not it has the right access control headers or not.

My guess is in your source code you are not setting the headers on POST requests.

**Comment by aberba** [comment]
I tried everything on earth but it doesn't work. Upon second guess, I used **two separate** letencrypt certificated for the same domain in both front-end and back-end. My guess it the CORB algorithm detects that as a violation cus my app works on heroku just fine.

**Comment by githubsaturn** [comment]
Try posting your question in the telegram channel. Maybe other people will be able to help:
https://github.com/githubsaturn/captainduckduck/issues/49

You can also post your domains here and i can have a look at it.

**Comment by hamza-younas94** [comment]
i got the cors problem i added cors in ngninx conf in my php ngingx but it doesn't work then i copied [#245](https://github.com/caprover/caprover/issues/245#issuecomment-396386302) add in Application nginx configuration its worked
