### ISSUE TITLE
Can captain duck duck be used without domain name?

### ISSUE THREAD

**Issue by xinyuewang1** [githubsaturn/captainduckduck#246]
Hi, I know you said in the first line of Prerequisites that we need a domain name, we're working on a school project that compulsory to stored on school server which we cannot get the authority to modify the DNS.
Is there a way around it cause we reeaaally like captain duck duck.

Thanks for your brilliant work!

**Comment by githubsaturn** [comment]
Yes, you can. But it won't be as easy as the standard settings. To do:

### if your server has a public IP address and you have root access:
- Ensure firewalls are disabled for port 80, 443, 3000 and these ports: https://captainduckduck.com/docs/firewall.html
- Install CaptainDuckDuck using ` mkdir /captain && docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock dockersaturn/captainduckduck`
- Now login to captainduckduck from http://<IP-ADDRESS-OF-SERVER>:3000 and change the password from the settings page.
- Go to app's page and create a new app.
- Go to your local machine and install captainduckduck npm client.
- Use `captainduckduck login` and login to server, when it asks for server URL, enter: `http://<IP-ADDRESS-OF-SERVER>:3000`
- Use `captainduckduck deploy` to deploy your app.
- To see the app, go to app's settings and map port `1234` from host to port `80` of container. 
- Now go to  http://<IP-ADDRESS-OF-SERVER>:1234 and see your app!
- After every deploy you have to go to app's settings and click on Save Configuration and Update in order for the port to remap.

### If your server does not have a direct public IP address:
Read this tutorial, but beware that it will be complicated and not straightforward for beginners.
https://captainduckduck.com/docs/run-locally.html

**Comment by iamareebjamal** [comment]
Hello, I tried this but seems like port 3000 is not being exposed on the host and hence cannot access the dashboard

**Comment by Ashar2shahid** [comment]
there is option to deploy locally in the the updated version of captain duck duck , [https://caprover.com/docs/run-locally.html](CapRover)
