### ISSUE TITLE
Port time out Issue

### ISSUE THREAD

**Issue by xinyuewang1** [githubsaturn/captainduckduck#247]
Hi, Thanks for you marvellous work!
I got this when I tried to install Captain duck duck on my EC2.

error message:
Installation failed.
Error: Port timed out: 80
    at Timeout._onTimeout (/usr/src/app/src/utils/CaptainInstaller.js:155:20)
    at ontimeout (timers.js:471:11)
    at tryOnTimeout (timers.js:306:5)
    at Timer.listOnTimeout (timers.js:266:5)

I looked at docker ps, no containers.
also nothing in /captain/ folder.
Really running out of ideas, can you offer some advice? Thanks a lot.

**Comment by githubsaturn** [comment]
You have to disable the firewall. 

Run `ufw disable` if you're using Ubuntu.

**Comment by xinyuewang1** [comment]
Aye, I forgot to mention I disabled it, and I checked it with sudo ufw status, it's disabled.

**Comment by xinyuewang1** [comment]
Any other thoughts can lead to this error?

**Comment by githubsaturn** [comment]
Try this:
docker run -p 80:80 nginx


Then go to http://<IP-ADDRSSS>


Does this work?

**Comment by xinyuewang1** [comment]
Thanks for the advice, I tried it.
after run `docker run -p 80:80 nginx` it will keep running in the foreground
then i checked  ip:3000, it says This site can’t be reached.
Any other thoughts?

**Comment by githubsaturn** [comment]
Of course IP:3000 won't work. After running nginx, try IP:80

Does this work? If this doesn't work then the issue is firewall. I haven't worked with AWS recently. But maybe they have a separate firewall in the dashboard?

Anyways if a simole nginx at port 80 doesn't work, then the issue is some sort of firewall. It's the simplest setup.

**Comment by xinyuewang1** [comment]
Thanks for the advice, so it turns out not working anyway.
Could be EC2 trying to give us a hard time.
Thanks anyway for all your time and suggestions.

**Comment by EdgarPatron** [comment]
I have teh same problem on Ubuntu running on VirtualBox

**Comment by Kalacione** [comment]
Hi there,

I tried `docker run -p 80:80 nginx` and sucessfully got nginx welcome page working.

**With install script :**
`docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock dockersaturn/captainduckduck`

got this error :

```
Installation failed.
Error: Port seems to be closed: 80
    at Request._callback (/usr/src/app/src/utils/CaptainInstaller.js:172:24)
    at self.callback (/usr/src/app/node_modules/request/request.js:185:22)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.onRequestError (/usr/src/app/node_modules/request/request.js:881:8)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketErrorListener (_http_client.js:385:9)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
npm info lifecycle captain-duckduck@0.0.0~poststart: captain-duckduck@0.0.0
npm info ok
```

**Env Setup :**
Virtualbox
Bridged Network
Ubuntu 18.4 
Docker 18.06.1
UFW disabled
Fresh install  (no application running blocking any port)

Sucessfully tested with DigitalOcean

Great Job BTW 🥇

**Comment by githubsaturn** [comment]
@Kalacione 

CaptainDuckDuck is designed for servers. Running on VMs requires some advanced settings.


Try this:

```
docker run -e MAIN_NODE_IP_ADDRESS='192.192.192.192' -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock dockersaturn/captainduckduck
```

Replace `192.192.192.192` with your VM ip address. If this doesn't work, try adding `BY_PASS_PROXY_CHECK='TRUE' `, i.e.:

```
docker run -e BY_PASS_PROXY_CHECK='TRUE' -e MAIN_NODE_IP_ADDRESS='192.192.192.192' -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock dockersaturn/captainduckduck
```

**Comment by vishesh0077** [comment]
Thanks a lot @githubsaturn it actually works
