### ISSUE TITLE
Container hostname (like -h flag)

### ISSUE THREAD

**Issue by enricodeleo** [githubsaturn/captainduckduck#250]
I'm trying to deploy a https://poste.io instance in order to get a full-featured mail server on captainduckduck (seems great, isn't it?). 

Apparently, everything should work (once all the port and volumes mappings are done) but the image doesn't bind to the external (nor the internal srv-captain--**) hostname. I think this is because the image doesn't start with the required -h flag. Is there any way to tell captainduckduck to do so? I could start it manually via shell but I would really like to keep everything under captainduckduck :)

Thanks for any hint!

**Comment by githubsaturn** [comment]
What do you mean when you say it doesn't bind?

I see a couple of issues with this images as per their docs: https://poste.io/doc/

- It's fully managed container, i.e., it has nginx and Let's Encrypt built-in. This conflicts with Captain.
- It is hijacking port 80 and 443 which are managed by Captain.

To make this work with CaptainDuckDuck, take the following steps:
- Create a new app on Captain, like `myemailapp` with persistent data
- Set all env vars and volumes as per poste docs, except PORT 80 and PORT 443. Save and update.
- Next, SSH to your server and run `docker service update --host myemailapp.domain.com srv-captain--myemailapp` (of course, replace domain.com with your Captain root domain). Captain does not mess with data that it does not manage, `host` is one of them.
- Create a simple captain-definition file with one line in` dockerFileLines: "FROM analogic/poste.io"` and deploy this file as a tar file via web dashboard


I haven't tested this flow, but it's my best guess to make things work. Notice that you have to do things in order as I explained. Hopefully it'll solve your issue.

**Comment by enricodeleo** [comment]
**THANKYOU** @githubsaturn I've been able to get into the app now. I had already done everything you suggested but I didn't know about `docker service update` command. It was exactly what I was seaching for!
