### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by vbrandl** [githubsaturn/captainduckduck#26]
I tried deploying a Rust hello-world application using captainduckduck and somehow messed up my configuration.
The commandline client responded with
```
{
  "status": 1109,
  "description": "The command '/bin/sh -c cargo build --release' returned a non-zero code: 101"
}
```
It would be nice if the client would also print the output, the command generated. That would make debugging way easier.

**Comment by githubsaturn** [comment]
Unfortunately, this is the only line that is flagged as error in console. I'll have to have a sudo hacky way to improve this. I'll add last few lines of logs to error message even if they are logged as regular output not error. Stay tuned.

**Comment by githubsaturn** [comment]
v0.3 deployed. Make sure you update your CLI as well (`npm i -g captainduckduck`), latest CLI version `1.0.7`
