### ISSUE TITLE
CLI Deploy Issue - Can't make app space from CLI

### ISSUE THREAD

**Issue by thinnker** [githubsaturn/captainduckduck#261]
Hi,

Firstly, your work on this is great, well done on the excellent project.

PROBLEM:
I have managed to get the Captain Dashboard live, and I have successfully deployed your test apps via the Web Interface, and it's great... all working.
Once I try to do a Deploy via CLI with your extracted code into a **new app namespace** for example "test-node-2", then it runs, and dies with a **error code:**
`Something bad happened. Cannot deploy "test-node-2"

Error code: 1000

Error message:

 App not found: test-node-2! Make sure your app is created before deploy!`

Hence no new namespace and obviosly deployment fails.

If I manually create the the app namespace via the Dashboard, then deploy from CLI, it works perfect.
But what I am possibly not understanding is... Can you actually deploy a new app name via CLI, hence it creates the new app space then deploys the app?
Am I understanding that correctly? 

To re-iterate: 
1) Create a new app namespace via Dashboard, then upload a .tar via Dash -> **WORKS Perfectly**
2) Create a new app namespace via Dashboard, then deploy to existing namespace via CLI -> **WORKS Perfectly**
3) Use CLI's 'captainduckduck deploy' to provision a new namespace and deploy (all in CLI) -> **Fails with Error above**

Thanks

**Comment by githubsaturn** [comment]
This is not an issue. Using CLI, you're trying to "Deploy" an app. It is different from creating an app. Steps are:

1 - Create an app (using the dashboard)
2 - Deploy the app (using CLI, or dashboard or git webhook)

You cannot skip step 1.

**Comment by thinnker** [comment]
Thanks Kasra, Its what I originally thought, but good to clarify. Much appreciated
