### ISSUE TITLE
How to install something like Ghost?

### ISSUE THREAD

**Issue by backupManager** [githubsaturn/captainduckduck#262]
How do I structure the file to install something like Ghost: https://ghost.org/ ?

Docker: https://hub.docker.com/_/ghost/

**Comment by githubsaturn** [comment]
For Ghost, you need to create an app with persistent data. And in the app's config, create a new persistent directory `/var/lib/ghost/content`

Then follow steps here: https://github.com/githubsaturn/captainduckduck/issues/258#issuecomment-413627678

**Comment by geeksamu** [comment]
I want to use Ghost.org too, and that solution doesn't work for me!

**Comment by githubsaturn** [comment]
What is the problem you are facing? Probably you are not aware of the fact that the default port for Ghost is not 80. You need to change the container port to `2368` as per Ghost's documentation. To do so, follow the example here:
https://github.com/githubsaturn/captainduckduck/issues/130

**Comment by geeksamu** [comment]
I created an app with persistent data with that new persistent directory you mentioned up there.

Then I used this tool 
https://githubsaturn.github.io/dockerfile-to-captain/
to get captain-definition file of this dockerfile
https://github.com/docker-library/ghost/blob/9d29c5d929829dc623e04ca8cc522fba2d6f87de/2/debian/Dockerfile
and finally I set the environmental variables and I uploaded the .tar file 
I got this error in the logs


>{"message":"COPY failed: stat /var/lib/docker/tmp/docker-builder300037361/docker-entrypoint.sh: no such file or directory"}
COPY failed: stat /var/lib/docker/tmp/docker-builder300037361/docker-entrypoint.sh: no such file or directory
>Deploy failed!
Error: {"message":"COPY failed: stat /var/lib/docker/tmp/docker-builder300037361/docker-entrypoint.sh: no such file or directory"}
COPY failed: stat /var/lib/docker/tmp/docker-builder300037361/docker-entrypoint.sh: no such file or directory

**Comment by githubsaturn** [comment]
You did not include the source files in your directory. Also, you went for a very difficult solution! Simple solution is to have this as your captain-definition file:
```
 {
  "schemaVersion" :1 ,
  "dockerfileLines" :[
                        "ghost:1-alpine"
                    ]
 }

```

Convert this file to `tar` and upload it. And everything will be fine.

**Comment by geeksamu** [comment]
Now I have another error message 😅
>Deploy failed!
Error: Error: (HTTP code 400) unexpected - Dockerfile parse error line 1: unknown instruction: GHOST:1-ALPINE

**Comment by githubsaturn** [comment]
My bad. There is a typo in that. It should be 
```
FROM ghost:1-alpine
```

The word FROM is missing from what I said before.

**Comment by geeksamu** [comment]
I did but I have new problem

>NAME: DatabaseError
CODE: EAI_AGAIN
MESSAGE: getaddrinfo EAI_AGAIN db:3306

**Comment by githubsaturn** [comment]
What was your process. I just tested the entire process with a production version of CaptainDuckDuck and everything worked fine. These are my steps:
1- Create an app with persistence checked on the console
2- Added a persistent directory to the config as below:

![1](https://user-images.githubusercontent.com/10582082/45725727-05ee4500-bb71-11e8-9934-a290a0ff9f85.png)

3- Edited the Default Nginx config and assign port `2368`

4- Uploaded the captain-definition file to the web dashboard.


Wait for a couple of minutes, and there it is. It's working: http://testghost.captainduckduck.com/

**Comment by geeksamu** [comment]
It works now thanks, but one last thing.
here at your blog http://testghost.captainduckduck.com/themes/
the logo URL at navbar is localhost, not the main domain.
I have the same issue.

**Comment by githubsaturn** [comment]
@geeksamu 
This is really a ghost issue. Please read Ghost's documentation here:
https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables

All you need to do is to set an environmental variable with key of `url` and value of `http://testghost.sw.captainduckduck.com`

Like this:
![screenshot from 2018-09-19 20-40-24](https://user-images.githubusercontent.com/10582082/45794584-4373d080-bc4c-11e8-88e9-067a83e788f6.png)

**Comment by reyemtm** [comment]
Thanks for such a simple method! This is working better for me than using the one-click ghost app. I know it is sqlite, but I think I'll be fine. 

Here are all the steps in one place - 

1. Create an app with persistent data
2. use ``/var/lib/ghost/content`` as the directory as outlined above, this might be different if choosing "alpine"
3. Change the Container HTTP Port to 2368
4. Enable HHTPS
5. Add the url variable as described above, substituting your url and using https
6. Use "Deploy by Image Name" - ``ghost:latest``
7. Done
