### ISSUE TITLE
Unable to attach new node

### ISSUE THREAD

**Issue by pSnehanshu** [githubsaturn/captainduckduck#264]
IMPORTANT: DO NOT POST issues that are not specific to CaptainDuckDuck. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using dockerfileLines property - please change your questions to Dockerfile and post it where appropriate such as Stackoverflow. This is not a CaptainDuckDuck related issue.

What is the problem?
Unable to attach new node.
It shows `SSH connection error`

Answers to the following questions where applicable:
- Your OS and version? Ubuntu 16
- RAM? 1GiB

**Comment by githubsaturn** [comment]
This is an SSH issue.
Something is preventing an SSH connection to be established between your main node and your new node. Make sure your firewalls are allowing correct ports or just disable them on both nodes with `ufw disable`, make sure you're using the correct keys to connect to the node.

You can see the details of why your SSH connection failed, by running:
```
docker service logs captain-captain --since 60m --follow
```

This shows a "live" feed of logs from Captain's engine. While this log is showing, try to connect the new node. Once you see the error, look at the logs. It must have more details regarding why the SSH connection has failed.

**Comment by jappyjan** [comment]
i'm having the same problem...
looked through all the github issues but could not find a solution...

this is my log output when trying to add a second node:

```
captain-captain.1.nq7hecziy5z2@v22019078774593756    | February 25th 2020, 11:51:01.847 am    Error: SSH Connection error!!
captain-captain.1.nq7hecziy5z2@v22019078774593756    | Error: SSH Connection error!!
captain-captain.1.nq7hecziy5z2@v22019078774593756    |     at Function.createError (/usr/src/app/built/api/ApiStatusCodes.js:7:16)        captain-captain.1.nq7hecziy5z2@v22019078774593756    |     at Client.<anonymous> (/usr/src/app/built/docker/DockerUtils.js:20:43)
captain-captain.1.nq7hecziy5z2@v22019078774593756    |     at Client.emit (events.js:198:13)
captain-captain.1.nq7hecziy5z2@v22019078774593756    |     at doNextAuth (/usr/src/app/node_modules/ssh2/lib/client.js:415:12)
captain-captain.1.nq7hecziy5z2@v22019078774593756    |     at tryNextAuth (/usr/src/app/node_modules/ssh2/lib/client.js:484:5)
captain-captain.1.nq7hecziy5z2@v22019078774593756    |     at SSH2Stream.onUSERAUTH_FAILURE (/usr/src/app/node_modules/ssh2/lib/client.js:597:5)
captain-captain.1.nq7hecziy5z2@v22019078774593756    |     at SSH2Stream.emit (events.js:198:13)
captain-captain.1.nq7hecziy5z2@v22019078774593756    |     at parsePacket (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:3779:10)     captain-captain.1.nq7hecziy5z2@v22019078774593756    |     at SSH2Stream._transform (/usr/src/app/node_modules/ssh2-streams/lib/ssh.js:694:13)
captain-captain.1.nq7hecziy5z2@v22019078774593756    |     at SSH2Stream.Transform._read (_stream_transform.js:190:10)
```

**Comment by r-chris** [comment]
Solution is typically related to SSH keys (or firewall setup). Documentation improvement ref: https://github.com/caprover/caprover-website/pull/32
