### ISSUE TITLE
[FR] Make port forwarding work on a per-subdomain basis

### ISSUE THREAD

**Issue by rafamel** [githubsaturn/captainduckduck#267]
Hi, I'm new to CDD so I'm not sure whether there's a canonical way to do this, but I'm battling with some services I want to publicly expose. As of right now, any port forwarding seems to take the port for the whole server, therefore making it accessible from any subdomain. This means that if a service is running for port, say, 5000, I won´t be able to redirect it to port 80 as it will conflict.

Is there any way to make port forwarding scoped (aka, use also ngix for that)?

**Comment by githubsaturn** [comment]
Have a look at this diagram:
https://captainduckduck.com/img/captain-architecture.png

Nginx owns port 80. If you have an app that exposes HTTP protocol on port 5000, for example, then all you need to do is to edit your nginx config for that particular app and add `:5000` to your upstream address. For example, see this:
https://github.com/githubsaturn/captainduckduck/issues/130

**Comment by rafamel** [comment]
Thanks for the solution @githubsaturn! Should this be added to the docs?
