### ISSUE TITLE
docker container exits after start

### ISSUE THREAD

**Issue by timboslice69** [githubsaturn/captainduckduck#269]
The docker container exists within 30 seconds of creation/starting, I've tried many times, removing all traces and doing clean installs and still the docker instance has exited before i can run the serversetup.

After Running 
`mkdir /captain && docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock dockersaturn/captainduckduck`

I get the following result:

```
> npm info it worked if it ends with ok
> npm info using npm@5.4.2
> npm info using node@v8.7.0
> npm info lifecycle captain-duckduck@0.0.0~prestart: captain-duckduck@0.0.0
> npm info lifecycle captain-duckduck@0.0.0~start: captain-duckduck@0.0.0
> 
> > captain-duckduck@0.0.0 start /usr/src/app
> > node ./bin/www
> 
> Captain Starting ...
> Installing Captain Service ...
> 
>  >>>> Checking System Compatibility <<<<
>    Docker Version passed.
>    Ubuntu detected.
>    X86 CPU detected.
>    Total RAM 2147 MB
> September 4th 2018, 5:32:45.267 pm    Starting swarm at 180.235.132.141:2377
> Swarm started: exc8rx81x8kxmhyvij185ra8e
> npm info lifecycle captain-duckduck@0.0.0~poststart: captain-duckduck@0.0.0
> npm info ok 
> 
```

Then after running
`captainduckduck serversetup`

I get the following:
> ✖ Login...
> Something bad happened. Cannot connect to "http://180.235.132.141:3000/api/v1/login"
> Error: connect ECONNREFUSED 180.235.132.141:3000

"docker ps -all " gives me
```
CONTAINER ID        IMAGE                          COMMAND             CREATED             STATUS                     PORTS               NAMES
c0ece09a1cd4        dockersaturn/captainduckduck   "npm start"         3 minutes ago       Exited (0) 3 minutes ago                       serene_curie
```

If I start the container again it exits faster, normally under 9 seconds.

```
CONTAINER ID        IMAGE                          COMMAND             CREATED             STATUS              PORTS                                                              NAMES
c0ece09a1cd4        dockersaturn/captainduckduck   "npm start"         7 minutes ago       Up 5 seconds        0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:3000->3000/tcp   serene_curie
root@apps:/# docker ps -l
CONTAINER ID        IMAGE                          COMMAND             CREATED             STATUS                              PORTS               NAMES
c0ece09a1cd4        dockersaturn/captainduckduck   "npm start"         7 minutes ago       Exited (0) Less than a second ago                       serene_curie
```

I cant figure out whats going wrong, or how to even see any sort of error logs for the container. Its pretty late here so I may be missing something obvious but so far I've run through the setup process as instructed many times only to end up with this issue.

System information below:

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial


              total        used        free      shared  buff/cache   available
Mem:        2097152      122388     1087852        8044      886912           0
Swap:        262144       36344      225800

Docker version 18.06.1-ce, build e68fc7a

node --version v8.11.4
```

**Comment by githubsaturn** [comment]
It's really bizarre. There might be some issues with firewalls and self-health-monitoring. But it should be caught during the installation process. To get some more logs, please run this:

```
mkdir /captain && docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock dockersaturn/captainduckduck

# after installation is done:
docker service logs captain-captain --since 60m --follow
```

This will show a continuous stream of logs. So you should see what the container restarts. Please post logs here so we can debug the issue.

**Comment by timboslice69** [comment]
I get no output with `docker service logs captain-captain --since 60m --follow`

But with `docker service ps captain-captain --no-trunc` i see the following.

> ID                          NAME                    IMAGE                                NODE                 DESIRED STATE       CURRENT STATE                     ERROR                                                                                                                                                    PORTS
> sqayoa46k4qv5dvupcl1jp425   captain-captain.1       dockersaturn/captainduckduck:0.7.2   ****   Ready               Assigned less than a second ago                                                                                                                                                            
> ovxv86py9jxdwn5tfyswjykg8    \_ captain-captain.1   dockersaturn/captainduckduck:0.7.2   ****   Shutdown            Rejected less than a second ago   "error creating external connectivity network: cannot restrict inter-container communication: please ensure that br_netfilter kernel module is loaded"   
> 1u8tsik3vdq06vhiur8foy9r8    \_ captain-captain.1   dockersaturn/captainduckduck:0.7.2   ****   Shutdown            Rejected 8 seconds ago            "error creating external connectivity network: cannot restrict inter-container communication: please ensure that br_netfilter kernel module is loaded"   
> 6id9mrviqxudtuyjiitxi77jp    \_ captain-captain.1   dockersaturn/captainduckduck:0.7.2   ****  Shutdown            Rejected 16 seconds ago           "error creating external connectivity network: cannot restrict inter-container communication: please ensure that br_netfilter kernel module is loaded"   
> 6pbrtjwzsrkg2er74tldfqkep    \_ captain-captain.1   dockersaturn/captainduckduck:0.7.2   ****   Shutdown            Rejected 21 seconds ago           "error creating external connectivity network: cannot restrict inter-container communication: please ensure that br_netfilter kernel module is loaded"   
> wj6wz3afosogdy5etq859nefv    \_ captain-captain.1   dockersaturn/captainduckduck:0.7.2   ****   Shutdown            Rejected 26 seconds ago           "error creating external connectivity network: cannot restrict inter-container communication: please ensure that br_netfilter kernel module is loaded"   

After a little digging it seems my system is missing br_netfilter so now I'm trying to get it going to continue debugging this problem.

**Comment by timboslice69** [comment]
after some digging br_netfilter is present on my system...

`lsmod | grep br_netfilter`

> br_netfilter 22256 0
> bridge 140269 2 br_netfilter,ebtable_broute

more digging...

**Comment by timboslice69** [comment]
This was related to the host I was using. The VPS was based on OpenVC: Ubuntu 16.04 (for AMD64/Intel EM64T) Virtuozzo Template.

I have moved to another provider and had everything running within an hour.

**Comment by negati-ve** [comment]
> This was related to the host I was using. The VPS was based on OpenVC: Ubuntu 16.04 (for AMD64/Intel EM64T) Virtuozzo Template.
> 
> I have moved to another provider and had everything running within an hour.

docker on Ubuntu has a bug that causes docker to ignore br_netfilter even though it is enabled

I worked around this on my machines by simply creating a dockerenv file
`touch /.dockerenv`
