### ISSUE TITLE
Break up the tutorial to use the project wiki.

### ISSUE THREAD

**Issue by sah2ed** [githubsaturn/captainduckduck#27]
Was thinking that it would be better to break up the [tutorial](https://github.com/githubsaturn/captainduckduck/blob/master/TUTORIAL.md) into multiple pages using the project's [wiki](https://github.com/githubsaturn/captainduckduck/wiki) to make it easier to jump to specific sections and also keep the steps in each section focused on the tasks at hand.

@githubsaturn thoughts?

**Comment by githubsaturn** [comment]
Good suggestion. https://github.com/githubsaturn/captainduckduck/wiki
