### ISSUE TITLE
Captainduckduck not working after docker update

### ISSUE THREAD

**Issue by Briston-KS** [githubsaturn/captainduckduck#271]
Hi there,

I've restarted the docker service to overcome the issue of SSL while creating a new app form CDD, which was mentioned in the issue "SSL error on creating new app #241"

However, after that the CDD was not working. I've tried CDD restart as well from the official CDD documentation.

I've updated the docker version from 16 to 18.06.1-ce. Even ,after the docker  upgrade, the CDD  was not working.

This was done after checking the pre-requisite of docker version mentioned in the official CDD documentation.

=========================
(C) Install Docker on Server (at least, version 17.06.x))
=========================

 
Different errors are found from the docker logs, the following varies each time.

============================
starting container failed: failed to get network during CreateEndpoint:

subnet sandbox join failed for "*.*.*.*/*": error creating vxlan interface: file exists"

==========================

I'm using AWS EC2 container.

can you give any idea of resolving the issue  without losing my applications already deployed in it ?

**Comment by githubsaturn** [comment]
I did some research and unfortunately it seems to be a docker issue and out of our hands to resolve.

> can you give any idea of resolving the issue without losing my applications already deployed in it ?

I am still working on backup feature (https://github.com/githubsaturn/captainduckduck/issues/187). But it's not ready yet.

I usually resolve these issues by rebooting the server. You can give it a shot.


Once the backup feature is done and ready. You can create a snapshot of your server and re-install everything.

**Comment by Briston-KS** [comment]
Thanks.. that worked..I've rebooted the server and restarted the docker service and everything is now working fine.
