### ISSUE TITLE
How do env variables work? (env vars not getting picked up by cronjob)

### ISSUE THREAD

**Issue by devxpy** [githubsaturn/captainduckduck#276]
Hey there!

I'm trying to create an app, that runs a cronjob for backing up postgres container to s3.

I created a script (`backup.sh`) that will do this task.

```
#!/usr/bin/env bash

filename=./$(env TZ=Asia/Kolkata date '+%a %d %b %Y %r')

printenv  # for debugging...

echo "creating sqldump at '$filename'..."

pg_dump > "$filename" && aws s3 cp "$filename" "s3://$AWS_STORAGE_BUCKET_NAME/backups/"
```

I created these env vars from captain's dashboard so that the `pg_dump` and `aws-cli` tools can pick up the credentials they need.

![image](https://user-images.githubusercontent.com/19492893/45622946-5a2af380-baa3-11e8-853d-6fa4b40491b2.png)

And sure enough, when I ` docker exec -it <containeer name> bash` into the container and run `./backup.sh`, everything works as expected. (The env vars appear correctly as well)

---

The issue occurs when I try to run the script from a cronjob; The env vars I defined are nowhere to be seen!

```
PWD=/root
HOME=/root
SHELL=/bin/sh
SHLVL=1
LOGNAME=root
PATH=/usr/bin:/bin
_=/usr/bin/printenv
creating sqldump at './Mon 17 Sep 2018 06:06:01 PM'...
pg_dump: [archiver (db)] connection to database "root" failed: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

```

How can I resolve this?

[Here is my code.](https://github.com/devxpy/postgres-s3-backup)

**Comment by githubsaturn** [comment]
This is a Docker thing, not specific to Captain. Docker containers don't forward env vars to cron jobs automatically. I'm not sure about the the reasoning behind this. But there are multiple solutions available. For example see this
https://ypereirareis.github.io/blog/2016/02/29/docker-crontab-environment-variables/
