### ISSUE TITLE
Error: password is incorrect

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#277]
Apart from the obvious, what could be the cause of this?

![image](https://user-images.githubusercontent.com/9009792/45779300-9486c300-bc52-11e8-8109-d9fd9fea2496.png)

This does admittedly happen when I've restored the captain data from a backup, so I'm doing something non-standard, but strangely it only happens on my desktop chrome, but not on my mobile chrome.  After restoring from backup and restarting captain on the server, I have until the last couple of hours been able to log into the restored captain using the default password... but now I get the above error on desktop chrome, but can log in just fine with that password on mobile.  It may just be a coincidence, but my desktop chrome has updated itself today to a new version... quite a different look and feel.

P.S. what I'm doing is spinning up a new server, where I create the new captain from backup, and point the DNS `*.whatever.mydomain.com` to the new server, so that I can log on to new captain console at `captain.whatever.mydomain.com`.  This has been working fine until today.  When I switch the DNS back to the working server, all is well again and I can log on to the working captain.

![image](https://user-images.githubusercontent.com/9009792/45780012-7de16b80-bc54-11e8-850f-5b79df893fb8.png)

captain logs are below... I made two or three failed login attempts towards the end of the logs (using default password, and with the above error given):

    root@captain-01 ~ # docker service logs captain-captain --since 60m --follow
    >>   npm info it worked if it ends with ok
    >>   npm info using npm@5.4.2
    >>   npm info using node@v8.7.0
    >>   npm info lifecycle captain-duckduck@0.0.0~prestart: captain-duckduck@0.0.0
    >>   npm info lifecycle captain-duckduck@0.0.0~start: captain-duckduck@0.0.0
    >>   
    >>   > captain-duckduck@0.0.0 start /usr/src/app
    >>   > node ./bin/www
    >>   
    >>   Captain Starting ...
    >>   September 19th 2018, 9:04:51.489 pm    Emptying generated and temp folders.
    >>   September 19th 2018, 9:04:51.501 pm    Ensuring directories are available on host. Started.
    >>   September 19th 2018, 9:04:51.511 pm    Ensuring directories are available on host. Finished.
    >>   September 19th 2018, 9:04:51.520 pm    Network captain-overlay-network is already attached to service: captain-captain
    >>   September 19th 2018, 9:04:51.527 pm    Setting up NGINX conf file...
    >>   September 19th 2018, 9:04:51.535 pm    Locking NGINX configuration reloading...
    >>   September 19th 2018, 9:04:51.679 pm    SUCCESS: UNLocking NGINX configuration reloading...
    >>   September 19th 2018, 9:04:51.683 pm    Captain Nginx is already running.. 
    >>   September 19th 2018, 9:04:51.685 pm    Updating NGINX service...
    >>   September 19th 2018, 9:04:51.978 pm    Waiting for 5 seconds for nginx reload to take into effect
    >>   September 19th 2018, 9:04:56.986 pm    NGINX is fully set up and working...
    >>   September 19th 2018, 9:04:57.011 pm    captain-captain (service) has already been connected to secret: captain-salt
    >>   September 19th 2018, 9:04:57.017 pm    There is no Docker Registry, neither local nor remote.
    >>   September 19th 2018, 9:04:57.111 pm    Captain Certbot is already running.. 
    >>   September 19th 2018, 9:04:57.113 pm    Updating Certbot service...
    >>   September 19th 2018, 9:04:57.135 pm    Ensuring Docker Registry is running...
    >>   September 19th 2018, 9:04:57.191 pm    Captain Registry is already running.. 
    >>   September 19th 2018, 9:04:57.212 pm    **** Captain is initialized and ready to serve you! ****
    >>   September 19th 2018, 9:04:58.229 pm    Error: Wrapped: Verification Failed for captain.something.mydomain.com
    >>   Error: Wrapped: Verification Failed for captain.something.mydomain.com
    >>       at errorize (/usr/src/app/src/utils/Logger.js:10:16)
    >>       at Object.e (/usr/src/app/src/utils/Logger.js:45:19)
    >>       at Request._callback (/usr/src/app/src/user/CaptainManager.js:816:44)
    >>       at self.callback (/usr/src/app/node_modules/request/request.js:186:22)
    >>       at emitOne (events.js:115:13)
    >>       at Request.emit (events.js:210:7)
    >>       at Request.onRequestError (/usr/src/app/node_modules/request/request.js:878:8)
    >>       at emitOne (events.js:115:13)
    >>       at ClientRequest.emit (events.js:210:7)
    >>       at Socket.socketErrorListener (_http_client.js:385:9)
    >>   September 19th 2018, 9:04:58.230 pm    Error: Wrapped: Error        Error: connect ECONNREFUSED 159.69.83.30:80
    >>   Error: Wrapped: Error        Error: connect ECONNREFUSED 159.69.83.30:80
    >>       at errorize (/usr/src/app/src/utils/Logger.js:10:16)
    >>       at Object.e (/usr/src/app/src/utils/Logger.js:45:19)
    >>       at Request._callback (/usr/src/app/src/user/CaptainManager.js:817:44)
    >>       at self.callback (/usr/src/app/node_modules/request/request.js:186:22)
    >>       at emitOne (events.js:115:13)
    >>       at Request.emit (events.js:210:7)
    >>       at Request.onRequestError (/usr/src/app/node_modules/request/request.js:878:8)
    >>       at emitOne (events.js:115:13)
    >>       at ClientRequest.emit (events.js:210:7)
    >>       at Socket.socketErrorListener (_http_client.js:385:9)
    >>   September 19th 2018, 9:04:58.230 pm    Error: Wrapped: body         undefined
    >>   Error: Wrapped: body         undefined
    >>       at errorize (/usr/src/app/src/utils/Logger.js:10:16)
    >>       at Object.e (/usr/src/app/src/utils/Logger.js:45:19)
    >>       at Request._callback (/usr/src/app/src/user/CaptainManager.js:818:44)
    >>       at self.callback (/usr/src/app/node_modules/request/request.js:186:22)
    >>       at emitOne (events.js:115:13)
    >>       at Request.emit (events.js:210:7)
    >>       at Request.onRequestError (/usr/src/app/node_modules/request/request.js:878:8)
    >>       at emitOne (events.js:115:13)
    >>       at ClientRequest.emit (events.js:210:7)
    >>       at Socket.socketErrorListener (_http_client.js:385:9)
    >>   September 19th 2018, 9:04:58.230 pm    Error: Wrapped: randomUuid   abd6b89f-6c6b-4c3e-a44f-fd29520b3cd9
    >>   Error: Wrapped: randomUuid   abd6b89f-6c6b-4c3e-a44f-fd29520b3cd9
    >>       at errorize (/usr/src/app/src/utils/Logger.js:10:16)
    >>       at Object.e (/usr/src/app/src/utils/Logger.js:45:19)
    >>       at Request._callback (/usr/src/app/src/user/CaptainManager.js:819:44)
    >>       at self.callback (/usr/src/app/node_modules/request/request.js:186:22)
    >>       at emitOne (events.js:115:13)
    >>       at Request.emit (events.js:210:7)
    >>       at Request.onRequestError (/usr/src/app/node_modules/request/request.js:878:8)
    >>       at emitOne (events.js:115:13)
    >>       at ClientRequest.emit (events.js:210:7)
    >>       at Socket.socketErrorListener (_http_client.js:385:9)
    >>   September 19th 2018, 9:04:58.231 pm    Captain health check failed: #0 at captain.something.mydomain.com
    >>   September 19th 2018, 9:04:58.231 pm    NGINX health check failed: #0
    >>   GET /checkhealth 302 10.390 ms - 75
    >>   GET /checkhealth 200 6.862 ms - 36
    >>   GET /checkhealth 302 0.607 ms - 75
    >>   GET /checkhealth 200 1.666 ms - 36
    >>   GET /checkhealth 302 0.719 ms - 75
    >>   GET /checkhealth 200 2.585 ms - 36
    >>   GET /checkhealth 302 0.294 ms - 75
    >>   GET /checkhealth 200 0.738 ms - 36
    >>   GET /checkhealth 302 0.502 ms - 75
    >>   GET /checkhealth 200 0.959 ms - 36
    >>   September 19th 2018, 9:05:57.150 pm    executeCommand Container: 7caad00afddd0430d04ff769b7e0a8728cbb193c1ccf9144539b656b7588410b
    >>   GET /checkhealth 302 0.372 ms - 75
    >>   GET /checkhealth 200 0.941 ms - 36
    >>   GET /checkhealth 302 0.166 ms - 75
    >>   GET /checkhealth 200 0.560 ms - 36
    >>   GET /checkhealth 302 0.398 ms - 75
    >>   GET /checkhealth 200 0.828 ms - 36
    >>   GET / 304 5.456 ms - -
    >>   GET /lib/css/main.min.css 304 0.916 ms - -
    >>   GET /css/rdash-custom.css 304 0.469 ms - -
    >>   GET /lib/js/main.min.js 304 0.742 ms - -
    >>   GET /js/dashboard.min.js 304 0.733 ms - -
    >>   GET /img/icon-512x512.png 304 0.700 ms - -
    >>   GET /checkhealth 302 0.427 ms - 75
    >>   GET /img/avatar.jpg 304 0.582 ms - -
    >>   GET /checkhealth 200 0.633 ms - 36
    >>   GET /templates/dashboard.html 304 0.625 ms - -
    >>   September 19th 2018, 9:06:24.017 pm    JsonWebTokenError: jwt must be provided
    >>   GET /api/v1/user/system/info 200 5.679 ms - 52
    >>   GET /lib/fonts/fontawesome-webfont.woff2?v=4.5.0 304 0.509 ms - -
    >>   GET /fonts/montserrat-regular-webfont.woff 304 0.462 ms - -
    >>   GET /templates/login.html 304 0.620 ms - -
    >>   POST /api/v1/login 200 29.651 ms - 54
    >>   POST /api/v1/login 200 6.990 ms - 54
    >>   GET /checkhealth 302 0.217 ms - 75
    >>   GET /checkhealth 200 0.605 ms - 36
    >>   POST /api/v1/login 200 1.956 ms - 54
    >>   GET /checkhealth 302 0.422 ms - 75
    >>   GET /checkhealth 200 1.017 ms - 36
    >>   GET / 304 1.543 ms - -
    >>   GET /lib/css/main.min.css 304 0.977 ms - -
    >>   GET /css/rdash-custom.css 304 1.296 ms - -
    >>   GET /lib/js/main.min.js 304 0.434 ms - -
    >>   GET /img/avatar.jpg 304 0.671 ms - -
    >>   GET /js/dashboard.min.js 304 0.757 ms - -
    >>   GET /img/icon-512x512.png 304 0.946 ms - -
    >>   GET /templates/login.html 304 0.490 ms - -
    >>   GET /lib/fonts/fontawesome-webfont.woff2?v=4.5.0 304 0.654 ms - -
    >>   GET /fonts/montserrat-regular-webfont.woff 304 0.476 ms - -
    >>   POST /api/v1/login 200 3.690 ms - 54
    >>   GET /checkhealth 302 0.303 ms - 75
    >>   GET /checkhealth 200 0.777 ms - 36
    >>   GET /checkhealth 302 0.317 ms - 75
    >>   GET /checkhealth 200 0.626 ms - 36

**Comment by githubsaturn** [comment]
I just tried this on a the exactly same version of the Google Chrome and everything ran fine.

- Can you try this on incognito mode?
- If it also fails on incognito, please inspect the network traffic and copy the request body, headers and response here.

**Comment by drmrbrewer** [comment]
OK interesting.  I stripped it right back to basics, i.e. not trying to do any complicated stuff relating to restoring captain config or doing any other server setup in cloud-init.  I just created a bare Ubuntu 18.04 server, and went through the steps in [Getting Started](https://captainduckduck.com/docs/get-started.html), i.e. installing docker, captain and captain CLI on the new server, setting up DNS as instructed, and doing serversetup.  BTW I'm using a Hetzner Cloud server (the cheapest CX11). 

And sure enough, I get the "password is incorrect" error when trying to log in to the captain console with the default password, even with this very basic setup.

Inspecting the network traffic... please explain what tool to use and what output I should post.

**Comment by githubsaturn** [comment]
I just tested a brand new installation on DigitalOcean. Everything was okay. We haven't published a new version in the past two months. I doubt things just break without any external modifications. I'll keep this issue open to see if anyone else is experiencing the same issue.

**Comment by drmrbrewer** [comment]
> I doubt things just break without any external modifications

That's what I don't understand either.

What about the network traffic reporting... can I provide some more info about this which might help?

**Comment by githubsaturn** [comment]
> What about the network traffic reporting... can I provide some more info about this which might help?

This would have been helpful only if the issue was with a particular browser. But since the CLI is also exhibiting the same issue, the network traffic won't be helpful anymore.

**Comment by drmrbrewer** [comment]
OMG I figured it out.  Slightly red face.  When prompted for the password, knowing that it was still at the default, and knowing that the default password is displayed on the login screen itself, I take the lazy approach (or shall I say the "foolproof" approach) and double-click on the password, then ctrl-c to copy:

![image](https://user-images.githubusercontent.com/9009792/45837896-54821780-bd08-11e8-8c33-0fc9eb777b23.png)

And I hadn't spotted that the above selection also includes a space at the end of it, so that I'm copying and pasting `captain42_` not `captain42` :-/

Apart from learning from my mistake, maybe the only suggestion would be to see if the webpage content could be changed somehow so that double clicking that word only selects the word without an extra space... so that someone in future isn't also caught :)

**Comment by 0xShervin** [comment]
I have a problem with login page and it's not solved by this issue. I'm getting constantly error "1105 : Invalid credentials" and it doesn't let me to login!

**Comment by maietta** [comment]
> I have a problem with login page and it's not solved by this issue. I'm getting constantly error "1105 : Invalid credentials" and it doesn't let me to login!

Please refer to the troubleshooting guide regarding resetting the password at https://caprover.com/docs/troubleshooting.html#reset-password
