### ISSUE TITLE
"net/http: TLS handshake timeout" after fresh install + activation self-signed registry

### ISSUE THREAD

**Issue by vitali-korezki** [githubsaturn/captainduckduck#278]
After fresh install and activation of self-signed registry, cannot add new nodes because of the following error:

"ERROR 1000: Push failed: 
{"message":"Get https://registry.mydomain.com:996/v2/: net/http: TLS handshake timeout"}Get https://registry.mydomain.com:996/v2/: net/http: TLS handshake timeout"

<img width="699" alt="captainduckduck tls handshake timeout" src="https://user-images.githubusercontent.com/2910779/45785184-3d67fa80-bc20-11e8-9e8a-a22afb2f8e11.png">

Ubuntu: 18.04
OS: linux
Architecture: x86_64
Memory: 31.28 GB
Docker Engine: 18.06.1-ce

**Comment by githubsaturn** [comment]
You probably have firewalls enabled. Run `ufw disable` and try again.

**Comment by vitali-korezki** [comment]
Thanks, ufw is inactive, still same results.
I've found a discussion how to solve it for docker at serverfault: [docker-pull-tls-handshake-timeout](https://serverfault.com/questions/908141/docker-pull-tls-handshake-timeout)

The described solution:
> If you are using a **private registry**, you need to place the certificate for that under /etc/docker/certs.d/**registryname**/ca.crt

Is that a possible solution for captain as well?
On my server the described directory `/etc/docker/certs.d/...` doesn't exist. Need to create manually?

**Comment by githubsaturn** [comment]
The certificate management is being taken care of by CaptainDuckDuck automatically. The solution is unnecessary for CaptainDuckDuck.

Timeout is a socket level error. This your is blocked. Either via a firewall such as `ufw` or by a gateway. Does your server have a direct public IP?

If your server is behind a NAT (like a PC at your home behind a router) then you need to manually forward all ports that are used by Captain to your PC in your router/modem settings. These are the ports that you need to forward: https://captainduckduck.com/docs/firewall.html

Judging from your 32GB of RAM, I believe this is the case. i.e., you're not using a VPS such as DigitalOcean or AWS and you host your machine. If this is true, the port forwarding is what you need to do. Even with that, the setup can be complex. As CaptainDuckDuck expects a public IP to be available as a local IP via a Network Interface.

**Comment by vitali-korezki** [comment]
I just added new entry in /etc/hosts with with my server ip and registry.mydomain.com, now the registry issue gone.
thanks

**Comment by githubsaturn** [comment]
Do you mind adding a bit info about your network architecture so that the next time this issue arises we know what caused it? Is your system behind a NAT?

**Comment by vitali-korezki** [comment]
sure, this is a dedicated server (SB-line) from hetzner with one static public IPv4 and IPv6, with a fresh installation of Ubuntu 18.04 minimal, ufw disabled, no additional packages except captainduckduck.

I couldn't find any information about NAT or other network specifications. All what I know, hetzner offers a firewall which can be configured via customer dashboard (at the time of setup firewall was disabled).

**Comment by githubsaturn** [comment]
It probably is the ipv6 problem... IPV6 doesn't play nice with let's encrypt and docker. I'll have to add a test for it to inform the user appropriately. 


Thank you very much for the info.

**Comment by vitali-korezki** [comment]
Seems like deploying on this kind of server is not really possible. 
I've tested build-in apps like mongo and mongo-express. The first seems to start successful, mongo-express not.

Even more, captain restarts over and over again. Here is the error I see repeatedly in the logs:

> Captain health check failed: #0 at captain.mydomain.com
| September 20th 2018, 4:42:04.968 am    NGINX health check failed: #0
| September 20th 2018, 4:42:10.989 am    Error: Wrapped: Verification Failed for captain.mydomain.com
| Error: Wrapped: Verification Failed for captain.mydomain.com
|     at errorize (/usr/src/app/src/utils/Logger.js:10:16)
|     at Object.e (/usr/src/app/src/utils/Logger.js:45:19)
|     at Request._callback (/usr/src/app/src/user/CaptainManager.js:816:44)
|     at self.callback (/usr/src/app/node_modules/request/request.js:186:22)
|     at emitOne (events.js:115:13)
|     at Request.emit (events.js:210:7)
|     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:878:8)
|     at emitOne (events.js:115:13)
|     at ClientRequest.emit (events.js:210:7)
|     at Socket.socketErrorListener (_http_client.js:385:9)
| September 20th 2018, 4:42:10.991 am    Error: Wrapped: Error        Error: getaddrinfo EAI_AGAIN captain.mydomain.com:80
| Error: Wrapped: Error        Error: getaddrinfo EAI_AGAIN captain.mydomain.com:80
|     at errorize (/usr/src/app/src/utils/Logger.js:10:16)
|     at Object.e (/usr/src/app/src/utils/Logger.js:45:19)
|     at Request._callback (/usr/src/app/src/user/CaptainManager.js:817:44)
|     at self.callback (/usr/src/app/node_modules/request/request.js:186:22)
|     at emitOne (events.js:115:13)
|     at Request.emit (events.js:210:7)
|     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:878:8)
|     at emitOne (events.js:115:13)
|     at ClientRequest.emit (events.js:210:7)
|     at Socket.socketErrorListener (_http_client.js:385:9)
| September 20th 2018, 4:42:10.992 am    Error: Wrapped: body         undefined
| Error: Wrapped: body         undefined
|     at errorize (/usr/src/app/src/utils/Logger.js:10:16)
|     at Object.e (/usr/src/app/src/utils/Logger.js:45:19)
|     at Request._callback (/usr/src/app/src/user/CaptainManager.js:818:44)
|     at self.callback (/usr/src/app/node_modules/request/request.js:186:22)
|     at emitOne (events.js:115:13)
|     at Request.emit (events.js:210:7)
|     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:878:8)
|     at emitOne (events.js:115:13)
|     at ClientRequest.emit (events.js:210:7)
|     at Socket.socketErrorListener (_http_client.js:385:9)
| September 20th 2018, 4:42:10.992 am    Error: Wrapped: randomUuid   d0b879d6-09bb-4a4c-b162-e8193b683799
| Error: Wrapped: randomUuid   d0b879d6-09bb-4a4c-b162-e8193b683799
|     at errorize (/usr/src/app/src/utils/Logger.js:10:16)
|     at Object.e (/usr/src/app/src/utils/Logger.js:45:19)
|     at Request._callback (/usr/src/app/src/user/CaptainManager.js:819:44)
|     at self.callback (/usr/src/app/node_modules/request/request.js:186:22)
|     at emitOne (events.js:115:13)
|     at Request.emit (events.js:210:7)
|     at Request.onRequestError (/usr/src/app/node_modules/request/request.js:878:8)
|     at emitOne (events.js:115:13)
|     at ClientRequest.emit (events.js:210:7)
|     at Socket.socketErrorListener (_http_client.js:385:9)

**Comment by githubsaturn** [comment]
This is most likely ipv6. You can disable IPv6 and try again, see the issue below, it might help.
https://github.com/githubsaturn/captainduckduck/issues/143

The bindings between the network interface's IPv6 and containers are not perfect. That's why Captain cannot talk to containers. Anyways, try disabling ipv6 from your DNS entry if you have one. If that doesn't solve the issue, disable ipv6 in ubuntu. Hopefully this should resolve the issue.

**Comment by githubsaturn** [comment]
Two more solutions that I can think of:

1- Use `dnsmasq` on Ubuntu. It's similar to `/etc/host` but it allows for wild card entry.
- Run `which dnsmasq` to make sure you have `dnsmasq` installed
- Make sure this file exists, if not, create this file: `/etc/NetworkManager/dnsmasq.d/dnsmasq-localhost.conf`
- Edit this file and add this line to it: `address=/captain.x/123.123.123.123` where `123.123.123.123` is your server's IP address.
- Restart network manager: `sudo service network-manager restart`

Proceed to solution 2 if the first solution doesn't work
2) Add all used domains, manually, to your `/etc/hosts` and assign them with your IP address.
- registry.mydomain.com
- captain.mydomain.com
- app1.mydomain.com
- app2.mydomain.com

**Comment by vitali-korezki** [comment]
Unfortunately didn't worked either. NetworkManager had to be installed in my case, but after the setup dns lookup stops working completely. I guess because of missing/wrong configuration from my side.
Right now, I'll switch back to digitalocean server, may be in couple month I'll try another run again and will give you a note if I find the solution.
many thanks for your help!

**Comment by vitali-korezki** [comment]
I just had a chance to look again on the issue, the reason is indeed because of IPv6.
The same problem happens when you purchase a Droplet on Digitalocean with IPv6 address and try to use self-signed registry. 

The solution to get this work I have found here (works for Ubuntu 18.04): https://askubuntu.com/a/1046648

Inside of `/etc/default/grub` set:
`GRUB_CMDLINE_LINUX_DEFAULT="ipv6.disable=1"`
`GRUB_CMDLINE_LINUX="ipv6.disable=1"`

Then execute:
`sudo update-grub`
`sudo reboot`

**Comment by githubsaturn** [comment]
Great! :+1:
