### ISSUE TITLE
Minor info inconsistency

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#279]
When doing a `serversetup` the first question asked is:

![image](https://user-images.githubusercontent.com/9009792/45805489-b87bf000-bcb6-11e8-9c73-eebc8b29c993.png)

But in fact the command is now a bit longer (think it used to be as stated above):

    mkdir /captain && docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock dockersaturn/captainduckduck

**Comment by githubsaturn** [comment]
Done in 1.1.0
