### ISSUE TITLE
Inconsistency in availability of .git directory

### ISSUE THREAD

**Issue by devxpy** [githubsaturn/captainduckduck#281]
I am using sentry, which requires me to provide it with the sha checksum of my HEAD (last commit). 

Normally, I use the git webhook for my deploys, and raven (sentry python client) is able to fetch the git sha (probably because the `.git` dir exists)

But then I tried to use the captain cli to deploy, and surprisingly, raven threw an error, saying that it couldn't find the git dir.

[More info here.](https://github.com/getsentry/raven-python/issues/855)

**Comment by githubsaturn** [comment]
This is not inconsistency. Captain does not ship your entire git history to the server.

CaptainDuckDuck by default uses `git archive` command: https://git-scm.com/docs/git-archive
Your `.gitignore` files and your `.git` directory gets excluded by default by `git archive` , when creating an archive that will be sent to the server.

Particular to your question, if you'd like to send our `.git` directory to the server, simply use the `--tarfile` flag on `captainduckduck deploy`. Using this flag you can pass in your own tarfile which can include your `.git` directory. To use this:
- Run a script that converts your entire directory to a tarfile 
- Run `captainduckduck deploy --tarfile <PATH TO YOUR CREATED TARFILE>`

**Comment by lzzy12** [comment]
@githubsaturn  can we not add a flag in caprover cli which can do this on it's own? Because it'll we really inconvenient to tar the folder everytime and pass the location in the command?

**Comment by lzzy12** [comment]
Seems the --tarfile flag doesn't exist in caprover cli after the rebase

**Comment by githubsaturn** [comment]
Adding a flag wouldn't solve the problem. If there was only one use case, it would have been doable. But here is the scenario:
- In 99% of cases, `caprover deploy` with default options will work just fine.
- the other 1% of cases, sometimes you need to include "all files" in the directory, sometimes, you need to include a directory that's not version controlled but nothing else, sometimes, a mixture of two.


This complexity shouldn't surface itself on caprover CLI. Instead, the our approach was to address the 99% of cases directly, and leave the customization option open for the other cases.

In your case, you want to avoid taring the file every single time, create a helper shell file like `./deployer.sh` this:

```
#!/bin/bash

# THIS IS JUST AN EXAMPLE!
tar -cvf ./deploy.tar --exclude='*.map' ./captain-definition ./build/*
caprover deploy -t ./deploy.tar
```

Now simply just run `./deployer.sh` in your directory and avoid having to pass all the args

**Comment by osmanzeki** [comment]
I agree with @githubsaturn here, there are pretty easy ways to automate this without changing the core of how CapRover deploys your artifacts.

I also use the tar method most of the time and am using a simple Makefile to automate most of the deployment.

For situations where I need to add files that are traditionally ignored by the `git archive` command (like `.env` files for example), I just append them to the tar in my Makefile after I run the archive command.

Like so:

```Makefile
# Phony Targets
.PHONY: help archive deploy deploy-first

# Variables
ROOT_DIR=$(pwd)
APP_NAME=my-app
ARTIFACT_PATH=.artifacts/artifact.tar

# Targets
help:
	@echo "You gotta call 'make deploy', silly you!"

archive:
	( \
	echo "Entering build artifact folder..." && \
	cd $(ROOT_DIR)/$(APP_NAME) && \
	echo "Archiving build artifact folder..." && \
	git archive -v HEAD ./ --format=tar > $(ROOT_DIR)/.artifacts/artifact.tar && \
	echo "Appending gitignored files into artifact..." && \
	tar --append --file=$(ROOT_DIR)/.artifacts/artifact.tar \
	$(ROOT_DIR)/$(APP_NAME)/client/.env \
	$(ROOT_DIR)/$(APP_NAME)/server/.env \
	echo "All done!" \
	)

deploy-first: archive
	caprover deploy -a $(APP_NAME) -t $(ROOT_DIR)/$(APP_NAME)/.artifacts/artifact.tar

deploy: archive
	caprover deploy --default
```

The very first time I deploy, I call the `make deploy-first` command to configure the folder in the caprover-cli and then I use the `make deploy` command from there on.
