### ISSUE TITLE
Problem to configure Continuous Integration with git address stating with https://

### ISSUE THREAD

**Issue by angelopolotto** [githubsaturn/captainduckduck#283]
I had troubles to integrate my CDD app with my git repository. My app saw the changes but never finish the build.
After days searching why my app don't finish the build,  I found the problem using this command to see the logs `docker service logs captain-captain --since 60m --follow` inside of CDD service. 
I was adding **https://** at beginning of my Git address in my app configuration, but the CDD don't made the string concatenation correctly to the HTTP Basic Auth. So, the final string is something like this:

**https://user:pass@https://git.address.com/app.git**

but the correctly is:

**https://user:pass@git.address.com/app.git**

I think we have two bugs:
• CDD don't log when something wrong happen in the Git Clone process.
• CDD don't concatenate the repository URL string correctly to the HTTP basic auth process.

Steps to reproduce the problem:
Try integrate a CDD app with a git repository address starting with **https://**

**Comment by ngoyal16** [comment]
we can mark this is close

**Comment by githubsaturn** [comment]
Thanks @ngoyal16 

This will be included in the next minor version release soon.
