### ISSUE TITLE
Feature Request: Templates

### ISSUE THREAD

**Issue by derek-adair** [githubsaturn/captainduckduck#286]
I would like to be able to use duckduck as a means of keeping track of my default app setups.  The main thing I want to be able to do is set up sane defaults and stub out clones of this default on a given domain.  It would work just like the one-click apps, but it would be my own custom recipe's.

I'm not sure how much of this would go in the web UI or how much would go in the client or w/e but the basics would require.

The workflow would be something like;
1. Generate Image
a. Fork any of the one-click apps
b. Generate a Dockerfile ([basically include this](https://githubsaturn.github.io/dockerfile-to-captain/))  
c. pull directly from some git repo
2. Do work to customize said app
3. Save and expose in one-click app view 
4. *Some how link entire project to a git host / CI / whatever and create a brand new project.  However,  maybe I do not understand how I may achieve this already. Do I simply create a volume w/ /var/www/html linked to host and throw that in git?)

**Comment by derek-adair** [comment]
This would include:

1. Custom Dockerfile
2.  Ability to add /edit one click app list
3. Ability to easily create and access a git repository
4. Ability to link this directly to a github/gitlab project.

This is a great project but w/o the ability to easily add/extend these base images its unusable for me beyond simple client demos.  For example;

1) Edit php.ini be able to upload plugins to wordpress
2) Use postgres for Django
3) Install PIL, etc

---------------------

If there were any clear way to generate my own project templates I'd probably dive in and contribute some more complicated examples, but i'm not even sure where to start.

**Comment by githubsaturn** [comment]
I don't quite understand this feature request. Could you clarify?

Things like installing PIL and even editing `php.ini` can be done via Dockerfile manipulation: https://github.com/docker-library/wordpress/issues/10#issuecomment-72141272

In particular:
> Custom Dockerfile
Already supported: https://captainduckduck.com/docs/captain-definition-file.html#convert-dockerfile-to-captain-definition

https://github.com/githubsaturn/captainduckduck/issues/113 is simply a minor improvement. People are already using scripts to automate this: https://github.com/githubsaturn/captainduckduck/issues/214

> Ability to add /edit one click app list
In the pipeline. Hopefully by the end of Q4.

> Ability to easily create and access a git repository
> Ability to link this directly to a github/gitlab project.
Not too sure what you meant by these. But you can use git webhooks for automatic deployment upon git push - if that's what you meant.

**Comment by derek-adair** [comment]
Thanks for the quick response!  I'm very excited about this project and i just need more time with it I guess.

this is what i need...https://githubsaturn.github.io/dockerfile-to-captain/

Is there any reason not to support just... using the Dockerfile?

**Comment by derek-adair** [comment]
Updating w/ relevant feature request....

**Comment by githubsaturn** [comment]
> Is there any reason not to support just... using the Dockerfile?

There will be support for direct referencing to a Dockerfile as per https://github.com/githubsaturn/captainduckduck/issues/113

Hopefully it'll be ready by the end of Q4.

**Comment by derek-adair** [comment]
Hell ya!

Was it clear what i mean by #3 thats really the core of what i would like.  Basically take an existing project and add it to one click install apps.
