### ISSUE TITLE
COPY not working as expected

### ISSUE THREAD

**Issue by derek-adair** [githubsaturn/captainduckduck#287]
```
{
  "schemaVersion": 1,
  "dockerfileLines": [
    "FROM python:3.4-alpine",
    "WORKDIR /app",
    "RUN apk update && apk upgrade \"postgresql-dev\" \"musl-dev\" \"gcc\" \"linux-headers\" \"libffi-dev\" \"zlib-dev\" \"jpeg-dev\"",
    "RUN pip install --no-cache-dir virtualenv && mkdir /virtualenv &&  virtualenv /virtualenv",
    "COPY pip.conf /virtualenv/",
    "COPY requirements.in /app/",
    "RUN /virtualenv/bin/pip install -r requirements.in",
    "COPY . /app"
  ]
}
```

Resulting in:

{"message":"COPY failed: stat /var/lib/docker/tmp/docker-builder491037336/pip.conf: no such file or directory"}
COPY failed: stat /var/lib/docker/tmp/docker-builder491037336/pip.conf: no such file or directory.

**Comment by derek-adair** [comment]
Ah, i need to add ./src in front of any file i include.

**Comment by githubsaturn** [comment]
Yes - this is a design flaw that will be addressed in the future. The `./src` prefix is confusing.

**Comment by derek-adair** [comment]
THanks again for your fast responses
