### ISSUE TITLE
[documentation] Document how to deploy a custom tar with CLI

### ISSUE THREAD

**Issue by etienne-dldc** [githubsaturn/captainduckduck#289]
Hi ✋,

I think it would be valuable to document the deployment using the CLI with a custom `tar` file.

It took me quite a while to figure that out but now I'm using this all the time for front-end projects that are only static files.

Here is a small step-by-step for a `create-react-app` that could be added to the doc: 

## Build your app

```bash
npm run build
```

## Create `captain-definition`

```json
{
  "schemaVersion": 1,
  "dockerfileLines": [
    "FROM socialengine/nginx-spa:latest",
    "COPY ./src/build /app",
    "RUN chmod -R 777 /app"
  ]
}
```

## Create the `tar` file

```bash
tar -cvf ./deploy.tar --exclude='*.map' ./captain-definition ./build/*
```

**Tip**: Add `deploy.tar` to your git ignore to avoir accidentally pushing it 😉 

## Deploy with `captainduckduck`

```bash
captainduckduck deploy -t ./deploy.tar
```

Then answer the questions as usual, wait for the upload and 🎉

The big advantage of this technic is that the build happen on your machine where you already have `node_modules` and probably more computing power than on your server and you also only upload minified files and not the entire codebase, which mean the deploy is way faster.

I hope this is helpful 🤞,
Keep being awesome guys 😎

**Comment by githubsaturn** [comment]
Thank you @etienne-dldc !

If you convert this into an `md` file and place it in the docs directory: 
https://github.com/githubsaturn/captainduckduck/tree/master/docs

and create a PR, I'll be happy to add it to the website under a new category, called recipes.
