### ISSUE TITLE
Security concerns

### ISSUE THREAD

**Issue by derek-adair** [githubsaturn/captainduckduck#292]
There are some opportunities for hardening this app.   [Exposing docker.sock is dangerous](https://raesene.github.io/blog/2016/03/06/The-Dangers-Of-Docker.sock/), but the real issue is that all of the containers are running as root.

[This is bad](https://medium.com/redbubble/running-a-docker-container-as-a-non-root-user-7d2e00f8ee15).

It's worth looking at [docker-gen](https://github.com/jwilder/docker-gen) for the solution to this.

**Comment by githubsaturn** [comment]
Not all containers run as root. But they CAN run as root - which is the default behavior for Docker. Developers need to decide whether this is actually a security risk or not. It is generally not a security risk.

About the socket access, it is a security risk if a random party container requires access to the socket. CaptainDuckDuck is a docker management system. It "does" need access to everything about your containers. It sets environmental variables and etc. It sets the image, compiles the source code and etc. It is not a security risk that it has access to the container, as it's a container management system. This is all container management systems.

**Comment by derek-adair** [comment]
>Not all containers run as root. But they CAN run as root

All CDD containers run as root, correct? thats what i meant by this

>Developers need to decide whether this is actually a security risk or not. 

If I want to run captainduckduck in an public container (I do), it is DEFINITELY a risk to have root exposed in such a manner.

Plus, unless i'm missing something, this is ENTIRELY avoidable if you'd take a look at docker-gen.  Its a pretty slick tool that would help generate, build and manage containers securely.

**Comment by derek-adair** [comment]
"risk" is probably a strong word.  This is honestly a pretty minor thing considering you can really lock down the CDD containers.

It's really just an opportunity to harden the system in general and make it more secure for the people who really just copy paste and... ya know...

* disable ufw
* leave all docker ports open

**Comment by derek-adair** [comment]
I'm open to any advice on how to properly use this tool in a secure manner.  I'm pretty green at sys admin (4 years or so).

**Comment by githubsaturn** [comment]
> I'm open to any advice on how to properly use this tool in a secure manner. I'm pretty green at sys admin (4 years or so).

CaptainDuckDuck on itself is so simple that there is not many holes for security risks. As I mentioned in the other issue, it doesn't even use cookies to minimize the risk. Even if you use basic commands, like `ufw disable` and open all your ports, it is still pretty secure - provided that your SSH is locked down via private/pubic key and not a default password such as `admin123`.
