### ISSUE TITLE
to run captain in a seperated instances, that means except nodes for captain

### ISSUE THREAD

**Issue by williamhatch** [githubsaturn/captainduckduck#294]
to make it more stable?

**Comment by githubsaturn** [comment]
I am not sure if I understand what you're saying. Can you please elaborate?

**Comment by williamhatch** [comment]
Hi, I mean assume captainduckduck is running on machine A, then A is supposed to be the node of the cluster. If I add node B, then node A and node B are the nodes. I mean if it is possible to exclude node A, just include node B as the cluster.

**Comment by githubsaturn** [comment]
Captain and nginx must run on the main node. Any other application can run on another node.
