### ISSUE TITLE
features requirement

### ISSUE THREAD

**Issue by williamhatch** [githubsaturn/captainduckduck#296]
Possible to have these features: 1) support heroku buildpack 2) mail server , using postal (open source)  3) easy plugin db, just like heroku? user neednt setting anything 4) log collector to one center (or log drain)﻿

To suppport the cmdline like heroku will be better ...

And possible to have IRC or slack?

**Comment by iamrommel** [comment]
Not sure why there is a need for item 1 (you can build app in 3 ways from cdd)
Item 2 & 3 can be done by just deploying your captain definition (so i guess there is no need for that), if you can find it on dockerhub then you can deploy it using CDD

I think item 4 was reconsidered before by utilizing "docker service logs" command, not sure what is progress about it. Logs inside the apps in cdd is a feature i like the most. But for the mean time if i want to see logs i just do docker service logs on the machine

**Comment by githubsaturn** [comment]
@iamrommel mostly covered everything. But just a few additional points:
for (1), Dockerfiles give you super powers in terms of creating your image, but if you really want to use Heroku buildpacks, you can use https://github.com/gliderlabs/herokuish

For 2 and 3, you can literally use dockerfiles. However, if you want a specific one-click app, please mention in here: https://github.com/githubsaturn/captainduckduck/issues/258

For 4) iamrammel covered everything.
