### ISSUE TITLE
Verification failed Error: 1107

### ISSUE THREAD

**Issue by Herbo4** [githubsaturn/captainduckduck#297]
**What is the problem?**
My domain will not attach to the duckduck install, Error: 1107

**Steps to reproduce the problem:**
-Create an Amazon EC2 instance and port forward the CaptainDuckDuck ports for all inbound and outbound traffic on your security group. (Went smoothly)
-Enter an A record on Namecheap (*.admin --> myIP) and wait for it to propagate (nslookup confirms with authoritative answer)
-Disable the Ubuntu Firewall and restart the server, then check the status (Status:inactive)
-Run the CaptainDuckDuck installer (Had to use sudo, not sure if this is the **root** of the problem- ba-dum-ching)
-Now run captainduckduck serversetup, using your server's public IP and your wildcarded subdomain. 

Answers to the following questions where applicable:
- Your OS and version?
Ubuntu 16.04 via Amazon EC2, docker stats below:
```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:21 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```
**RAM**
2 GB

**Comment by githubsaturn** [comment]
Does it fail when it's asking for the root domain or when it's asking for email to enable SSL?

**Comment by Herbo4** [comment]
This was completely my bad- I missed the Post-Install config on Docker. If you get this error, make sure your docker instance is configured FULLY. Thanks for the response.

**Comment by opensourcekam** [comment]
I'm having a similar issue now @Herbo4 was there a specific post installation configuration that you used?

**Comment by tim-hub** [comment]
same issue @Herbo4 @opensourcekam
