### ISSUE TITLE
CLI: allow -s and -d to be combined

### ISSUE THREAD

**Issue by garth** [githubsaturn/captainduckduck#300]
When using `captainduckduck deploy -s` and some options are missing (eg `-p password`) then all other options are ignored and the CLI will ask for every parameter.

Particularly for environments where an app is deployed to multiple instances (eg test, prod), it would be useful to be able to combine `-s` and `-d` to allow the missing parameters to be taken from the defaults.

For example 

```
captainduckduck deploy -d -s -h https://captain.mydomain -a my-app -b master
```

should use the stored password or only prompt for the password when it has not been set or has expired.

**Comment by tuefekci** [comment]
Cpp stores the token on an per repo bases so the data is already there.

$CONFIG/configstore/captainduckduck.json should be in your home folder in something like .config. the needed data is in deploy also already loaded https://github.com/githubsaturn/captainduckduck/blob/master/app-cli/captainduckduck-deploy.js#L16 if you add some logic under https://github.com/githubsaturn/captainduckduck/blob/master/app-cli/captainduckduck-deploy.js#L213 you should be good to go.

**Comment by githubsaturn** [comment]
Done in  1.1.0
