### ISSUE TITLE
Some apps didn't restart after system reboot

### ISSUE THREAD

**Issue by enricodeleo** [githubsaturn/captainduckduck#301]
After rebooting the machine, apps restarted correctly automatically except a couple of them that are unavailable even after a re-deploy and a "save configuration". They do not appear even with `docker ps`.

Is that a known issue?

OS is Ubuntu 16.04

**Comment by githubsaturn** [comment]
This shouldn't happen. Anything specific about those apps?

Can you reproduce this issue easily? If so, please post reproducible steps here so we can look into it.

Also, "right after restart", can you get the output from `docker service logs srv-captain--yourappname --since 1h` and also `docker service ls`?

**Comment by enricodeleo** [comment]
@githubsaturn output of `docker service logs servicename` is empty even without a timespan limit for the 2 apps that didn't started.

`docker service ls` states REPLICAS as `0/1`.

**Comment by githubsaturn** [comment]
> `1/1: invalid mount config for type "bind": bind source path does not exist`

Aha! It means that your path on your host is gone after restart. To investigate further:
- What host you're using? If you're using Docker for AWS, see this: Docker for AWS, see this: https://github.com/docker/for-aws/issues/74 it's a known issue only with AWS.
- run `docker service inspect srv-captain--servicename --pretty` and print the output here. Also, inspect the output and find the "Mounts" section. Does the host directory still exist on your server?

**Comment by enricodeleo** [comment]
I could finally solve the issue re-mounting the external drive provided with my instance!

It was there by default and already mounted on the first run so I couldn't imagine it would've been lost with a reboot. 

Thanks for your hints!
