### ISSUE TITLE
it is possible to collect all the logs of the instances and show in one command?

### ISSUE THREAD

**Issue by williamhatch** [githubsaturn/captainduckduck#303]
as topic.

**Comment by githubsaturn** [comment]
The command, docker logs, shows the logs from all instance of each app. If you want to combine logs of two separate services into one, you can use some linux tricks, like [this](https://stackoverflow.com/questions/3004811/how-do-you-run-multiple-programs-in-parallel-from-a-bash-script)

```
docker service logs srv-captain--my-app --since 60m --follow
```
