### ISSUE TITLE
srv-captain--postgresql-db  Name or service not known 

### ISSUE THREAD

**Issue by williamhatch** [githubsaturn/captainduckduck#308]
/usr/local/bundle/gems/pg-0.21.0/lib/pg.rb:56:in `initialize': could not translate host name "srv-captain--postgresql-db" to address: Name or service not known (PG::ConnectionBad)

but I deployed postgresql:
Your app is internally available as srv-captain--postgresql-db to other Captain apps. In case of web-app, it is accessible via http://srv-captain--postgresql-db from other apps.

might be what cause the problem?

**Comment by williamhatch** [comment]
I found it is reproducible when doing cluster. In single node will no happen.

BTW, i use docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' container_name_or_id to get the ip is different from I ping the srv-captain--app_name why?

**Comment by githubsaturn** [comment]
The IP for service is not necessarily the IP for the individual container. Can you please elaborate what is the issue that you're having and the "exact" steps to reproduce it?

**Comment by williamhatch** [comment]
docker ps even cant find the process in cluster, but single node can find the process.

1. setup captain
2. self registery enable
3. add node
3. add one-click apps for postgresql or mysql
4. cant connect it!

but in single mode, it is OK!

**Comment by githubsaturn** [comment]
> docker ps even cant find the process in cluster, but single node can find the process.

This is not a problem! This is how docker cluster mode (swarm works).


Your second part, however, is a problem. we'll look into it.

**Comment by williamhatch** [comment]
since I deploy a rails app to connect the db, in single mode works! but cluster not works that is why i using docker ps to do troubleshooting

**Comment by williamhatch** [comment]
hi, any progess in this issue when cluster?

**Comment by githubsaturn** [comment]
Yes. We're working on it. It seems to be broken on overlay network. 

Anyway, I will update here once more details are found.

**Comment by williamhatch** [comment]
nice! good to know....

**Comment by githubsaturn** [comment]
This is invalid. We had a firewall that was enabling us to reproduce this issue. Make sure your firewall is disabled on both nodes. If you want specific ufw rules, see https://captainduckduck.com/docs/firewall.html

**Comment by williamhatch** [comment]
i disabled the firewall... anyway I will try again. Thanks for the update.
