### ISSUE TITLE
Does captain complete all running HTTP request before a new version is deployed

### ISSUE THREAD

**Issue by aberba** [githubsaturn/captainduckduck#309]
Hello, curious cus its never been mentioned anywhere else about how captainduckduck handles new deployments. If I have a NodeJS server running (lets say scaled to 3 processes) and I make a new deployment, will captain ensure all request being currently handled by running server finish before deploying new version?

I want to know if a long running process will be killed before finishing when I make a new deployment.

**Comment by githubsaturn** [comment]
No, Captain has no idea about a long running process in your application, it is private to your application. However, keep in mind that Captain (Docker) doesn't kill your application when is building the new version, you application however, dies for a few seconds when the new image is being deployed.
