### ISSUE TITLE
Container IP address

### ISSUE THREAD

**Issue by dottodot** [githubsaturn/captainduckduck#31]
I been looking into how to connect to a mongodb that's in a container from my desktop and as far as I can tell you need to ssh and then use the container ip, however I noticed the container doesn't have an ip making this not possible. Is there any way around this that you know of?

**Comment by githubsaturn** [comment]
Find your mongodb container name:

`docker service ls`

it should be something like `srv-captain--something`. Then do this:

`docker service update --publish-add 3535:27017`

Then you can connect to mongodb from your laptop using IP_ADDRESS_OF_SERVER:3535. Needless to say, you can replace 3535 with anything you want as long as that port is free.

**Comment by dottodot** [comment]
Thanks that works great
