### ISSUE TITLE
Any help deploying Polymer3 on CaptainDuckDuck

### ISSUE THREAD

**Issue by nrdout** [githubsaturn/captainduckduck#311]
I tried deploy polymer3 using prpl-server using captainduckduck but i get 502 Error.

Any help on polymer3 on CaptainDuckDuck?

**Comment by githubsaturn** [comment]
502 errors are common. For troubleshooting please see below:
https://captainduckduck.com/docs/troubleshooting.html#successful-deploy-but-502-bad-gateway-error

**Comment by nrdout** [comment]
Thanks for your help, I was able to solve the issue by using this solution : https://github.com/githubsaturn/captainduckduck/issues/130

@githubsaturn
