### ISSUE TITLE
Dose Captainduckduck support reverse proxy?

### ISSUE THREAD

**Issue by PouakaiNz** [githubsaturn/captainduckduck#316]
Hi,

I was wondering if Captainduckduck could have one nginx web server hosting all the different containers? 

There's an cool tutorial here using a nginx reverse proxy for Docker, so will it work with captain? 

[https://itnext.io/run-multiple-isolated-web-applications-on-containers-with-a-single-ip-for-free-52d216f3e810](https://itnext.io/run-multiple-isolated-web-applications-on-containers-with-a-single-ip-for-free-52d216f3e810)

Thanks

**Comment by githubsaturn** [comment]
This is exactly how CaptainDuckDuck works:
https://captainduckduck.com/img/captain-architecture.png

**Comment by PouakaiNz** [comment]
Why would captain be launching apache instances then when nginx is already running then?


`sudo docker ps`

nginx:latest                            "nginx -g 'daemon of…"   10 minutes ago      Up 10 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp



`$ top -b -o +%MEM | head -n 22`

top - 22:50:33 up 8 min,  1 user,  load average: 0.14, 0.52, 0.40
Tasks: 124 total,   1 running,  88 sleeping,   0 stopped,   0 zombie
%Cpu(s): 15.8 us, 14.7 sy,  0.5 ni, 67.9 id,  1.0 wa,  0.0 hi,  0.1 si,  0.1 st
KiB Mem :  1009048 total,    66832 free,   623796 used,   318420 buff/cache
KiB Swap:        0 total,        0 free,        0 used.   192924 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
  386 root      19  -1  529384 307304 306540 S  0.0 30.5   0:54.72 systemd-journal
  564 mysql     20   0 1154392 163016   1796 S  0.0 16.2   0:00.78 mysqld
 2575 www-data  20   0  484060  65896  39704 S  0.0  6.5   0:03.77 **apache2**
 3899 www-data  20   0  408276  63396  39288 S  0.0  6.3   0:01.95 apache2
 2694 www-data  20   0  484588  62652  36072 S  0.0  6.2   0:02.33 apache2
 2576 www-data  20   0  482280  61652  37352 S  0.0  6.1   0:00.80 apache2
 2574 www-data  20   0  404272  60180  40272 S  0.0  6.0   0:03.57 apache2
 1615 999       20   0  607708  59900   2312 S  0.0  5.9   0:01.20 mysqld
 2573 www-data  20   0  408088  58176  34352 S  0.0  5.8   0:01.24 apache2
 2578 www-data  20   0  398040  53696  40036 S  0.0  5.3   0:01.40 apache2
  579 root      20   0  829656  45732   8528 S  0.0  4.5   0:05.71 dockerd
 2598 root      20   0 1225232  35972   8104 S  0.0  3.6   0:02.69 node
 1269 root      20   0  181136  33932    748 S  0.0  3.4   0:07.83 netdata
 1684 root      20   0  982044  18436   2916 S  0.0  1.8   0:00.66 npm
  510 root      20   0  549280  14580   2704 S  0.0  1.4   0:00.41 snapd
`

**Comment by githubsaturn** [comment]
CaptainDuckDuck does not start apache automatically. You can check the applications that are started by CaptainDuckDuck via `docker ps`

**Comment by githubsaturn** [comment]
However, you can run an apache via CaptainDuckDuck. For example, if you spin up a WordPress container, it spins up an apache process inside that container.

**Comment by githubsaturn** [comment]
By default, CaptainDuckDuck runs:
- CaptainDuckDuck
- nginx
- certbot
- NetData  (optional)
- Registry (optional)

**Comment by PouakaiNz** [comment]
Right I see so if the Apache processes are coming from WP container, is there any way to get them served by to the already running nginx server?

I used the quick install wordpress button you have setup in captain, its a great app btw

**Comment by githubsaturn** [comment]
CaptainDuckDuck uses a fully containerized architecture. It means all your applications are running inside their own containers. 

Again, have a look at this: https://captainduckduck.com/img/captain-architecture.png

You can have a custom made docker image for your wordpress that uses nginx fpm for serving php files, but the standard solution offered by WordPress official docker image is using apache.

**Comment by PouakaiNz** [comment]
Still battling through this, for anyone else going down this same road here's where I've got to:

CaptainDuckDuck is working and PHP-FPM test is working [nginx-php-advanced.tar](https://github.com/githubsaturn/captainduckduck/blob/master/captain-sample-apps/nginx-php-advanced.tar) showing "Hello CaptainDuckDuck!"

So now onto WordPress-FPM;

In CaptainDuckDuck I've gone into Apps->One Click Install->WordPress
I've indicated (tagged) Docker to install the "4.9-php7.2-fpm" package from [Docker Wordpress Versions](https://hub.docker.com/r/library/wordpress/tags/)

and also Mysql Version "5.6" [Docker MYSQL Versions]( https://hub.docker.com/r/library/mysql/tags/)

Everything installs correctly with no errors in the log files, great!

Now when I go to my WordPress installation url, I get a 502 Bad Gateway from Nginx.

checking the Nginx log `docker service logs captain-nginx --since 60m --follow` 
It reports [error] 7#7: *1599 connect() failed (111: Connection refused) while connecting to upstream

And this is where I'm stuck, I think the issue is the internal port that Nginx-FPM is looking for?

So i tried editing /etc/php/7.2/fpm/pool.d/www.conf:

listen = /run/php/php7.2-fpm.sock
to
listen = 0.0.0.0:9000

as per this [stackoverflow answer ](https://stackoverflow.com/questions/48388983/nginxphp-fpm-connection-refused-while-connecting-to-upstream-502)

Sadly to no avail, so I'm wondering what to try next..

**Comment by githubsaturn** [comment]
But even this is not going to work. If you want the advanced usage of containers, like wordpress fpm, you need to understand how containers work. Unfortunately, it is not a simple concept. Have a look at this:
https://www.howtoforge.com/tutorial/dockerizing-wordpress-with-nginx-and-php-fpm/

Even in the comments of this article, most people are saying that this doesn't work.

**Comment by PouakaiNz** [comment]
Thanks for your help, Surely this must be possible however? 

Changing the port to :9000 fixed the 111 connection refused error, cheers.

Now I'm getting  [error] 10#10: *330 recv() failed (104: Connection reset by peer) 
this could possibly be a memory error as I only have 1 gb server spun up atm?

**Comment by githubsaturn** [comment]
> this could possibly be a memory error as I only have 1 gb server spun up atm?

I don't think so.

Port 9000 is your fpm port, which is different from http port. In the same nginx configuration that you changed to port 9000, you need to make further changes. I am not an fpm expert, but this configuration might help:
https://github.com/mjstealey/wordpress-nginx-docker/blob/master/nginx/wordpress.conf.example
