### ISSUE TITLE
[Feature Request] searX one-click-app

### ISSUE THREAD

**Issue by MartinHennrich** [githubsaturn/captainduckduck#318]
Please add [searX](https://github.com/asciimoo/searx) by @asciimoo as CaptainDuckDuck one-click-app

**Comment by RalphPfeiffer** [comment]
An ELK stack, Gitea, NextCloud and Pritunl would be sweet too. 😍 
Shall I open separate issues for those?

**Comment by githubsaturn** [comment]
Please add one click app suggestions to this thread, if it's not already there.

**Comment by githubsaturn** [comment]
https://github.com/githubsaturn/captainduckduck/issues/258
