### ISSUE TITLE
Deploying a php-app Using bitbucket private repo

### ISSUE THREAD

**Issue by l-lawliett** [githubsaturn/captainduckduck#321]
I am trying to deploy an a simple app using Captain Duck Duck, this is working fine when using Tarball method.
Later when i tried deployment using Deploy from Bitbucket, this is not working for me 

I notice someone had a similar issue you had help the person out. They were using github but i am using bitbucket.

I extracted the working tar copy and created a bitbucket git repo for the same and tried deploying as per the instructions given in the github/bitbucket repo

but it still fails

POST /api/v1/user/webhooks/triggerbuild?namespace=captain&token=xxxxxx

 This indicates that Bitbucket sent a request to Captain server to trigger a build.

but it keep telling me Error: Wrapped: Cloning into '/captain/temp/img_raw/img-captain--test-app/47/src'...

and also

fatal: unable to access 'https://myemail%40gmail.com:MyPassword%409@https://mybitbucketusername@bitbucket.org/mybitbucketusername/test-app.git/': Could not resolve host: https

my repository field in app section of the dashboard is https://mybitbucketusername@bitbucket.org/mybitbucketusername/test-app.git

Do you think my config is wrong??????

Kindly help to sort this out.
Thanks

**Comment by githubsaturn** [comment]
> my repository field in app section of the dashboard is https://mybitbucketusername@bitbucket.org/mybitbucketusername/test-app.git


Change your repository to `mybitbucketusername@bitbucket.org/mybitbucketusername/test-app.git`. i.e., Drop `https://`

**Comment by l-lawliett** [comment]
Change your repository to mybitbucketusername@bitbucket.org/mybitbucketusername/test-app.git. i.e., Drop https://

This didnt work do you have any other solutions man i love this but the most important part I wish wud just work

**Comment by githubsaturn** [comment]
Have you tried removing the `.git` at the end as well?

**Comment by l-lawliett** [comment]
yes I just tried

**Comment by l-lawliett** [comment]
We can close now I found out how to do it bitbucket.org/mybitbucketusername/test-duck/
Remove the .git and the https

You wouldn't mind adding this methods to your documentation man I love the project......its awesome how dude how can we chat
