### ISSUE TITLE
Trying create a wildfly on captain Duck Duck by following dockerfile

### ISSUE THREAD

**Issue by l-lawliett** [githubsaturn/captainduckduck#322]
Okay trying to launch a Java Webapp on Wildfly server using Captain Duck Duck

I follow the normal way how Docker does it using my dockerFile but when I convert the DockerFile ro capatain-definition it build the server but  it's not copying my project to the standalone package that deploy my application.

captain-definition file:

{
  "schemaVersion": 1,
  "dockerfileLines": [
    "FROM jboss/wildfly",
    "ADD test.war /opt/jboss/wildfly/standalone/deployments/"
  ]
}

I also Change ADD to COPY an it didn't work same way....what advice do you have

**Comment by githubsaturn** [comment]
From [docs](https://captainduckduck.com/docs/captain-definition-file.html#convert-dockerfile-to-captain-definition)

> Captain generates a dockerfile and puts it besides a directory named `src` where your source code sits. So if in your normal dockerfile, you have `COPY ./somefile /usr/app`, you will have to change it to `COPY ./src/somefile /usr/app` otherwise deploy would fail.

**Comment by l-lawliett** [comment]
Build started for java-app
Step 1/2 : FROM jboss/wildfly

---> 90d24f5bebd8
Step 2/2 : COPY ./src/app /usr/app

---> f48cd09c620d
Successfully built f48cd09c620d
Successfully tagged img-captain--java-app:latest

I got this but when i go to my app url.....i can't any respond from my web service

**Comment by githubsaturn** [comment]
Do you get a 502 error message when you visit the app's URL? If so, follow these steps:
https://captainduckduck.com/docs/troubleshooting.html#successful-deploy-but-502-bad-gateway-error

**Comment by l-lawliett** [comment]
I got it to show my wildfly server but I don't know why I can't place my .war file in the standalone folder do you know of anyway I can place the war file there through my normal cli or allow captain duck duck to automatically place it there can't seem to figure it out....

**Comment by githubsaturn** [comment]
Even after you changed your Dockerfile according to this? https://github.com/githubsaturn/captainduckduck/issues/322#issuecomment-439657585

Your `captain-definition` file is

```
{
  "schemaVersion": 1,
  "dockerfileLines": [
    "FROM jboss/wildfly",
    "ADD ./src/test.war /opt/jboss/wildfly/standalone/deployments/"
  ]
}
```

**Comment by l-lawliett** [comment]
> Even after you changed your Dockerfile according to this? [#322 (comment)](https://github.com/githubsaturn/captainduckduck/issues/322#issuecomment-439657585)
> 
> Your `captain-definition` file should be this: Notice the `src` in `ADD`
> 
> ```
> {
>   "schemaVersion": 1,
>   "dockerfileLines": [
>     "FROM jboss/wildfly",
>     "ADD ./src/test.war /opt/jboss/wildfly/standalone/deployments/"
>   ]
> }
> ```

This works bro so tru now I know CaptainDuckDuck is the tru Heroku I will recommend this to everyone I know bro u have created such a tool. All the best
