### ISSUE TITLE
Port mapping disabled on every push

### ISSUE THREAD

**Issue by bilicio** [githubsaturn/captainduckduck#326]
The Port mapping are disabled on command"captainduckduck deploy".
In the admin panel i set Port Mapping Server Public Port:3031 and Container:80. and when i test the app it works as it should. but when i do another deploy, the Port mapping stop work until i get in to the admin panel and press "Save and Update Configuration". the port are saved always in the admin but didnt work right away. i need always come back and press the button.

there is any way to keep the configuration saved after the deploy? like, verify if there is a port mapping after the deploy command?
Thank you!

**Comment by githubsaturn** [comment]
Thanks for reporting this. This is a bug and it's fixed in https://github.com/githubsaturn/captainduckduck/commit/75a6fd494710a6cc7108b85b312817e0abe6abf5

It will be included in the next release soon.

**Comment by bilicio** [comment]
You are welcome! :)
