### ISSUE TITLE
[Question] Can I test in localhost?

### ISSUE THREAD

**Issue by brilvio** [githubsaturn/captainduckduck#33]
Hi there,

I love the idea, but can I test using only one machine using /etc/hosts for resolving the dns?

I tried but I can't change the Captain Root Domain it says: `Verification Failed.`

And tried `captainduckduck serversetup` and the response is:
```
Error: 1107
Error: Verification Failed.
```

**Comment by brilvio** [comment]
I resolved, I am using Ubuntu I had a dnsmasq but I think it didn't work correctly so I installed, and I edited this file only: 
`/etc/dnsmasq.conf` and restarted the service.

Thanks.

**Comment by brilvio** [comment]
Now when using : 
`captainduckduck serversetup` I have this response:
```  
Error: 1107
Error: Unexpected output when enabling SSL forcaptain.captain.x with ACME Certbot 
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Obtaining a new certificate
An unexpected error occurred:
The request message was malformed :: Error creating new authz :: Name does not end in a public suffix
Please see the logfiles in /var/log/letsencrypt for more details.
```

**Comment by githubsaturn** [comment]
Of course, you cannot enable https on localhost. Just use plain captainduckduck login.

**Comment by brilvio** [comment]
Sorry didn't know that existed another command to login.

**Comment by amanvishnani** [comment]
Any way to configure DNS on windows? the default host file does not support wildcards.

**Comment by githubsaturn** [comment]
Google suggests this one can be used:
http://mayakron.altervista.org/wikibase/show.php?id=AcrylicHome

DISCLAIMER: I never used it! I just found it on Google
