### ISSUE TITLE
Can I assign multiple unique domain to multiple apps

### ISSUE THREAD

**Issue by l-lawliett** [githubsaturn/captainduckduck#331]
I have a Captain Duck Duck setup usually i can setup multiple virtual host with separate domains how do I do so using Captain Duck Duck I try to point the new domain. I use to do so by creating a symbolic link can explain if this is possible and how can I do so. Please asap

**Comment by githubsaturn** [comment]
Yes. For each app, there is a section called: `Add Custom Domain`. You can add multiple domain to any apps you want. For example, if you have app1 and app2. You can:
- Make `app1` accessible to `www.app1.com`  `app1.com`  `www.app1.org`
- Make `app1` accessible to `www.app2.com`  `awesomeapp.com`  and etc.

**Comment by l-lawliett** [comment]
I dont see add custom domain I see connect new domain.....?

**Comment by githubsaturn** [comment]
Same thing

**Comment by l-lawliett** [comment]
Okay I added a root domain name www.xyz.com but when i create an app which DuckDuck auto generated my-app.xyz.com this url and try to connect to www.abc.com it says fail to verify?

**Comment by githubsaturn** [comment]
When you see `Fail to Verify` it means that Captain has tried `www.abc.com` to see if it points to the same IP as your `www.xyz.com` but it wasn't.

You need to make sure that `www.abc.com` points to your server IP, exactly, similar to `www.xyz.com`.

**Comment by l-lawliett** [comment]
can you type this www.playnbalive.com because i know it is pointing to the server

**Comment by githubsaturn** [comment]
It is pointing to `165.227.214.15` 

Is this your server IP?

**Comment by githubsaturn** [comment]
Sometimes, it takes a few hours for DNS changes to show up. As they might be cached in your server. I suggest wait up to 24hr, and try again. If this doesn't work, please let me know here and we'll investigate.

**Comment by l-lawliett** [comment]
Okay it work it was a propagation problem thanks very much

**Comment by githubsaturn** [comment]
Awesome! Glad to hear.

**Comment by githubsaturn** [comment]
Yes, and yes. The only caveat is that, if your dashboard is at `captain.domain.com` and you have an app called app1:
* The default domain is `app1.domain.com`
* You cannot assign `app2.domain.com` to app1. It's intentional because what if you create an app called app2.
* But you can assign `one.domain2.com` `two.domain2.com`
* Or you can assign `app1.apps.domain.com` `app2.apps.domain.com` etc....

As long as the domain doesn't conflict with an existing or future app, you're good to go.

**Comment by kristijanPetr** [comment]
@githubsaturn well my idea was to assign CNAME record to point to specific app( subdomain) as its not possible to add A record to docker container. But unfortunately to your answer its not possible to add subdomain as new domain to an app
