### ISSUE TITLE
Does anyone here tried deploying gatsbyjs site on CDD?

### ISSUE THREAD

**Issue by iamrommel** [githubsaturn/captainduckduck#334]
I'm starting to learn this GatsbyJS and it's kinda cool.  And CDD is another cool tool so i want this two tools become "cooler".

Does anyone here have experience working Gatsby and CDD? What are the things i need to look into? 

They got docs on deployment for heruko https://www.gatsbyjs.org/docs/deploying-to-heroku/#deploying-to-heroku

So i think it would be cooler if we can expose CDD on GatsbyJs community

**Comment by githubsaturn** [comment]
As far as I know, Gatsby creates static files at the end of its build process. You can use a technique similar to this:
https://captainduckduck.com/docs/recipe-deploy-create-react-app.html
