### ISSUE TITLE
CDD - CLI - Deploy/Login - NodeJS v10 issue.

### ISSUE THREAD

**Issue by tuefekci** [githubsaturn/captainduckduck#335]
Hello and sorry for the quick writeup, its sunday night ;) .

since 0.7.3 i cant deploy/login anymore via CDD-Cli  .tar gets created but than nothing happens (freeze until ctrl+c) also login does not respond anymore after the name of the server is filled in, manual deploy via -s with username and password is working fine did an npm install captainduckduck & npm update -g etc. did not work yet, i will try to remove the cli completly and reinstall in the week that could probably fix it.

this is still a bad user experience especialy for people who are new to CDD.

This issue is close to #328 but it extends it a bit due to login issues and more explanation.

Thanks.

**Comment by githubsaturn** [comment]
Thanks for reporting this. But I doubt this has anything to do with v0.7.3. It looks like a CLI app bug to me. More specifically https://github.com/githubsaturn/captainduckduck/issues/328 was reported before v0.7.3 which seems to be the same.

My best guess is something in the OS level has changed that freezes saving data or transmitting data. To help me debug, can you please let me know:
- Your OS where you use the CLI app?
- When you use `captainduckduck login` do you see this message? `Logged in successfully to ...`?

**Comment by tuefekci** [comment]
git archive and generation of the tar works fine, i checked that right after i found the other issue.

- OS: Windows
- No message thats why it looks to me like bug and not an network error because deploy via -s and attributes works.

thats basicly where it freezes until i quit the process.
![cpp_bug](https://user-images.githubusercontent.com/2657626/49755711-5cbf7280-fcb9-11e8-8698-62ae4f9999cb.jpg)

**Comment by githubsaturn** [comment]
I just tested on my Windows 10 and it works fine. I might need to ask you for more information to be able to debug this as I don't have a producible case on my end.

The fact that you are not seeing anything after entering Captain Machine Name, leads to be fact that the HTTP request for login is frozen:
https://github.com/githubsaturn/captainduckduck/blob/master/app-cli/captainduckduck-login.js#L153

Anyways, I will write up a debugging script asap and will send it here so you can run it on your machine and get some more debugging info.

**Comment by tuefekci** [comment]
L153 Returns fine https://github.com/githubsaturn/captainduckduck/blob/master/app-cli/captainduckduck-login.js#L220 fails due to response 
`{
    "status": 1000,
    "description": "password is empty."
}`

iam also going through the code on my site 👍

**Comment by tuefekci** [comment]
https://github.com/githubsaturn/captainduckduck/blob/master/app-cli/captainduckduck-login.js#L168 sends a form formated body but https://github.com/githubsaturn/captainduckduck/blob/master/app-backend/src/routes/LoginRouter.js#L12 requests a json body is that right?

**Comment by githubsaturn** [comment]
Found the issue. It's not the backend code. It's the local nodejs.

I just updated NodeJS on my local windows machine, and I can now produce the bug. They have probably changed something under the hood with spawned off processes. I can even make the CLI freeze without hitting the API at all.

Try this:
`captainduckduck logout`  and select cancel. It will freeze, right?

**Comment by tuefekci** [comment]
@githubsaturn looks like you found it out, good work. I am on v10.14.1 which is LTS.

**Comment by githubsaturn** [comment]
Will communicate here once fixed.

**Comment by githubsaturn** [comment]
Fixed in https://github.com/githubsaturn/captainduckduck/commit/38255569d1ad450ea4922b235f4795f8fd1e9740

Update your local CLI version by:

```
npm i -g captainduckduck
```
