### ISSUE TITLE
CLI not working: captainduckduck-serversetup does not exist, try --help

### ISSUE THREAD

**Issue by roelvan** [githubsaturn/captainduckduck#338]
What is the problem? Cannot use the CLI, related to? https://github.com/dozjs/doz-cli/blob/master/src/doz-component.js

Steps to reproduce the problem: Freshly install the CLI and run `captainduckduck serversetup`

Answers to the following questions where applicable:
- Your OS and version? Mac, latest. NVM and installed using YARN

**Comment by githubsaturn** [comment]
1- Can you reproduce this bug if you use the regular node installation `npm -g i captainduckduck`?
2- What is your node version when using nvm+yarn?

**Comment by roelvan** [comment]
I tried the regular npm too and am getting the same error. Both on node
9.10.0 and 10+.

**Comment by githubsaturn** [comment]
Confirmed. But this is not a CaptainDuckDuck/Commander bug. This is an nvm bug. Steps to 100% reproduce the issue:


```
docker run -it node:8 /bin/bash  # starting a fresh node container

##### RUNNING THIS COMMANDS:

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
source /root/.bashrc 
nvm install node
yarn global add captainduckduck
captainduckduck list #################### THIS WILL FAIL
npm i -g captainduckduck
captainduckduck list #################### THIS WILL ALSO FAIL
yarn global remove captainduckduck
npm uninstall -g captainduckduck
nvm use system
npm i -g captainduckduck
captainduckduck list #################### THIS WILL WORK!!!
```

Therefore, to fix, just use the system version:

```
yarn global remove captainduckduck
npm uninstall -g captainduckduck
nvm use system
npm i -g captainduckduck
captainduckduck list #################### THIS WILL WORK!!!
```

**Comment by githubsaturn** [comment]
Having said this, I found out that there is a workaround for installation issue with yarn.
Similar to https://github.com/vuejs/vue-cli/pull/206/files


I made the changes in 1.0.18 https://github.com/githubsaturn/captainduckduck/commit/a1ff473853001726793e3977bc04ffb438dad09e
and
https://github.com/githubsaturn/captainduckduck/commit/00312e5dacb19c9b51811845d6b382e5e69db6bf


This also fixed the issue with nvm.
