### ISSUE TITLE
Unable to access to mysql db generated when creating a one-click wordpress app from both a laptop and inside the server

### ISSUE THREAD

**Issue by NishidaRyu416** [githubsaturn/captainduckduck#339]
Inside the server, I executed this command, `mysql -h 127.0.0.1 -p 3306  -u root `, however, this really didn't work, instead, I got the following error, `ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)`

On my laptop, I tried to connect to mysql, by entering some variables to the mysql client.
The variables were, `my server's IP` for the `host`, `3306` for the `port`, `mysql root password` for the `password`, `root` for the `username`.

I hope someone helps me out, Thanks.

**Comment by githubsaturn** [comment]
You need to use port mapping. See https://captainduckduck.com/docs/one-click-apps.html#connecting-to-databases

**Comment by NishidaRyu416** [comment]
Actually I did add 7777for the port and 77 for the container port, however it still didn’t work well

**Comment by githubsaturn** [comment]
Port 77 ?? Why? MySQL runs on 3306.

**Comment by NishidaRyu416** [comment]
Oh now it works.
I didn’t know how it worked, thanks for teaching!
