### ISSUE TITLE
[Webhook Deployment Bitbucket] Build stuck on "Build started"

### ISSUE THREAD

**Issue by qmidy** [githubsaturn/captainduckduck#345]
Hi,

Thanks for developping such a great PaaS. 

I got a little deployment issue, i tried to use a webhook on bitbucket on my api but the build is stuck :

![image](https://user-images.githubusercontent.com/5627607/51131683-b83ccd00-1830-11e9-92ca-fcc1c868bff2.png)

It feels like Captain recognizes the hook (because there is a build started message) but nothing happens after that. 

Also, I tried the test api but .tar deployment and it's working fine and so i use the same captain-definition file for my node api.

Here is my webhook config on bitbucket :

![image](https://user-images.githubusercontent.com/5627607/51131905-3bf6b980-1831-11e9-9383-d6dd511c0957.png)

(I tried with and without SSL).

I can't see any error message... And haven't found any similar case in the issues. 

May someone help ? 

Thx in advance

**Comment by githubsaturn** [comment]
Double check your credentials that you entered for your bitbucket. Probably Captain fails to clone your repo. Make sure the credentials are in the correct format:

username: your@email.com
password: yourpassword
repository: bitbucket.com/yourbitbucketuser/yourreponame
branch: master

Note that repository should not have http or https prefix.


If everything looks good, then run the following command on your server:
```
docker service logs captain-captain --since 60m --follow
```

While you are looking at the logs, push a new version to your bitbucket. Copy and paste the logs here and we'll investigate what caused the issue.

**Comment by qmidy** [comment]
Thanks for the quick answer... 

As you said, I changed the login informations on bitbucket and now it's fine. 

Sorry for my dumb head and nice job ! 

Quentin
