### ISSUE TITLE
502 Bad gateway error

### ISSUE THREAD

**Issue by oliverpople** [githubsaturn/captainduckduck#347]
**What is the problem?**
I've had success deploying the sample apps and now want to deploy my own node(+react) app. However, I receive the 502 error when I open my public app URL in the browser. 

My captain-definition file looks like this:

```
{
 "schemaVersion":1 ,
 "dockerfileLines" :[
                       "FROM node:10.8.0",
                       "RUN mkdir -p /usr/src/frontend",
                       "COPY ./src/client /usr/src/frontend",
                       "WORKDIR /usr/src/frontend",
                       "RUN npm install && npm cache clean --force",
                       "RUN npm run build   ## THIS IS THE COMMAND THAT BUILDS FRONTEND CODE, IT MIGHT BE DIFFERENT DEPENDING YOUR PACKAGE.JSON",
                       "RUN mkdir -p /usr/src/app",
                       "WORKDIR /usr/src/app",
                       "COPY ./src/package.json /usr/src/app/",
                       "RUN npm install && npm cache clean --force",
                       "COPY ./src /usr/src/app",
                       "RUN ls /usr/src/frontend/",
                       "RUN ls /usr/src/frontend/build",
                       "RUN ls /usr/src/frontend/build/static",
                       "RUN cp -r /usr/src/frontend/build /usr/src/app/  ## DIRECTORIES MAY CHANGE DEPENDING ON YOUR PACKAGE.JSON CONFIG",
                       "ENV NODE_ENV production",
                       "ENV PORT 80",
                       "EXPOSE 80",
                       "CMD [ \"nodemon\", \"server.js\" ]"
                   ]
}

```
**What have I tried?:**

I've checked the app's logs, which show that it's running: 

>Last login: Tue Jan 15 15:10:08 2019 from 172.103.230.110
root@jsonar-test:~# docker service ps captain-captain --no-trunc
ID                          NAME                    IMAGE                                NODE                DESIRED STATE       CURRENT STATE           ERROR               PORTS
f2n6l5bab08n3lq8orapz8e60   captain-captain.1       dockersaturn/captainduckduck:0.7.3   jsonar-test         Running             Running 3 hours ago
qkowgaxmzvvcrjbvmc5jrqha7    \_ captain-captain.1   dockersaturn/captainduckduck:0.7.3   jsonar-test         Shutdown            Complete 3 hours ago
79wb59f0vqq9tinu3f1j7vrp9    \_ captain-captain.1   dockersaturn/captainduckduck:0.7.3   jsonar-test         Shutdown            Complete 3 hours ago
z7bsuulqgziyg7dcu1bqptwha    \_ captain-captain.1   dockersaturn/captainduckduck:0.7.3   jsonar-test         Shutdown            Shutdown 19 hours ago
vh3gugiblh82b9sd8phx4kufw    \_ captain-captain.1   dockersaturn/captainduckduck:0.7.3   jsonar-test         Shutdown            Shutdown 19 hours ago

I've also run `ufw disable`.

For ref my node server.js looks like this:

```
var express = require("express");
var login = require("./routes/loginroutes");
var customersRoutes = require("./routes/customersRoutes");
var bodyParser = require("body-parser");
var app = express();
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header(
    "Access-Control-Allow-Headers",
    "Origin, X-Requested-With, Content-Type, Accept"
  );
  next();
});
var router = express.Router();

app.use(express.static(path.join(__dirname, "build")));

app.get("/", function(req, res) {
  res.sendFile(path.join(__dirname, "build", "index.html"));
});

router.post("/register", login.register);
router.post("/login", login.login);
router.get("/customernames", customersRoutes.customernames);
router.post("/customerfilter", customersRoutes.customerfilter);
router.post("/customerorderinfo", customersRoutes.customerorderinfo);
app.use("/api", router);
app.listen(4000);
```

My node app (backend/ in root dir) package.json script:

```
{
"name": "jsonartest",
"version": "1.0.0",
"description": "A web app for accessing and viewing customer data.",
"main": "index.js",
"scripts": {
"test": "echo "Error: no test specified" && exit 1"
},
"repository": {
"type": "git",
"url": "git+https://github.com/oliverpople/jSonarTest.git"
},
"author": "Oliver Pople",
"license": "ISC",
"bugs": {
"url": "https://github.com/oliverpople/jSonarTest/issues"
},
"homepage": "https://github.com/oliverpople/jSonarTest#readme",
"dependencies": {
"dotenv": "^6.2.0",
"express": "^4.16.4",
"mysql": "^2.16.0",
"async": "^2.1.5",
"body-parser": "^1.16.0",
"node-cmd": "^2.0.0",
"node-session": "^1.2.1",
"promise": "^7.1.1",
"rmfr": "^1.0.2"
}
}

```
My directory structure:

├── README.md
├── captain-definition
├── client
│   ├── README.md
│   ├── build
│   ├── node_modules
│   ├── package-lock.json
│   ├── package.json
│   ├── public
│   └── src
├── deploy.tar
├── node_modules
├── package-lock.json
├── package.json
├── routes
│   ├── customersRoutes.js
│   └── loginroutes.js
├── server.js
├── sql
│   └── mysqlsampledatabase.sql
└── userdata
└── username.json

Answers to the following questions where applicable:

Your OS and version? Ubuntu Docker 18.06.1ce3 on 18.04
RAM? 3GB

**Comment by githubsaturn** [comment]
First, why are you using ` "CMD [ \"nodemon\", \"server.js\" ]"`? Nodemon is mainly for development. Change it to  ` "CMD [ \"node\", \"server.js\" ]"`

Second, the 502 error means that nginx cannot connect to your server. See here for resolutions:
https://captainduckduck.com/docs/troubleshooting.html#successful-deploy-but-502-bad-gateway-error

**Comment by githubsaturn** [comment]
Is this your source code? https://github.com/oliverpople/jSonarTest/blob/master/backend/server.js#L30

If it is, then the issue is in your source code. You are listening to port 4000 - regardless of the PORT env var that you set.

You need to change it to 
```
app.listen(Number(process.env.PORT || 4000));
```
