### ISSUE TITLE
https on internal url

### ISSUE THREAD

**Issue by dottodot** [githubsaturn/captainduckduck#35]
I've noticed that you can use internal urls between apps i.e `http://srv-captain--myapp-api` which I assume should be a bit quicker than using external urls. However is doesn't work with https. Is that even possible to achieve?

**Comment by githubsaturn** [comment]
You are correct that it's faster. And since they're not public URLs https doesn't work. However it's not something that you should be concerned about as this communication happens in your private network anyways. Therefore it's inheritly secure.
