### ISSUE TITLE
Procfile support

### ISSUE THREAD

**Issue by dhyegofernando** [githubsaturn/captainduckduck#37]
It would be great to have `Procfile` support like Heroku does.

e.g. Implementation sample >>> https://github.com/ddollar/foreman

**Comment by githubsaturn** [comment]
I guess you answered your own question :wink: 

Jokes aside, Captain is not intented to be used a pixel-to-pixel replica of Heroku, nor it's a process manager. Captain is a deployment platform. 

Procfile defines two things:
- how to run your app (basically what programming language you used)
- what are the processes that you want to run

The first one is simply captain-definition file. The second point is also doable with Captain. This is the part where you answered yourself. If you want to run a `procfile` simply add it to your dockerfileLines in your captain-definition file. Read advanced version here: https://github.com/githubsaturn/captainduckduck/wiki/Captain-Definition-File

So adding support for Procfile means that you can save writing a simple `captain-definition` file like:
```
{
 "schemaVersion" :1 ,
 "templateId" :"node/8.7.0"
}
```

Needless to say, there is a ton of higher priority stuff in the pipeline... So we'll be focusing on those :+1:
