### ISSUE TITLE
Private network and service port

### ISSUE THREAD

**Issue by anddimario** [githubsaturn/captainduckduck#40]
Hi, i'm looking the docs, maybe i wrong, but it seems that all service are exposed on public network, is there a way to expose only necessary service (port 80/443 only?) on public network and the other services on private?

**Comment by githubsaturn** [comment]
Port 80 and Port 443 are the only ports that are exposed. All services that you deploy remain on the private Network.  Not only that, but you also have an option to remove service from nginx such that it's not accessible from the outside world and it's only accessible as an internal service to the other services.
