### ISSUE TITLE
How to debug the APP or check logs

### ISSUE THREAD

**Issue by dpvenkatesh** [githubsaturn/captainduckduck#47]
Awesome work..

**My Qsn:** 
My node app was not coming up, coz of some code issue. I was not sure what was breaking the app.
Is there a way to check logs?

**Comment by githubsaturn** [comment]
Are you talking about build logs or regular logs during operation?
- Build logs: wait for v0.3 which will come out in next few days. See https://github.com/githubsaturn/captainduckduck/issues/26
- Execution logs. You can ssh to your server and run `docker service logs srv-captain--myawesomeapp` (of course replace `myawesomeapp` with your app name)
