### ISSUE TITLE
Can it deploy Ruby on Rails?

### ISSUE THREAD

**Issue by alialsaif** [githubsaturn/captainduckduck#63]
Can captain deploy ruby on rails applications?

**Comment by githubsaturn** [comment]
@alialsaif 
There's a pull request open for it. I had some concerns. Are a professional Ruby dev? Is so, do you mind taking a look at it? I just had some concerns regarding rackup command being generic and non-opinionated.

**Comment by githubsaturn** [comment]
Implemented in https://github.com/githubsaturn/captainduckduck/commit/bee43e06e0c03e6cf078f09c6d3e6396c4c0de25

Will be released in `v0.5.0` in next few days.

**Comment by githubsaturn** [comment]
https://github.com/githubsaturn/captainduckduck/releases/tag/V0.5.1

**Comment by zmd94** [comment]
Just want to confirm that RoR can be deployed in CPP.

#324
