### ISSUE TITLE
Container shutdown when 1 instance available

### ISSUE THREAD

**Issue by nampdn** [githubsaturn/captainduckduck#64]
Hi, thanks for your awesome work.
Just install CDD in my server, add a node to swarm, and try to deploy example nodejs app.
I can deploy it from the CLI. But the application after that won't automatically start.
I try to spin up the instance to 2, and it run only 1. If spin to 3, still only 1 is running, all the rest is still shutdown when I inspect by `docker node ps` command. And it only run in my host manager machine without replicate it to the worker.
Besides, I tried to create mongo app with one click. Can't see the container available in `docker node ps` and can't access it too.

How can I figure all of this out?

![screen shot 2017-12-19 at 8 01 13 pm](https://user-images.githubusercontent.com/26531658/34158491-3da18c32-e4f8-11e7-96cc-e4d936812b3b.png)

**Comment by githubsaturn** [comment]
Make sure to deploy your image after you have set the docker registery. Just re-deploy the app and see if it solves it. 

The reason is that when you deploy the app before connecting to registry, the image is not replicated in the registry. Therefore only manager has access to it.

**Comment by nampdn** [comment]
I can make sure that the registry is working as I configure it as self registry hosting and the worker node is joined.
I re-deploy the sample node app, replicate it to 10 instance, but only 5 instance up and running.

**Comment by githubsaturn** [comment]
Bizarre. I'll be able to look into this in a few hours. Stay tuned.

**Comment by githubsaturn** [comment]
By the way, do you have any firewall enabled on your manager node. Particularly port 996? You may want to disable your fireball temporarily and retry.

**Comment by nampdn** [comment]
Ok, I'll try to disable ufw for a while.

**Comment by nampdn** [comment]
Here is the result after I disable the firewall and try to create mongo-express one click. Neither works.
![screen shot 2017-12-19 at 10 00 51 pm](https://user-images.githubusercontent.com/26531658/34163035-36a17c16-e508-11e7-8af6-d4dfbbe55e7d.png)

**Comment by githubsaturn** [comment]
Alright. I'll look into this.

**Comment by githubsaturn** [comment]
@nampdn 

I just retested the entire thing, and it just works for me. This is my setup/process:

- Get a 1gb server on Digital Ocean
- Setup DNS and do `captainduckduck serversetup` and successfully accessing captain at `captain.do5.mydomain.com`
- Get another 1gb server on Digital Ocean
- run `ufw disable` on both servers
- Attach the second server via Captain dashboard "Nodes" section
- Create a selfhosted docker registry via Captain dashboard
- Wait for 1 minute. Refresh the page and login to Captain to see if correctly see  `Current Docker Registry: Local at registry.do5.captainduckduck.com:996`
- Create a new app. 
- IMPORTANT: at this point, if I scale the app, it's gonna fail to create on other nodes.
- I deployed the sample nodejs app to the test app.
- Check if it's working by visiting the link
- Changed the app instance to 4.
- Run `docker service ps srv-captain--test` and I see it correctly spins up instances on worker node:
```
root@docker-1gb-nyc3-01:~# docker service ps srv-captain--test 
ID                  NAME                      IMAGE                                                      NODE                        DESIRED STATE       CURRENT STATE             ERROR                              PORTS
iwny8s8co7kx        srv-captain--test.1       registry.do5.captainduckduck.com:996/img-captain--test:1   docker-1gb-nyc3-01          Running             Running 15 seconds ago                                       
tpv7zdzhcabm         \_ srv-captain--test.1   registry.do5.captainduckduck.com:996/img-captain--test:1   docker-1gb-nyc3-01-WORKER   Shutdown            Shutdown 16 seconds ago                                      
vezk6ayqu7p1         \_ srv-captain--test.1   registry.do5.captainduckduck.com:996/img-captain--test     docker-1gb-nyc3-01          Shutdown            Shutdown 52 seconds ago                                      
rtuthnujbybc         \_ srv-captain--test.1   registry.do5.captainduckduck.com:996/img-captain--test     docker-1gb-nyc3-01-WORKER   Shutdown            Rejected 2 minutes ago    "No such image: registry.do5.c…"   
ow1i0yd6prqu         \_ srv-captain--test.1   registry.do5.captainduckduck.com:996/img-captain--test     docker-1gb-nyc3-01-WORKER   Shutdown            Rejected 3 minutes ago    "No such image: registry.do5.c…"   
q1uynplz2bv3        srv-captain--test.2       registry.do5.captainduckduck.com:996/img-captain--test:1   docker-1gb-nyc3-01-WORKER   Running             Running 18 seconds ago                                       
fwju7owg3aiw        srv-captain--test.3       registry.do5.captainduckduck.com:996/img-captain--test:1   docker-1gb-nyc3-01          Running             Running 19 seconds ago                                       
1xd733af3pgj        srv-captain--test.4       registry.do5.captainduckduck.com:996/img-captain--test:1   docker-1gb-nyc3-01-WORKER   Running             Running 18 seconds ago                                       
```

As you can see above, there are 4 instances running, 2 on main node, 2 on worker node. Can you please re-test?

**Comment by githubsaturn** [comment]
I tried with different containers and cannot reproduce the issue. Please upgrade to latest version (v0.3.1) and re-open if the issue still exists.

You can update your instance by going to web dashboard > settings > install updates.
