### ISSUE TITLE
Auth token is not valid anymore. Request for a new auth token

### ISSUE THREAD

**Issue by lucasdu4rte** [githubsaturn/captainduckduck#66]
Yesterday I did the whole installation process correctly on a DO machine, as recommended. I was able to do my first deploy in a PHP application, it was working normal, until I did refactory code, but then I turned the machine off so I did not continue counting the credits. And 11 hours later on call I waited about 10 minutes and tried to deploy again, and gave this error:

```
Pushing last commit on master: 47c9cf7e26f597d66bc65951fcbc5f0016a3a5a1
Uploading file to https://captain.manager.domain.com
 
This might take several minutes. PLEASE BE PATIENT...

Something bad happened. Cannot deploy "tradicao"
{
  "status": 1106,
  "description": "Auth token is not valid anymore. Request for a new auth token"
}
 
```

**Comment by githubsaturn** [comment]
Just do logout and login again:
captainduckduck logout
captainduckduck login

**Comment by lucasdu4rte** [comment]
Thanks!
