### ISSUE TITLE
Issues deploying: 500 Internal Server Error

### ISSUE THREAD

**Issue by khoadnguyen** [githubsaturn/captainduckduck#69]
Hello, I'm currently on v.30 and I keep getting the same deploy error every time. This is my first deployed app and I've set up the server according to the docs. The error detailed here was was uploading the test node app (no modifications) and deploying from my local machine (username and domain have been redacted).

I'm currently using a iMac on High Sierra.

I haven't ever deployed an app yet, so I can't tell if this is a bug or maybe something I'm missing. 

```
Deploying to do-captain
 
Saving zip file to:
/Users/**username**/Downloads/node/temporary-captain-to-deploy.zip
 
Pushing last commit on master: 82246e41849bc1914510eba7a7d2ac57530ee0e5
Uploading file to https://captain.app.**domain**.com
 
This might take several minutes. PLEASE BE PATIENT...

Something bad happened. Cannot deploy "node-test"

{
  "statusCode": 500,
  "body": "Internal Server Error",
  "headers": {
    "server": "nginx/1.13.7",
    "date": "Tue, 19 Dec 2017 23:14:24 GMT",
    "content-type": "text/plain; charset=utf-8",
    "content-length": "21",
    "connection": "close",
    "x-powered-by": "Express",
    "etag": "W/\"15-/6VXivhc2MKdLfIkLcUE47K6aH0\""
  },
  "request": {
    "uri": {
      "protocol": "https:",
      "slashes": true,
      "auth": null,
      "host": "captain.app.**domain**.com",
      "port": 443,
      "hostname": "captain.app.**domain**.com",
      "hash": null,
      "search": null,
      "query": null,
      "pathname": "/api/v1/user/appData/node-test",
      "path": "/api/v1/user/appData/node-test",
      "href": "https://captain.app.**domain**.com/api/v1/user/appData/node-test"
    },
    "method": "POST",
    "headers": {
      "x-namespace": "captain",
      "x-captain-auth": "**********************REMOVED****************",
      "content-type": "multipart/form-data; boundary=--------------------------884217313532410945046176",
      "content-length": 51586
    }
  }
}
 

```

**Comment by rhyneav** [comment]
I would double check to make sure your captain-definition file is 100% correct. I was getting the same exact error on a custom application, but it was because I forgot a colon in the captain-definition JSON 
¯\_(ツ)_/¯

**Comment by khoadnguyen** [comment]
I looked over the captain definition and it didn't seem off as it was unmodified from the test apps on the repo. Here is the file in its entirety: 

```
{
 "schemaVersion": 1,
 "templateId" :"node/8.7.0"
}
```

**Comment by githubsaturn** [comment]
@khoadnguyen 

- Can you please try and upload one of the sample apps? Do they work?
- How much RAM does your server have and how big is the app you're trying to deploy?

**Comment by khoadnguyen** [comment]
@githubsaturn 

This was the sample app. I took the [node.tar](https://github.com/githubsaturn/captainduckduck/tree/master/captain-sample-apps) file and unpacked it and tried the deploy using the cli rather than uploading from the gui. 

This was deploying to a Digital Ocean 1gb instance using the preinstalled Docker.

**Comment by githubsaturn** [comment]
Hmm.. That's weird. That's exactly my test setup. To help dubug the issue, please ssh to your server and run:
```
 docker service logs captain-captain --since 1m --follow 
```

while logger is logging, please retry deploying the app. Your log should include the exact error that's happening. Can you please do this and share the error message?

**Comment by khoadnguyen** [comment]
When I run it again I get this: 

![screen shot 2017-12-20 at 1 06 55 pm](https://user-images.githubusercontent.com/2165265/34228952-67bcd762-e587-11e7-9fe1-57e345def15d.png)


```
Deploying to do-captain
 
Saving zip file to:
/Users/**username**/Downloads/node/temporary-captain-to-deploy.zip
 
Pushing last commit on master: 82246e41849bc1914510eba7a7d2ac57530ee0e5
Uploading file to https://captain.app.**domain**.com
 
This might take several minutes. PLEASE BE PATIENT...

Something bad happened. Cannot deploy "node-test"

{
  "statusCode": 502,
  "body": "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.13.7</center>\r\n</body>\r\n</html>\r\n",
  "headers": {
    "server": "nginx/1.13.7",
    "date": "Wed, 20 Dec 2017 21:07:40 GMT",
    "content-type": "text/html",
    "content-length": "173",
    "connection": "close"
  },
  "request": {
    "uri": {
      "protocol": "https:",
      "slashes": true,
      "auth": null,
      "host": "captain.app.**domain**.com",
      "port": 443,
      "hostname": "captain.app.**domain**.com",
      "hash": null,
      "search": null,
      "query": null,
      "pathname": "/api/v1/user/appData/node-test",
      "path": "/api/v1/user/appData/node-test",
      "href": "https://captain.app.**domain**.com/api/v1/user/appData/node-test"
    },
    "method": "POST",
    "headers": {
      "x-namespace": "captain",
      "x-captain-auth": **Auth**,
      "content-type": "multipart/form-data; boundary=--------------------------491494128537086374834935",
      "content-length": 51586
    }
  }
}
```

The logs detail a post at the time when I hit deploy, but other than that I couldn't see any errors:

![screen shot 2017-12-20 at 1 08 07 pm](https://user-images.githubusercontent.com/2165265/34228993-8abbc1e2-e587-11e7-9099-bd7e11aedb41.png)

**Comment by githubsaturn** [comment]
@khoadnguyen 

This is not the same error you originially posted. This is a 502 error with some body attached to it, your original error is a 500 error. 

Anyways, this new error is very different. Solution:

- On your local machine, first make sure your CLI tool is up to date by running `npm install -g captainduckduck`, then run `captainduckduck logout` then `captainduckduck login`, then try to deploy again. If the problem is not gone, go to the next step
- On your server run `docker service update captain-captain --force` wait for 30 seconds and retry deploying, if the problem is not solved, go to the next step
- On your server, run the following commands and share the output
  >> `docker service ls`
  >>  and
  >> `cat /captain/generated/nginx/conf.d/captain-root.conf`

**Comment by khoadnguyen** [comment]
@githubsaturn 

I think I got it working after the I tried the first step, could be that my CLI was out of date. Thanks for your help on all of this!

**Comment by githubsaturn** [comment]
👍

**Comment by githubsaturn** [comment]
As of version v0.3.1, status 500 is not being returned as an error. Instead, the exact error and stacktrace will be returned.

Also please update your CLI to latest version to make use of pre-checks that have been added to the latest version (1.0.8)
`npm install -g captainduckduck`
