### ISSUE TITLE
Support ARM

### ISSUE THREAD

**Issue by icebob** [githubsaturn/captainduckduck#7]
Hi,

do you plan to support Raspberry PI ARMs?

**Comment by githubsaturn** [comment]
I haven't tried it on ARM processor. It might work, might not. There are dependencies that are out of reach, like nginx, if it doesn't work, it's not possible to run this image on ARM at all.

Anyways, out of criousity, why is it that you think will be useful for this project to run on Rasberry PI? This is a webserver, and most likely will run on VPS in cloud.

**Comment by FloMaetschke** [comment]
i would love to see this working on pi

**Comment by githubsaturn** [comment]
I don't have the hardware to build this against ARM. But it does work - if you have the hardware. You just need to follow these steps:
- clone the repo
- go to `app-backend` directory and run `docker build -t captain-arm -f dockerfile-captain.release .`

Then just replace `dockersaturn/captainduckduck` with `captain-arm` during installation:
```
mkdir /captain && docker run -p 80:80 -p 443:443 -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock captain-arm
# wait around 30 seconds
docker service update --image captain-arm captain-captain
```
