### ISSUE TITLE
Mysqli in PHP container

### ISSUE THREAD

**Issue by lucasdu4rte** [githubsaturn/captainduckduck#70]
My website deploy in PHP, has returned this to me, searched the internet, and talk about the lack of the mysqli extension.
Does anyone know how to install or enable mysqli in the container?

`Fatal error: Uncaught Error: Class 'mysqli' not found in /var/www/html/system/library/db/mysqli.php:7 Stack trace: #0 /var/www/html/system/library/db.php(9): DB\MySQLi->`

**Comment by githubsaturn** [comment]
Can you please create a sample test project to show the problem?

Quick googling suggest this is a config issue maybe:
https://github.com/docker-library/docs/issues/943

Anyways, please send a repro test case so I can dig into it more.

**Comment by githubsaturn** [comment]
I just tried a test app and it's working fine. I assume you were using a wrong version of PHP. Note that mysqli was deprecated in PHP7. It's available in PHP 5 though. So use this captain-definition file and you'll be fine:

```
{
 "schemaVersion" :1 ,
 "templateId" :"php/5.3"
}
```
