### ISSUE TITLE
Support for custom SSL Certificate

### ISSUE THREAD

**Issue by nampdn** [githubsaturn/captainduckduck#71]
It would be great if we can provide custom SSL Certificate from other provider such as Comodo rather than the default Let's Encrypt cert.
Can I contribute with this?

**Comment by githubsaturn** [comment]
Thanks for your suggestion. But what's the use case? Why would anyone wants to pay for something that's readily available for free and it's guaranteed to renew automatically while the paid version should be renewed manually?

**Comment by nampdn** [comment]
The use case can be apply with already purchased SSL in long-term.
In my company, we have one SSL purchased from Comodo which will work for 3 years.
By the way, sometime we need EV SSL that display Company Name in the address bar.

**Comment by githubsaturn** [comment]
I see. That's valid. Just beware this is not a one liner change. For this kind of bigger changes, after reviewing the code and finding a potential solution, please discuss your proposed solution in telegram channel before implementation. Thanks!
https://t.me/joinchat/Bgv2LEkKHCwtH-RXU9v5Aw

**Comment by githubsaturn** [comment]
https://github.com/githubsaturn/captainduckduck/releases/tag/v0.4.0

In V0.4.0, you are now able to customize your nginx config for your app. Also there is now a directory on host `/captain/nginx-shared` which is mapped to `/nginx-shared` in nginx container. Therefore, you can copy your SSL certs and reference them in your customized nginx config.

https://github.com/githubsaturn/captainduckduck/wiki/NGINX-Customization
