### ISSUE TITLE
Container stuck in loop

### ISSUE THREAD

**Issue by dottodot** [githubsaturn/captainduckduck#75]
Think this is the first deploy I've done since updating to the latest version, and it seems to be stuck in a loop where the container will disappear then start repeatedly. Not sure how to stop this short of deleting the app and starting again.

**Comment by githubsaturn** [comment]
By container you mean Captain container or your app?

If it's your app, it means it keeps crashing. Please run:
docker service logs srv-captain--yourappname


You'll see the logs of your app and why it's crashing

**Comment by dottodot** [comment]
Ok got it, thanks.
