### ISSUE TITLE
Running with Celery and Redis

### ISSUE THREAD

**Issue by sidharthv96** [githubsaturn/captainduckduck#77]
Hi,
I started using CaptainDuckDuck few days ago and have started moving all my running projects to a Single server powered by CDD... 
I have successfully moved 3 projects over. But now I'm facing a hiccup on a project that has Redis and Celery.
Should I add seperate apps for redis and celery?

**Comment by githubsaturn** [comment]
Yes - any stand alone app requires its own container (app).
Therefore, Celery and Redis require their own containers. i.e., if you want to access Redis from Celery container you would use `srv-captain--redis-app-name:6379` where `redis-app-name` is the name of container you chose for Redis and `6379` is Redis port.

PS:
Note that containers and apps are the same things. Container is terminology used by Docker, and App is used by CaptainDuckDuck.
