### ISSUE TITLE
Validating captain-definition before deployment

### ISSUE THREAD

**Issue by sidharthv96** [githubsaturn/captainduckduck#78]
Hi,
By adding a simple JSON Validation before deploying the zip to server, we can filter out simple mistakes from the client side itself.
This would be useful when working with large definition files.

**Comment by githubsaturn** [comment]
Great suggestion. Will add.

**Comment by githubsaturn** [comment]
https://github.com/githubsaturn/captainduckduck/commit/6f7f1bb37928be23c4d8baeb36550754691b86c0
