### ISSUE TITLE
Seperate healthcheck logs

### ISSUE THREAD

**Issue by sidharthv96** [githubsaturn/captainduckduck#81]
I have been running by instance for two days, My logs are flooded with 
`captain-captain.1.435og5ld4vsq@hostname    | GET /checkhealth 302 0.166 ms - 60`
`captain-captain.1.435og5ld4vsq@hostname    | GET /checkhealth 200 0.500 ms - 36`
As this happens every 5 seconds, it results in `34560` redundant lines in the logfile. 
Averaging around 80 characters per line, it wastes `2764800 bytes` of data every time I run `docker service logs captain-captain --follow`
That's a 20MB logfile for a week.
The biggest issue is that it takes a long time for the log to print to the terminal and for us to get to the end. 
It would be helpful if we could specify a --loglevel=[INFO|WARNING|DEBUG|ERROR] into the command.

**Comment by githubsaturn** [comment]
Changing behavior of `service logs captain-captain --follow` is not decided by CaptainDuckDuck, it's a pure Docker command. All CaptainDuckDuck does is to simply print to STDOUT and STDERR.
Therefore, supporting multiple levels of logs requires an internal database of logs managed by CaptainDuckDuck which is a total overhead at this point. Common practice is to use a third party logger. Again, this is not specfic to CaptainDuckDuck, there are multiple loggers available for Docker: 
: https://docs.docker.com/engine/admin/logging/overview/

Having said that, we have the ability to remove healthchecks from logs completely. But that would be not sane either. existence of healthchecks in the logs is very important indicatator that we can decided whether the application was completely frozen or healthchecks were being executed.

To address your concern, I strongy recommend you have a look at Docker logging drivers. Many of them enable you to filter out unwanted logs and have great search ability. 

PS: Performing healthchecks every 5 seconds was decided when the project was not stable. I'll change this to 20 seconds. This will lead to a significant size reduction of logs.
