### ISSUE TITLE
Optional .json extension for captain-definition

### ISSUE THREAD

**Issue by sidharthv96** [githubsaturn/captainduckduck#87]
What do you guys think about adding a .json extension to captain-definition file? It would enable many features in most text editors like automatic indentation, JSON Validation, code highlight, etc. 
I think small changes in app-cli would be enough to accomodate the modification.

The extension can be made optional, so as not to break current configurations.

**Comment by githubsaturn** [comment]
There are multiple ways to deploy the app. CLI is one of them.

So CLI change on itself won't be enough to accomodate this. Change should be done in `app-backend` which will be breaking the old contract. With recent changes in CLI (JSON validation), this additional `.json` seems to be adding no so much of value.

**Comment by sidharthv96** [comment]
I was mainly talking about the modern text editors that automatically enhances the workspace based on the file extension.

![image](https://user-images.githubusercontent.com/10703445/34404053-e901e42a-ebd1-11e7-9b49-cd6924459708.png)

Although there is validation while deploying, Text editors would help the user to not make errors in the first place, with help of code coloring and inline error checking.
![image](https://user-images.githubusercontent.com/10703445/34403977-7ffcf9f6-ebd1-11e7-8acf-9a9ba4e78425.png)

It would also point out the exact location of error if there is one.
![image](https://user-images.githubusercontent.com/10703445/34404046-da89a63a-ebd1-11e7-98bb-f5dc3f3b9c4b.png)

![image](https://user-images.githubusercontent.com/10703445/34404036-cbb2d41a-ebd1-11e7-93c6-ce7fbee1e466.png)

But all this would be useful mostly if the file is large in size.

I was thinking about checking if a captain-definition.json file was available, then process it,
else, fallback to the old captain-definition file.

Maybe this can be introduced in the next major release.

**Comment by githubsaturn** [comment]
I see what you're saying. The JSON validation that we recently added in CLI would catch this error before sending it to server. But I agree that it's nicer to have a syntax highlighter. This is something that we'll for sure consider in the next major release where we can include breaking changes.
