### ISSUE TITLE
Error when accessing database from captain-definition file. django makemigrations

### ISSUE THREAD

**Issue by sidharthv96** [githubsaturn/captainduckduck#88]
I'm getting 

`django.db.utils.OperationalError: could not translate host name "srv-captain--postgres" to address: Name does not resolve`

everytime I add `"RUN python manage.py makemigrations",` to my django apps captain-definition file.

But the apps work fine if I run the same command after logging in via the shell.

**Comment by githubsaturn** [comment]
I assume you're using a custom set of dockerfileLines, right? 

During build process, you don't have access to your services such as `srv-captain--postgres`. You should create a shell script and run this command as a CMD line in your dockerfile, not RUN.

Note that there can only be one CMD line in your dockerfile. The common practice is to create a `entrypoint.sh` file and put all your running code there. For example, see this dockerfile and entrypoint.sh here:
https://github.com/TimWolla/docker-adminer/tree/73de6b9a7979ded5d2289fe015fffe81fa32e0a4/4.3
