### ISSUE TITLE
App static files via nginx

### ISSUE THREAD

**Issue by RainerAtSpirit** [githubsaturn/captainduckduck#93]
I got an express back end app that also serves a bunch of static files. Those static files could be probably better served by nginx directly. By pulling those out of the temporary zipfile that gets deployed the size of the file would be reduced dramatically. Is that possible by manually changing some configuration files and copying the files to a specific place?

**Comment by githubsaturn** [comment]
Yes, it's possible with the new release V0.4.0. 
- Method 1 (more efficient): 
Use customized caching mechanism. The very first request for a static asset will go to your express app. But anything after that, until cache expires, will be served from nginx.
- Method 2: copy your static assets to nginx-shared directory (https://github.com/githubsaturn/captainduckduck/wiki/NGINX-Customization#custom-files-and-directories) and have it directly served by nginx. This method is not nearly as efficient and solid as the first one. 


Note that in CaptainDuckDuck instance everything is containerized and cross contamination is very minimal. The nginx container has no access to files in your app container, therefore you cannot reference your app specific files, from your nginx config which lives in nginx container. The only link between nginx and your app is a normal HTTP connection.

**Comment by RainerAtSpirit** [comment]
Excellent, so method 1 it is.
