### ISSUE TITLE
Elixir/Phoenix

### ISSUE THREAD

**Issue by nsuchy** [githubsaturn/captainduckduck#95]
Easy to use Elixir and Phoenix framework support would be awesome. Are you guys willing to add this to supported languages?

**Comment by nsuchy** [comment]
Update: I made a pull request at https://github.com/githubsaturn/captainduckduck/pull/96

**Comment by githubsaturn** [comment]
Short Answer: No.

On top of your current built-in list (NodeJS, PHP, and Python), the only languages that we have on the roadmap are Java, Scala, Ruby, Go and possibly ASP.NET. There will be an infinite number of frameworks if we want to add everything as a built-in framework.

**Having said that**, this is only applicable to "Built-in" support. You can always use **WHATEVER language** you want with CaptainDuckDuck. For example, for your Elixir app, based on your PR, you can have the following `captain-definition` file. 

```
 {
  "schemaVersion" :1 ,
  "dockerfileLines" :[
                        "FROM marcelocg/phoenix",
                        "COPY ./src /code",
                        "CMD [ \"mix\", \"phoenix.new\", \"/code/my_new_app\" ]"
                    ]
 }
```

You don't need to create a PR or add a built-in language. This generic schema is already supported. Also in your PR, you are using a non-official docker image. Have a look at other languages like NodeJS. You can find official docker images from here:https://hub.docker.com/explore/ as they receive continuous support.
