### ISSUE TITLE
How to setup PHP-FPM for Nginx container

### ISSUE THREAD

**Issue by 1zaak** [githubsaturn/captainduckduck#99]
Any directions would be helpful. I can't correctly deploy my PHP app without PHP-FPM setup on Nginx.

**Comment by githubsaturn** [comment]
Captain uses docker under the hood for containers. So you can simply google "docker nginx php fpm" and among the first results, you can find this:http://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx.html

Anyways, I've added an example for PHP app using nginx with some sample customization to give you some clue how to do things:
https://github.com/githubsaturn/captainduckduck/commit/ab63ffd4d0937d426ed7ac8baa7e21ad3371944b
